const RECIPES4 = [

// ── DIPS & STARTERS ──────────────────────────────────────
{id:124,name:'Whipped Feta with Snap Peas and Hot Honey',category:'Dips & Starters',difficulty:'easy',serves:4,time:'20 min',calories:280,mainIngredient:'Feta',
ingredients:[
  {name:'Feta',amount:200,unit:'g'},
  {name:'Skyr or Greek yoghurt',amount:3,unit:'tbsp'},
  {name:'Olive oil',amount:1,unit:'tbsp'},
  {name:'Black pepper',amount:1,unit:'to taste'},
  {name:'Lemon, zest and juice of half',amount:0.5,unit:'whole'},
  {name:'Salt',amount:1,unit:'pinch'},
  {name:'Snap peas',amount:200,unit:'g'},
  {name:'Olive oil',amount:1,unit:'tbsp'},
  {name:'Honey',amount:2,unit:'tbsp'},
  {name:'Smoked paprika',amount:1,unit:'tsp'},
  {name:'Espelette pepper',amount:1,unit:'tsp'},
  {name:'Cider vinegar',amount:1,unit:'to taste'},
  {name:'Fresh mint',amount:1,unit:'handful'},
  {name:'Toasted pistachios',amount:2,unit:'tbsp'},
],
steps:[
  'Blend feta, yoghurt, olive oil, lemon zest and juice, black pepper, and a pinch of salt until smooth. Chill in the fridge to firm slightly.',
  'Blanch or lightly sauté the snap peas with olive oil, salt, and black pepper until just tender but still crisp.',
  'Make the hot honey by gently warming honey with smoked paprika, Espelette pepper, and a few drops of cider vinegar to infuse.',
  'Arrange the whipped feta on a plate, top with snap peas, drizzle with hot honey, and finish with fresh mint, lemon zest, olive oil, and toasted pistachios.',
  'Serve.',
]},

{id:125,name:'Burrata, Anchovy, Mint and Extra Virgin Olive Oil',category:'Dips & Starters',difficulty:'easy',serves:2,time:'5 min',calories:320,mainIngredient:'Burrata',
ingredients:[
  {name:'Burrata',amount:1,unit:'whole'},
  {name:'Anchovies',amount:6,unit:'whole'},
  {name:'Fresh mint leaves',amount:1,unit:'handful'},
  {name:'Extra virgin olive oil',amount:3,unit:'tbsp'},
],
steps:[
  'Place the burrata on a serving plate.',
  'Arrange the anchovies over the burrata.',
  'Scatter fresh mint leaves on top.',
  'Drizzle generously with extra virgin olive oil.',
  'Serve immediately.',
]},

// ── SALADS ──────────────────────────────────────────────
{id:126,name:'Dill Caesar Salad',category:'Salads',difficulty:'medium',serves:4,time:'25 min',calories:240,mainIngredient:'Baby Gem Lettuce',
ingredients:[
  {name:'Baby gem lettuce',amount:2,unit:'whole'},
  {name:'Fresh dill',amount:1,unit:'bunch'},
  {name:'Creamy dill Caesar dressing',amount:4,unit:'tbsp'},
  {name:'Anchovy breadcrumbs',prep:'spicy',amount:4,unit:'tbsp'},
],
steps:[
  'Prepare the creamy dill Caesar dressing.',
  'Wash and dry the baby gem lettuce thoroughly.',
  'Toss the lettuce with the creamy dill Caesar dressing until coated.',
  'Make the spicy anchovy breadcrumbs and toast them until crispy.',
  'Plate the dressed lettuce and top generously with the anchovy breadcrumbs.',
  'Garnish with extra fresh dill before serving.',
]},

{id:127,name:'Spicy Onion Salad',category:'Salads',difficulty:'easy',serves:4,time:'15 min',calories:60,mainIngredient:'Red Onion',
ingredients:[
  {name:'Red onions',amount:2,unit:'whole',prep:'thinly sliced'},
  {name:'Tomato',amount:1,unit:'whole',prep:'finely chopped'},
  {name:'Green chilli',amount:1,unit:'whole',prep:'finely chopped'},
  {name:'Fresh coriander',amount:2,unit:'tbsp',prep:'chopped'},
  {name:'Lemon juice',amount:1,unit:'tbsp'},
  {name:'Salt',amount:1,unit:'tsp'},
  {name:'Chilli powder',amount:0.5,unit:'tsp'},
  {name:'Roasted cumin powder',amount:0.5,unit:'tsp'},
],
steps:[
  'Place the sliced onions in a bowl of cold water for 10 minutes to reduce sharpness. Drain well.',
  'Combine onions, tomato, green chilli, and fresh coriander in a mixing bowl.',
  'Sprinkle in salt, chilli powder, and roasted cumin powder.',
  'Add the lemon juice and toss everything together until evenly coated.',
  'Serve immediately as a side dish with grilled or tandoori meats.',
]},

{id:128,name:'Chilled Cucumber and Asparagus with Herb Fish Sauce Dressing',category:'Salads',difficulty:'easy',serves:4,time:'15 min',calories:80,mainIngredient:'Cucumber',
ingredients:[
  {name:'Cucumbers',amount:2,unit:'whole'},
  {name:'Asparagus',amount:200,unit:'g'},
  {name:'Fresh herbs',amount:1,unit:'handful'},
  {name:'Fish sauce',amount:2,unit:'tbsp'},
],
steps:[
  'Prepare the cucumbers and asparagus by chilling them.',
  'Chop the fresh herbs.',
  'Make a dressing by combining the herbs with fish sauce.',
  'Arrange the chilled cucumbers and asparagus on a plate.',
  'Drizzle the herb and fish sauce dressing over the vegetables.',
  'Serve immediately.',
]},

{id:129,name:'Beetroot, Whipped Ricotta and Pistachios',category:'Salads',difficulty:'easy',serves:4,time:'30 min',calories:260,mainIngredient:'Beetroot',
ingredients:[
  {name:'Beetroot',amount:4,unit:'whole'},
  {name:'Ricotta',amount:200,unit:'g'},
  {name:'Lemon',amount:0.5,unit:'whole'},
  {name:'Olive oil',amount:3,unit:'tbsp'},
  {name:'Pistachios',amount:50,unit:'g'},
  {name:'Honey',amount:1,unit:'tbsp'},
  {name:'Dijon mustard',amount:1,unit:'tsp'},
  {name:'Red wine vinegar',amount:1,unit:'tbsp'},
  {name:'Aleppo pepper',amount:0.5,unit:'tsp'},
  {name:'Fresh mint',amount:1,unit:'handful'},
],
steps:[
  'Roast or boil the beetroot until tender, then peel and slice.',
  'Whip the ricotta with a bit of lemon juice and zest until smooth and fluffy.',
  'Make a dressing with olive oil, chopped pistachios, honey, dijon mustard, red wine vinegar, and Aleppo pepper.',
  'Arrange the beetroot on a plate, dollop with whipped ricotta, and drizzle with the pistachio dressing.',
  'Sprinkle fresh mint leaves over the top before serving.',
]},

// ── SEAFOOD ──────────────────────────────────────────────
{id:130,name:'Prawn Carpaccio with Prawn Head Oil Dressing',category:'Seafood',difficulty:'medium',serves:4,time:'30 min',calories:160,mainIngredient:'Prawns',
ingredients:[
  {name:'Fresh prawns',amount:500,unit:'g'},
  {name:'Olive oil',amount:4,unit:'tbsp'},
  {name:'Salt',amount:1,unit:'to taste'},
],
steps:[
  'Prepare the prawns by carefully removing the heads and shells.',
  'Reserve the prawn heads for making the oil dressing.',
  'Lay the prawn meat flat and slice thinly to create the carpaccio.',
  'Heat olive oil in a pan and gently cook the prawn heads to infuse the oil with flavour.',
  'Strain the oil to remove the prawn heads, creating the prawn head oil dressing.',
  'Arrange the prawn carpaccio on a plate and drizzle with the prawn head oil.',
  'Sprinkle with a pinch of salt and serve immediately.',
]},

{id:131,name:'Dover Sole with Fennel, Orange and Chilli Butter',category:'Seafood',difficulty:'medium',serves:2,time:'35 min',calories:520,mainIngredient:'Dover Sole',
ingredients:[
  {name:'Fennel bulb',prep:'finely sliced',amount:1,unit:'whole'},
  {name:'Lemon juice',amount:0.5,unit:'whole'},
  {name:'Chives',prep:'finely chopped',amount:1,unit:'tbsp'},
  {name:'Dill',amount:1,unit:'handful'},
  {name:'Olive oil',amount:4,unit:'tbsp'},
  {name:'Dover sole',amount:1,unit:'whole'},
  {name:'Flour',amount:3,unit:'tbsp'},
  {name:'Butter',amount:70,unit:'g'},
  {name:'Orange, zest and juice',amount:1,unit:'whole'},
  {name:'Fennel seeds',amount:1,unit:'tbsp'},
  {name:'Red chilli',prep:'finely chopped',amount:1,unit:'whole'},
  {name:'Capers',amount:2,unit:'tbsp'},
],
steps:[
  'Thinly shave the fennel bulb, then toss with the herbs, lemon juice, olive oil, salt, and fennel fronds. Set aside.',
  'Pat the Dover sole dry and season well with salt and pepper. Coat in flour and tap off the excess.',
  'Heat a large frying pan over medium-high heat with olive oil and 50g butter. Cook the Dover sole for 3–4 minutes on the first side until golden.',
  'Flip the fish and baste continuously with the butter for another 3 minutes until just cooked through. Remove the fish to a plate and rest.',
  'Lower the heat. Add fennel seeds and chilli to the pan and cook for 30 seconds, then add capers, orange zest, orange juice, and remaining butter.',
  'Let the sauce bubble for 1–2 minutes until glossy and reduced. Stir through chives and spoon over the Dover sole.',
  'Serve with the shaved fennel salad alongside.',
]},

// ── MEAT & POULTRY ───────────────────────────────────────
{id:132,name:'Ginger & Spring Onion Poached Chicken',category:'Meat & Poultry',difficulty:'easy',serves:4,time:'45 min',calories:340,mainIngredient:'Chicken',
ingredients:[
  {name:'Chicken drumsticks',amount:6,unit:'whole'},
  {name:'Ginger',prep:'thick slices',amount:3,unit:'slices'},
  {name:'Spring onions',amount:4,unit:'whole'},
  {name:'Rice bran or vegetable oil',amount:3,unit:'tbsp'},
  {name:'Ginger',prep:'finely chopped',amount:15,unit:'g'},
  {name:'Sugar',amount:1,unit:'tsp'},
  {name:'Sesame oil',amount:1,unit:'tsp'},
  {name:'Poaching liquid',amount:80,unit:'ml'},
  {name:'Light soy sauce',amount:3,unit:'tbsp'},
],
steps:[
  'Bring about 2L of water to a boil and add the ginger slices and spring onion.',
  'Add the chicken and bring back to a boil, then lower the heat, cover, and gently simmer for 10 minutes.',
  'Turn off the heat and leave the chicken in the pot, covered, for about 20 minutes to finish cooking gently. Remove, shred, and plate up.',
  'Heat the oil in a pan and fry the spring onion and ginger until fragrant and just starting to turn golden.',
  'Add the sugar, sesame oil, poaching liquid, and light soy sauce, letting it simmer for another minute.',
  'Taste and adjust seasoning, then spoon over the chicken and serve with rice.',
]},

{id:133,name:'One-Pan Sausage and Feta Shakshuka',category:'Meat & Poultry',difficulty:'easy',serves:4,time:'35 min',calories:580,mainIngredient:'Sausages',
ingredients:[
  {name:'Olive oil',amount:2,unit:'tbsp'},
  {name:'Brown onion',prep:'diced',amount:1,unit:'whole'},
  {name:'Garlic cloves',prep:'roughly chopped',amount:2,unit:'cloves'},
  {name:'Baby red peppers',prep:'halved',amount:10,unit:'whole'},
  {name:'Ground cumin',amount:2,unit:'tsp'},
  {name:'Ground coriander',amount:2,unit:'tsp'},
  {name:'Smoky paprika',amount:2,unit:'tsp'},
  {name:'Beef sausages',prep:'halved',amount:500,unit:'g'},
  {name:'Tinned chopped tomatoes',amount:400,unit:'g'},
  {name:'Tinned cherry tomatoes',amount:400,unit:'g'},
  {name:'Tinned chickpeas',amount:400,unit:'g'},
  {name:'Free-range eggs',amount:5,unit:'whole'},
  {name:'Persian feta',amount:180,unit:'g'},
  {name:'Za\'atar',amount:3,unit:'tbsp'},
  {name:'Pita bread',amount:4,unit:'whole'},
  {name:'Parsley',prep:'roughly chopped',amount:1,unit:'handful'},
],
steps:[
  'Place a large frying pan over medium-high heat. Add the olive oil, onion, garlic, and pepper with a good pinch of salt. Cook, stirring often, until slightly softened.',
  'Add the sausages and spices and cook, stirring often, for a further 2 minutes.',
  'Add the chopped tomatoes, cherry tomatoes, and chickpeas. Simmer for 10 minutes to cook the sausages.',
  'Crack in the eggs, cover the pan, and simmer over low heat for 10 minutes, until the eggs are just cooked.',
  'Warm the pita in a dry, hot pan and sprinkle over half the za\'atar.',
  'Serve the shakshuka with the feta crumbled over, the remaining za\'atar, and parsley scattered on top.',
]},

{id:134,name:'Blackened Chicken with Spiced Honey Butter and Wedge Salad',category:'Meat & Poultry',difficulty:'medium',serves:4,time:'60 min',calories:620,mainIngredient:'Chicken',
ingredients:[
  {name:'Spatchcock chicken',amount:1,unit:'whole'},
  {name:'Banana shallots',amount:6,unit:'whole'},
  {name:'Butter',amount:2,unit:'tbsp'},
  {name:'Garlic cloves',prep:'sliced',amount:4,unit:'cloves'},
  {name:'Red wine vinegar',amount:3,unit:'tbsp'},
  {name:'Honey',amount:2,unit:'tbsp'},
  {name:'Olive oil',amount:2,unit:'tbsp'},
  {name:'Black pepper',amount:2,unit:'tbsp'},
  {name:'Cumin',amount:1,unit:'tbsp'},
  {name:'Coriander',amount:1,unit:'tbsp'},
  {name:'Chilli powder',amount:1,unit:'tbsp'},
  {name:'Paprika',amount:1,unit:'tbsp'},
  {name:'Salt',amount:1,unit:'tbsp'},
  {name:'Gem lettuces',amount:4,unit:'whole'},
  {name:'Fresh dill',amount:1,unit:'bunch'},
  {name:'Fresh parsley',amount:1,unit:'bunch'},
  {name:'Lemon juice',amount:1,unit:'whole'},
  {name:'Greek yoghurt',amount:6,unit:'tbsp'},
  {name:'Tahini',amount:2,unit:'tbsp'},
  {name:'Extra virgin olive oil',amount:100,unit:'ml'},
  {name:'Spring onion',prep:'sliced',amount:1,unit:'whole'},
],
steps:[
  'Make the spice mix and marinate the chicken, reserving 1 tablespoon for the pan sauce later.',
  'Heat an ovenproof pan over medium heat. Add olive oil and place the chicken skin-side down for about 7 minutes until well coloured. Turn and cook for a further 3 minutes.',
  'Remove the chicken from the pan and add the shallots cut-side down. Sit the chicken back on top and roast for 30 minutes at 200°C, or until cooked through.',
  'For the dressing, blitz parsley, dill, olive oil, tahini, garlic, lemon juice and 2 tbsp water until smooth and bright green. Fold into the yoghurt and season.',
  'Give the lettuce wedges an ice bath and drain until dry. Drizzle with the green yoghurt dressing and garnish with spring onion, sesame seeds and chilli flakes.',
  'While the chicken rests, add butter, sliced garlic and reserved spice mix to the pan. Cook 2 minutes, scraping up the base. Remove from heat and stir in honey and red wine vinegar.',
  'Serve the warm sauce over the blackened chicken and sticky shallots alongside the wedge salad.',
]},

{id:135,name:'Tasty Chicken',category:'Meat & Poultry',difficulty:'easy',serves:4,time:'40 min',calories:310,mainIngredient:'Chicken',
ingredients:[
  {name:'Chicken thighs',amount:4,unit:'whole'},
  {name:'Turmeric',amount:1,unit:'tsp'},
  {name:'Garlic cloves',prep:'crushed',amount:2,unit:'cloves'},
  {name:'Paprika',amount:1,unit:'tsp'},
  {name:'Cumin',amount:1,unit:'tsp'},
  {name:'Ground black pepper',amount:0.5,unit:'tsp'},
  {name:'Salt',amount:1,unit:'tsp'},
  {name:'Fish sauce',amount:1,unit:'tbsp'},
  {name:'Dijon mustard',amount:0.5,unit:'tbsp'},
  {name:'Honey',amount:1,unit:'tsp'},
  {name:'Olive oil',amount:1,unit:'tbsp'},
  {name:'Lemon juice',amount:2,unit:'tsp'},
],
steps:[
  'Combine all ingredients except the chicken and half the lemon juice. Add the chicken and coat thoroughly.',
  'Place the chicken and marinade into a small baking dish and cook for 15 minutes at 200°C.',
  'Turn the chicken over and cook for a further 15 minutes.',
  'Remove from oven, place the chicken and all cooking juices in a bowl, and let cool for 20 minutes.',
  'Shred or chop the chicken and mix with the remaining 1 tsp lemon juice. Adjust seasoning with extra salt if needed.',
]},

// ── VEGETARIAN ───────────────────────────────────────────
{id:136,name:'Miso Garlic Butter Cabbage with Braised Butter Beans',category:'Vegetarian',difficulty:'medium',serves:4,time:'50 min',calories:360,mainIngredient:'Cabbage',
ingredients:[
  {name:'Pointed cabbage',amount:1,unit:'whole'},
  {name:'Neutral oil',amount:2,unit:'tbsp'},
  {name:'Salted butter',amount:50,unit:'g'},
  {name:'White miso paste',amount:1,unit:'tsp'},
  {name:'Garlic cloves',prep:'minced',amount:4,unit:'cloves'},
  {name:'Smoked paprika',amount:1,unit:'tsp'},
  {name:'Shallot',prep:'finely diced',amount:1,unit:'whole'},
  {name:'Fresh parsley',prep:'finely chopped',amount:1,unit:'bunch'},
  {name:'Cider vinegar',amount:1,unit:'tbsp'},
  {name:'Butter beans',amount:570,unit:'g'},
  {name:'Nutritional yeast',amount:1,unit:'tbsp'},
  {name:'Lemon',prep:'zested',amount:0.5,unit:'whole'},
  {name:'Chilli crisp',amount:1,unit:'to serve'},
],
steps:[
  'Preheat your oven and prepare a frypan.',
  'Halve the pointed cabbage and drizzle with neutral oil. Season with salt and pepper.',
  'Mix the salted butter, white miso paste, minced garlic, and smoked paprika to make the miso-garlic butter.',
  'Sear the cabbage in the frypan until golden on the cut sides, then transfer to the oven.',
  'Roast the cabbage, basting occasionally with the miso-garlic butter, until tender and caramelised.',
  'Meanwhile, sauté the diced shallot and minced garlic in a little oil until soft.',
  'Add the chopped parsley, cider vinegar, drained butter beans, nutritional yeast, and lemon zest. Stir gently and heat through until creamy.',
  'Serve the roasted cabbage on top of the braised butter beans.',
  'Garnish with finely diced chives, toasted sesame seeds, and a spoon of chilli crisp before serving.',
]},

// ── PASTA & RICE ─────────────────────────────────────────
{id:137,name:'Mussel and \'Nduja Pasta',category:'Pasta & Rice',difficulty:'medium',serves:4,time:'35 min',calories:520,mainIngredient:'Mussels',
ingredients:[
  {name:'Fresh mussels',amount:1,unit:'kg'},
  {name:'\'Nduja sausage',amount:100,unit:'g'},
  {name:'Pasta of choice',amount:400,unit:'g'},
  {name:'Olive oil',amount:2,unit:'tbsp'},
  {name:'Garlic cloves',prep:'chopped',amount:3,unit:'cloves'},
  {name:'White wine',amount:100,unit:'ml'},
  {name:'Cherry tomatoes',amount:200,unit:'g'},
  {name:'Fresh parsley',amount:1,unit:'handful'},
  {name:'Salt and pepper',amount:1,unit:'to taste'},
],
steps:[
  'Clean and debeard the mussels thoroughly, discarding any that are open and do not close when tapped.',
  'Heat olive oil in a large pan over medium heat and sauté chopped garlic until fragrant.',
  'Add the \'nduja sausage, breaking it up with a spoon, and cook until it releases its oils.',
  'Pour in a splash of white wine and allow it to reduce slightly.',
  'Add the cherry tomatoes and cook until they begin to soften.',
  'Toss in the cleaned mussels, cover the pan, and cook for 3–4 minutes until all the mussels open.',
  'Meanwhile, cook the pasta in salted water until al dente, then drain.',
  'Add the cooked pasta to the pan with the mussels and toss to coat in the sauce.',
  'Finish with freshly chopped parsley, season with salt and pepper, and serve immediately.',
]},

// ── SIDES ─────────────────────────────────────────────────
{id:138,name:'Carrot Tarte Tatin',category:'Sides',difficulty:'medium',serves:6,time:'90 min',calories:320,mainIngredient:'Carrots',
ingredients:[
  {name:'Carrots',amount:6,unit:'whole'},
  {name:'Honey',amount:2,unit:'tbsp'},
  {name:'Apple cider vinegar',amount:1.5,unit:'tsp'},
  {name:'Orange juice',amount:1.5,unit:'tsp'},
  {name:'Cold butter',amount:2,unit:'tbsp'},
  {name:'Orange zest',amount:1,unit:'to taste'},
  {name:'Fresh thyme',amount:1,unit:'sprig'},
  {name:'Puff pastry sheet',amount:1,unit:'sheet'},
  {name:'Crumbled feta cheese',amount:60,unit:'g'},
  {name:'Olive oil',amount:1,unit:'tbsp'},
  {name:'Flaky sea salt',amount:1,unit:'to taste'},
],
steps:[
  'Preheat the oven to 150°C (300°F) convection.',
  'Peel and cut the carrots lengthways, place them in the oven and roast until tender but still with a slight bite in the centre.',
  'Once the carrots are cooked, increase the oven temperature to 175°C (350°F).',
  'In a 20cm pan, combine the honey, apple cider vinegar, and orange juice. Cook over medium-high heat without stirring until it reduces and thickens into a syrup.',
  'Lower the heat to medium-low and add cold butter, stirring until it melts and forms a smooth caramel. If it splits, add 1 tsp cold water and whisk until it comes back together.',
  'Stir in orange zest and fresh thyme, then arrange the roasted carrots in the pan.',
  'Cover the carrots with puff pastry, tucking the edges around the filling. Prick a few holes to let steam escape, then bake at 175°C until the pastry is puffed and golden brown.',
  'Remove from the oven and let rest for about 30 minutes.',
  'Flip the tart onto a plate to serve. If it sticks, warm the pan briefly over low heat.',
  'Finish with crumbled feta, fresh thyme, a drizzle of olive oil, and a sprinkle of flaky sea salt.',
]},

{id:139,name:'Potato Galette',category:'Sides',difficulty:'medium',serves:4,time:'60 min',calories:380,mainIngredient:'Potato',
ingredients:[
  {name:'Sebago potatoes',prep:'peeled and thinly sliced',amount:2,unit:'whole'},
  {name:'Salt and pepper',amount:1,unit:'to taste'},
  {name:'Clarified butter, melted',amount:500,unit:'g'},
],
steps:[
  'Preheat the oven to 160°C.',
  'Line a small ovenproof frying pan or skillet with baking paper.',
  'Using a mandolin set to 3mm, slice the potatoes on the short end.',
  'Place the slices into a medium mixing bowl, drizzle with clarified butter until well coated, and season with salt.',
  'Arrange the slices on the baking paper in overlapping circles.',
  'Pour a little more clarified butter over the top and cover with baking paper.',
  'Bake for about 40 minutes until golden brown, crispy, and the potatoes are cooked through.',
  'Remove the galette from the baking tray and season with salt to serve.',
]},

// ── SAUCES ────────────────────────────────────────────────
{id:140,name:'Copy Cat Lori-Jayne AP Sauce',category:'Sauces',difficulty:'hard',serves:8,time:'75 min',calories:180,mainIngredient:'Cream',
ingredients:[
  {name:'Butter',amount:4,unit:'tbsp'},
  {name:'Shallots',amount:6,unit:'whole'},
  {name:'Garlic cloves',amount:6,unit:'cloves'},
  {name:'Cognac',amount:30,unit:'ml'},
  {name:'White wine',amount:250,unit:'ml'},
  {name:'Soy sauce',amount:24,unit:'g'},
  {name:'Black vinegar',amount:10,unit:'g'},
  {name:'Kecap manis',amount:30,unit:'g'},
  {name:'Sherry vinegar',amount:15,unit:'g'},
  {name:'Fish sauce',amount:7,unit:'g'},
  {name:'Lemon juice',amount:12,unit:'g'},
  {name:'Chicken stock',amount:500,unit:'ml'},
  {name:'Heavy cream',amount:250,unit:'ml'},
  {name:'Fresh thyme',amount:2,unit:'sprigs'},
  {name:'Red Sichuan peppercorns',amount:2,unit:'tbsp'},
  {name:'Green Sichuan peppercorns',amount:2,unit:'tbsp'},
  {name:'Black peppercorns',amount:2,unit:'tbsp'},
],
steps:[
  'Add shallots and butter to a cold pan.',
  'Cook shallots over low heat for 30–35 minutes until deeply softened.',
  'Add minced garlic, turn heat back up to medium and cook until fragrant.',
  'Add 1 shot of cognac and let it cook off.',
  'Add the white wine and let all alcohol cook off completely.',
  'Add soy sauce, black vinegar, kecap manis, sherry vinegar, fish sauce, and lemon juice.',
  'Add chicken stock and cook down for about 20 minutes to reduce by roughly half.',
  'Add heavy cream and thyme. Bring to a boil, then cut the heat.',
  'Strain the sauce through a fine sieve.',
  'Gently toast the peppercorns until fragrant, then blend and stir into the sauce to taste.',
  'Serve warm.',
]},

// ── DESSERTS ──────────────────────────────────────────────
{id:141,name:'Strawberry & Champagne Jelly with White Chocolate Panna Cotta',category:'Desserts',difficulty:'hard',serves:4,time:'4 hr 30 min',calories:480,mainIngredient:'Cream',
ingredients:[
  {name:'Thickened cream',amount:300,unit:'g'},
  {name:'Caster sugar',amount:55,unit:'g'},
  {name:'Vanilla paste',amount:0.5,unit:'tbsp'},
  {name:'White chocolate',amount:140,unit:'g'},
  {name:'Gold-strength gelatine leaves',amount:3,unit:'whole'},
  {name:'Greek yoghurt',amount:125,unit:'g'},
  {name:'Strawberry juice',amount:100,unit:'ml'},
  {name:'Champagne or sparkling wine',amount:100,unit:'ml'},
],
steps:[
  'Place the cream, 40g sugar, and vanilla in a small saucepan and stir over medium heat until just beginning to simmer. Remove from the heat.',
  'Add the white chocolate and whisk until completely melted and smooth.',
  'Soak 1 gelatine leaf in cold water until softened. Squeeze out excess water, then stir into the warm cream mixture until fully dissolved.',
  'Transfer to a bowl and allow to cool to room temperature. Add the Greek yoghurt and whisk until smooth.',
  'Divide evenly between four serving glasses. Refrigerate for at least 2 hours, or until set.',
  'Combine the strawberry juice, Champagne, and remaining 15g sugar in a small saucepan. Warm gently over low heat, stirring until the sugar dissolves. Do not boil.',
  'Soak 2 gelatine leaves in cold water until softened. Squeeze out excess water, then stir gently into the warm strawberry mixture until dissolved.',
  'Allow the jelly mixture to cool to room temperature. Once the panna cotta has set, carefully pour the jelly over the top of each glass.',
  'Refrigerate for a further 2 hours, or until the jelly is set.',
  'Serve chilled. Best enjoyed on the day it is made.',
]},


// ── SIDES ──────────────────────────────────────────────
{id:142,name:'Easy Greek-Style Lemon Potatoes',category:'Sides',difficulty:'easy',serves:4,time:'55 min',calories:280,mainIngredient:'Potatoes',
ingredients:[
  {name:'Potatoes',amount:800,unit:'g'},
  {name:'Olive oil',amount:60,unit:'ml'},
  {name:'Fresh lemon juice',amount:60,unit:'ml'},
  {name:'Garlic',amount:3,unit:'cloves'},
  {name:'Salt',amount:1,unit:'to taste'},
  {name:'Pepper',amount:1,unit:'to taste'},
  {name:'Water or vegetable broth',amount:120,unit:'ml'},
],
steps:[
  'Preheat the oven to 200°C.',
  'Peel and cut the potatoes into wedges.',
  'Arrange the potato wedges in a single layer in a large baking dish or pan.',
  'In a bowl, whisk together olive oil, lemon juice, minced garlic, salt, pepper, and water or vegetable broth.',
  'Pour the mixture over the potatoes, ensuring they are evenly coated.',
  'Roast in the oven until the edges are crispy and the insides are tender, basting occasionally with the pan juices.',
  'Serve hot.',
]},

{id:143,name:'Spicy Crab Toast',category:'Dips & Starters',difficulty:'easy',serves:4,time:'25 min',calories:240,mainIngredient:'Crab',
ingredients:[
  {name:'Snow crab meat',amount:300,unit:'g'},
  {name:'Jalapeno',amount:1,unit:'whole'},
  {name:'Spring onion',amount:2,unit:'whole'},
  {name:'Pepperoncini',amount:2,unit:'whole'},
  {name:'Capers',amount:1,unit:'tbsp'},
  {name:'Mixed fresh herbs',amount:1,unit:'handful'},
  {name:'Bread',prep:'sliced',amount:4,unit:'whole'},
],
steps:[
  'Prepare the snow crab by cleaning and shredding the meat.',
  'Finely chop the jalapeno, spring onion, and pepperoncini.',
  'Mix the crab meat with the chopped vegetables, capers, and a generous amount of fresh herbs.',
  'Toast slices of bread to your liking.',
  'Spoon the crab mixture onto the toast.',
  'Serve as a classy little snack for your friends.',
]},
{id:144,name:'Dill Caesar Salad',category:'Salads',difficulty:'easy',serves:4,time:'25 min',calories:260,mainIngredient:'Lettuce',
ingredients:[
  {name:'Baby gem lettuce',amount:3,unit:'whole'},
  {name:'Creamy dill Caesar dressing',amount:120,unit:'ml'},
  {name:'Anchovy breadcrumbs',amount:80,unit:'g'},
],
steps:[
  'Prepare the creamy dill Caesar dressing.',
  'Wash and dry the baby gem lettuce, keeping the leaves whole.',
  'Make the anchovy breadcrumbs and toast them until crispy.',
  'Arrange the baby gem lettuce on a plate.',
  'Drizzle generously with the creamy dill Caesar dressing.',
  'Sprinkle the spicy anchovy breadcrumbs over the top.',
  'Serve immediately.',
]},
{id:145,name:'Cioppino (Fisherman\'s Stew)',category:'Soups',difficulty:'medium',serves:6,time:'1 hr',calories:420,mainIngredient:'Seafood',
ingredients:[
  {name:'Mussels',amount:1,unit:'kg'},
  {name:'Olive oil',amount:80,unit:'ml'},
  {name:'Fennel bulbs',prep:'finely sliced',amount:2,unit:'whole'},
  {name:'Fennel seeds',amount:1,unit:'tbsp'},
  {name:'Brown onions',prep:'finely sliced',amount:2,unit:'whole'},
  {name:'Celery stalks',prep:'finely sliced',amount:2,unit:'whole'},
  {name:'Chilli flakes',amount:1,unit:'pinch'},
  {name:'Bay leaves',amount:2,unit:'whole'},
  {name:'Garlic',prep:'crushed',amount:4,unit:'clove'},
  {name:'Chopped tomatoes',amount:800,unit:'g'},
  {name:'Fish stock',amount:1,unit:'L'},
  {name:'Chicken stock',amount:1,unit:'L'},
  {name:'Snapper',prep:'cut into chunks',amount:600,unit:'g'},
  {name:'Raw prawn cutlets',amount:300,unit:'g'},
  {name:'Edenvale Alcohol Removed Pinot Gris',amount:250,unit:'ml'},
  {name:'Flat leaf parsley, chopped',amount:1,unit:'handful'},
  {name:'Crusty bread',amount:1,unit:'whole'},
],
steps:[
  'Begin by scrubbing and debearding your mussels. Set aside.',
  'Heat a large saucepan over medium heat and add olive oil. Once warm, add fennel, fennel seeds, onion, celery, bay leaves and chilli flakes. Cook, stirring occasionally, for 5-8 minutes or until softened.',
  'Add garlic and the Pinot Gris and cook for a further two minutes.',
  'Add tomatoes, stir through, then add both types of stock. Simmer for 20-30 minutes until slightly reduced.',
  'Ladle two cups of the stock into a saute pan with a lid and bring to the boil. Add the mussels and cook for 4 minutes or until opened.',
  'Meanwhile, add the fish and prawns to the large pot to cook for 5 minutes.',
  'Return mussels and their stock to the pan and stir to combine.',
  'Ladle into bowls and garnish with parsley and reserved fennel fronds. Serve with crusty bread and enjoy.',
]},
{id:146,name:'Cantonese Steamed Fish in Under 20 Minutes',category:'Seafood',difficulty:'easy',serves:2,time:'20 min',calories:320,mainIngredient:'Fish',
ingredients:[
  {name:'Whole fresh white fish',prep:'cleaned and scaled',amount:600,unit:'g'},
  {name:'Spring onion',prep:'sliced into 5 cm lengths',amount:2,unit:'whole'},
  {name:'Fresh ginger',prep:'sliced',amount:3,unit:'slice'},
  {name:'Light soy sauce',amount:2,unit:'tbsp'},
  {name:'Shaoxing wine',amount:1,unit:'tbsp'},
  {name:'Sesame oil',amount:1,unit:'tsp'},
  {name:'Vegetable oil',amount:2,unit:'tbsp'},
  {name:'Fresh coriander leaves',amount:1,unit:'handful'},
],
steps:[
  'Clean and pat dry the fish thoroughly. Score each side of the fish with 2-3 diagonal cuts.',
  'Place the ginger slices and half the spring onions both inside the cavity and on top of the fish.',
  'Set up a steamer or a wok with a steaming rack and bring water to a boil.',
  'Place the fish on a heatproof plate and steam over high heat for 8-10 minutes, or until the fish is just cooked through and flakes easily.',
  'Carefully remove the plate from the steamer. Discard the ginger and spring onions used during steaming.',
  'In a small saucepan, heat the vegetable oil until hot.',
  'Scatter the remaining fresh spring onions over the steamed fish.',
  'Pour the hot oil over the fish to sizzle the aromatics.',
  'Drizzle with soy sauce, Shaoxing wine, and sesame oil. Garnish with coriander if desired. Serve immediately.',
]},
{id:147,name:'Thai Basil and Oyster Sauce Pipis',category:'Seafood',difficulty:'easy',serves:4,time:'15 min',calories:230,mainIngredient:'Pipis',
ingredients:[
  {name:'Vegetable oil',amount:1,unit:'tsp'},
  {name:'Garlic cloves',prep:'crushed',amount:3,unit:'clove'},
  {name:'Pipis',amount:1.5,unit:'kg'},
  {name:'Long red chillies',prep:'sliced',amount:2,unit:'whole'},
  {name:'Thai basil leaves',amount:60,unit:'g'},
  {name:'Oyster sauce',amount:3,unit:'tsp'},
  {name:'Caster sugar',amount:1,unit:'tsp'},
],
steps:[
  'Heat a wok over high heat. Add the oil and garlic and cook for 30 seconds until fragrant.',
  'Throw in the pipis and toss quickly.',
  'Add the chilli, Thai basil, oyster sauce and sugar, reserving a little chilli and basil for the end.',
  'Cover with a lid and let everything steam for 2-4 minutes or until the pipis open up.',
  'Remove the lid and toss everything through the sauce.',
  'Finish with the remaining chilli and basil and serve immediately.',
]},
{id:148,name:'Mongolian Beef',category:'Meat & Poultry',difficulty:'medium',serves:4,time:'45 min',calories:560,mainIngredient:'Beef',
ingredients:[
  {name:'Steak',prep:'thinly sliced',amount:720,unit:'g'},
  {name:'Soy sauce',amount:60,unit:'ml'},
  {name:'Cornflour',amount:100,unit:'g'},
  {name:'MSG',amount:1,unit:'pinch'},
  {name:'Bicarbonate of soda',amount:0.5,unit:'tsp'},
  {name:'Cracked white pepper',amount:1,unit:'to taste'},
  {name:'Brown onion',amount:1,unit:'whole'},
  {name:'Spring onions',amount:4,unit:'whole'},
  {name:'Garlic cloves',amount:4,unit:'clove'},
  {name:'Birdseye red chillies',amount:2,unit:'whole'},
  {name:'Fresh ginger, finely grated',amount:1,unit:'thumb'},
  {name:'Tallow or peanut oil for frying',amount:500,unit:'ml'},
  {name:'Water',amount:50,unit:'ml'},
  {name:'Steamed rice',amount:1,unit:'to serve'},
],
steps:[
  'Trim the beef of any excess fat or sinew and slice thinly into strips.',
  'Combine 30 ml of the soy sauce, 2 tablespoons of the cornflour, white pepper, MSG, and bicarb soda in a large bowl. Add the beef and mix well to combine. Cover and refrigerate for 1 to 3 hours to marinate.',
  'Thinly slice the onion. Thickly slice the spring onions, keeping the white and green parts separate. Finely dice the garlic, finely slice the red chilli, and finely grate the ginger. Set aside.',
  'Heat enough tallow or oil in a wok to shallow fry, to 180C. Test with a chopstick, if it bubbles, the oil is ready.',
  'Remove the beef from the fridge and add the remaining cornflour, tossing well to coat.',
  'Fry the beef in batches for 3-4 minutes, then drain on a wire rack over a tray.',
  'Carefully remove most of the oil from the wok. Return the wok to high heat.',
  'Add the onions and stir-fry for 2 minutes, tossing occasionally. Add the spring onion whites, garlic, chilli, and ginger. Toss well and cook for a further minute.',
  'Return the beef to the wok and toss to combine. Add the remaining soy sauce and the water. Bring to a boil and cook for 2 more minutes.',
  'Stir in the spring onion greens. Serve over steamed rice and enjoy.',
]},
{id:149,name:'San Choy Bow',category:'Meat & Poultry',difficulty:'easy',serves:4,time:'30 min',calories:380,mainIngredient:'Beef',
ingredients:[
  {name:'Beef mince',amount:720,unit:'g'},
  {name:'Peanut oil',amount:1,unit:'tbsp'},
  {name:'Garlic cloves',prep:'minced',amount:2,unit:'clove'},
  {name:'Ginger',prep:'finely grated',amount:1,unit:'tbsp'},
  {name:'Small onion',prep:'finely chopped',amount:1,unit:'whole'},
  {name:'Shiitake mushrooms',prep:'diced',amount:100,unit:'g'},
  {name:'Canned water chestnuts, drained and chopped',amount:225,unit:'g'},
  {name:'Soy sauce',amount:2,unit:'tbsp'},
  {name:'Oyster sauce',amount:1,unit:'tbsp'},
  {name:'Hoisin sauce',amount:1,unit:'tbsp'},
  {name:'Rice wine vinegar',amount:1,unit:'tbsp'},
  {name:'Sesame oil',amount:1,unit:'tsp'},
  {name:'Iceberg lettuce leaves, washed and dried',amount:8,unit:'whole'},
  {name:'Spring onions',prep:'sliced thinly',amount:2,unit:'whole'},
  {name:'Fresh coriander leaves',amount:1,unit:'handful'},
],
steps:[
  'Heat the peanut oil in a wok or large frying pan over medium-high heat.',
  'Add the garlic, ginger, and onion. Stir-fry for 1-2 minutes until fragrant and softened.',
  'Add the beef mince and cook, breaking it up with a spatula, until browned.',
  'Stir in the mushrooms and water chestnuts, and cook for another 2-3 minutes.',
  'Add the soy sauce, oyster sauce, hoisin sauce, rice wine vinegar, and sesame oil. Mix well and cook for 2-3 minutes until the sauce thickens and coats the beef mixture.',
  'Spoon the beef mixture into the lettuce leaves.',
  'Garnish with sliced spring onions and coriander. Serve immediately and enjoy.',
]},
{id:150,name:'Chicken with Butter Ponzu',category:'Meat & Poultry',difficulty:'easy',serves:2,time:'25 min',calories:410,mainIngredient:'Chicken',
ingredients:[
  {name:'Chicken thigh',amount:300,unit:'g'},
  {name:'Shimeji mushrooms',amount:80,unit:'g'},
  {name:'Oil',amount:1,unit:'tsp'},
  {name:'Salt',amount:1,unit:'pinch'},
  {name:'Sake',amount:1,unit:'tbsp'},
  {name:'Potato starch',amount:1,unit:'tbsp'},
  {name:'Ponzu',amount:2,unit:'tbsp'},
  {name:'Sugar',amount:1,unit:'tsp'},
  {name:'Soy sauce',amount:1,unit:'tsp'},
  {name:'Butter',amount:5,unit:'g'},
  {name:'Black pepper',amount:1,unit:'to taste'},
  {name:'Chopped green onions',amount:1,unit:'to taste'},
],
steps:[
  'Cut the chicken thigh into bite-sized pieces. Rub in the marinade ingredients.',
  'Trim off the base of the shimeji mushrooms and separate them.',
  'Heat the oil in a pan and cook the chicken skin-side down.',
  'Once browned, flip the chicken and add the shimeji mushrooms.',
  'When everything is cooked through, add the sauce ingredients.',
  'Simmer lightly, then add your favourite toppings.',
]},
{id:151,name:'Grilled Chicken with Hummus and Chilli Oil',category:'Meat & Poultry',difficulty:'easy',serves:4,time:'30 min',calories:480,mainIngredient:'Chicken',
ingredients:[
  {name:'Chicken',amount:1,unit:'kg'},
  {name:'Garlic cloves',amount:4,unit:'clove'},
  {name:'Chilli oil',amount:2,unit:'tbsp'},
  {name:'Salt',amount:1,unit:'to taste'},
  {name:'Pepper',amount:1,unit:'to taste'},
  {name:'Dried oregano',amount:1,unit:'tbsp'},
  {name:'Lemon zest',amount:1,unit:'whole'},
  {name:'Lemon juice',amount:1,unit:'tbsp'},
  {name:'Extra virgin olive oil',amount:2,unit:'tbsp'},
  {name:'Hummus',amount:200,unit:'g'},
  {name:'Coriander',amount:1,unit:'handful'},
],
steps:[
  'Marinate the chicken very well for a few hours or ideally overnight.',
  'Cook on the BBQ skin side down for 12-15 minutes, then turn and briefly grill the flesh side. Aim for an internal temperature of 74C to be safe.',
  'Spoon hummus onto your favourite plate and top with lashings of chilli oil and some finely chopped coriander.',
  'Serve with a salad of your choice or your favourite sides. This absolutely slaps and would be great in a wrap too.',
]},
{id:152,name:'Pad Thai with Shrimps and Tofu',category:'Pasta & Rice',difficulty:'medium',serves:2,time:'35 min',calories:520,mainIngredient:'Noodles',
ingredients:[
  {name:'Dried rice noodles',amount:180,unit:'g'},
  {name:'Raw shrimp',prep:'peeled',amount:150,unit:'g'},
  {name:'Firm tofu, cubed',amount:150,unit:'g'},
  {name:'Eggs',amount:2,unit:'whole'},
  {name:'Garlic cloves',prep:'finely chopped',amount:2,unit:'clove'},
  {name:'Shallot',prep:'finely sliced',amount:1,unit:'whole'},
  {name:'Spring onions',prep:'sliced',amount:2,unit:'whole'},
  {name:'Bean sprouts',amount:1,unit:'handful'},
  {name:'Neutral oil for cooking',amount:2,unit:'tbsp'},
  {name:'Tamarind paste',amount:2,unit:'tbsp'},
  {name:'Fish sauce',amount:1.5,unit:'tbsp'},
  {name:'Palm sugar',amount:1,unit:'tbsp'},
  {name:'Oyster sauce',amount:1,unit:'tsp'},
  {name:'Crushed roasted peanuts',amount:2,unit:'tbsp'},
  {name:'Lime wedges',amount:2,unit:'whole'},
  {name:'Sliced bird chilli',amount:1,unit:'whole'},
],
steps:[
  'Prepare the rice noodles according to the package instructions until just tender. Drain and set aside.',
  'Mix together the pad Thai sauce: tamarind paste, fish sauce, palm sugar, and optional oyster sauce.',
  'Heat neutral oil in a wok or large pan over medium-high heat. Add garlic and shallot, and stir-fry until fragrant.',
  'Add tofu cubes and cook until lightly golden. Push to one side of the pan.',
  'Add the shrimp, cooking until pink and just cooked through.',
  'Crack in the eggs and scramble lightly, mixing with the other ingredients.',
  'Add the noodles and the prepared sauce. Toss everything together to coat evenly.',
  'Stir in bean sprouts and spring onions, cooking briefly until just wilted.',
  'Serve hot, topped with crushed roasted peanuts, lime wedges, and sliced bird chilli.',
]},
{id:153,name:'Ossobucco & Risotto alla Milanese',category:'Pasta & Rice',difficulty:'hard',serves:4,time:'2 hr 30 min',calories:680,mainIngredient:'Veal',
ingredients:[
  {name:'Veal shanks',amount:4,unit:'whole'},
  {name:'Onion',amount:1,unit:'whole'},
  {name:'Carrot',amount:1,unit:'whole'},
  {name:'Celery',amount:2,unit:'stalk'},
  {name:'Garlic',amount:2,unit:'clove'},
  {name:'Tomato paste',amount:2,unit:'tbsp'},
  {name:'White wine',amount:250,unit:'ml'},
  {name:'Chicken stock',amount:1.5,unit:'L'},
  {name:'Butter',amount:80,unit:'g'},
  {name:'Olive oil',amount:2,unit:'tbsp'},
  {name:'Saffron',amount:1,unit:'pinch'},
  {name:'Arborio rice',amount:320,unit:'g'},
  {name:'Parmesan cheese',amount:80,unit:'g'},
  {name:'Salt',amount:1,unit:'to taste'},
  {name:'Pepper',amount:1,unit:'to taste'},
  {name:'Lemon zest',amount:1,unit:'whole'},
  {name:'Parsley',amount:1,unit:'handful'},
],
steps:[
  'Season the veal shanks with salt and pepper.',
  'Sear the shanks in a hot pan with olive oil until browned on all sides, then remove and set aside.',
  'In the same pan, saute chopped onion, carrot, celery, and garlic until softened.',
  'Stir in tomato paste and cook briefly, then deglaze the pan with white wine.',
  'Return the shanks to the pan, add chicken stock, and simmer gently until the meat is tender.',
  'Separately, prepare the risotto: heat butter in a pan and toast the Arborio rice.',
  'Gradually add warm chicken stock while stirring continuously until the rice is creamy and al dente.',
  'Stir in saffron threads, butter, and grated Parmesan cheese.',
  'Prepare gremolata by combining lemon zest and parsley.',
  'Serve the ossobucco over the risotto, topped with gremolata.',
]},
{id:154,name:'Asian Greens Cooking Instructions',category:'Sides',difficulty:'easy',serves:8,time:'20 min',calories:60,mainIngredient:'Greens',
ingredients:[
  {name:'Bok choy',amount:10,unit:'bunch'},
  {name:'Chinese broccoli',prep:'cut stalks',amount:10,unit:'bunch'},
  {name:'Choy sum',prep:'cut stalks',amount:10,unit:'bunch'},
],
steps:[
  'To blanch: bring the water to the boil then place the Asian green into the boiled water stalks first.',
  'Blanch them for 1 minute or until the Asian green stalks are soft.',
  'Submerge leaves for 20 seconds then immediately place them into cold water and store in the fridge.',
  'To cook: cook the Asian green on the low heat side of the grill, just until warm and the garlic is still a white colour (not brown or black). Do not overcook.',
]},
{id:155,name:'Spicy Honey Christmas Carrots',category:'Sides',difficulty:'easy',serves:6,time:'40 min',calories:150,mainIngredient:'Carrots',
ingredients:[
  {name:'Carrots',prep:'halved',amount:800,unit:'g'},
  {name:'Gochujang',amount:2,unit:'tbsp'},
  {name:'Honey',amount:2,unit:'tbsp'},
],
steps:[
  'Preheat the oven to a high temperature suitable for roasting.',
  'Cut the carrots in half to create more surface area for charring.',
  'Roast the carrots until their natural sugars caramelise and they develop a smoky, sweet char.',
  'Mix gochujang and honey into a luscious sauce.',
  'Toss the roasted carrots in the gochujang-honey mixture until evenly coated.',
  'Serve hot as a festive side dish.',
]},
{id:156,name:'Easy Greek-Style Lemon Potatoes',category:'Sides',difficulty:'easy',serves:6,time:'1 hr',calories:280,mainIngredient:'Potatoes',
ingredients:[
  {name:'Potatoes',amount:1,unit:'kg'},
  {name:'Olive oil',amount:80,unit:'ml'},
  {name:'Fresh lemon juice',amount:60,unit:'ml'},
  {name:'Garlic',prep:'minced',amount:3,unit:'clove'},
  {name:'Salt',amount:1,unit:'to taste'},
  {name:'Pepper',amount:1,unit:'to taste'},
  {name:'Water or vegetable broth',amount:250,unit:'ml'},
],
steps:[
  'Preheat the oven to 200C.',
  'Peel and cut the potatoes into wedges.',
  'Arrange the potato wedges in a single layer in a large baking dish or pan.',
  'In a bowl, whisk together olive oil, lemon juice, minced garlic, salt, pepper, and water or vegetable broth.',
  'Pour the mixture over the potatoes, ensuring they are evenly coated.',
  'Roast in the oven until the edges are crispy and the insides are tender, basting occasionally with the pan juices.',
  'Serve hot as a flavourful side dish.',
]},
{id:157,name:'Chilli Sauce with Roasted Shrimp Paste',category:'Sauces',difficulty:'medium',serves:8,time:'30 min',calories:60,mainIngredient:'Chilli',
ingredients:[
  {name:'Fresh long red chillis, seeds removed, coarsely chopped',amount:300,unit:'g'},
  {name:'Large garlic cloves, sliced',amount:4,unit:'clove'},
  {name:'Salt',amount:1,unit:'tsp'},
  {name:'Distilled white vinegar',amount:250,unit:'ml'},
  {name:'Palm sugar or castor sugar',amount:2,unit:'tbsp'},
  {name:'Belachan/shrimp paste',amount:20,unit:'g'},
],
steps:[
  'Place the chopped chillis, garlic, salt, and vinegar into a bowl, cover, and let sit overnight to mellow.',
  'Preheat the oven or air fryer to 180C.',
  'Place the piece of shrimp paste into a square of foil, scrunch together to enclose. Roast for 5 minutes until it releases aroma, becomes slightly brown around the edges, and crumbly. If shrimp paste makes you nervous, you can leave it out.',
  'Transfer the chilli and garlic mixture into a saucepan. Add the sugar and roasted shrimp paste.',
  'Bring to a simmer and cook for 5 minutes. Remove from heat and cool to room temperature.',
  'Blend in a food processor until super smooth, then pour into a sterilised bottle or jar.',
  'Seal with a lid and place in the fridge. The sauce will last up to 3 months, but it likely will be eaten long before that.',
  'Enjoy with BBQ chicken or by dipping a cheese toastie into a generous dollop of kewpie topped with the chilli sauce.',
]},
{id:158,name:'Quick Mayonnaise',category:'Sauces',difficulty:'easy',serves:8,time:'5 min',calories:180,mainIngredient:'Egg',
ingredients:[
  {name:'Egg yolks',amount:2,unit:'whole'},
  {name:'Dijon mustard',amount:1,unit:'tbsp'},
  {name:'Lemon, juice of',amount:1,unit:'whole'},
  {name:'Neutral flavoured oil',amount:450,unit:'ml'},
  {name:'Salt',amount:1,unit:'tsp'},
],
steps:[
  'Add everything to a tall jug, then put a stick blender to the bottom.',
  'Turn the stick blender on and after a few seconds start moving the stick blender to the top of the jug until a smooth sauce forms.',
  'If it is too thick, simply add a small amount of room temperature water and mix again until you reach the desired consistency.',
]},
{id:159,name:'Sambal',category:'Sauces',difficulty:'medium',serves:8,time:'45 min',calories:90,mainIngredient:'Ginger',
ingredients:[
  {name:'Ginger',prep:'chopped into thin pieces',amount:1,unit:'kg'},
  {name:'Fresh garlic',amount:150,unit:'g'},
  {name:'Vegetable oil',amount:450,unit:'ml'},
  {name:'White vinegar',amount:250,unit:'ml'},
  {name:'Salt',amount:5,unit:'tbsp'},
  {name:'Lemongrass, defrosted',amount:320,unit:'g'},
  {name:'Fish sauce',amount:125,unit:'ml'},
  {name:'Raw sugar',amount:425,unit:'g'},
  {name:'Coriander roots',prep:'chopped',amount:86,unit:'g'},
  {name:'Sambal oelek',amount:250,unit:'g'},
],
steps:[
  'Part A: slice 1 kilo of ginger using the robot coupe slicing blade. Add salt and garlic, 250 ml of vegetable oil and 250 ml of vinegar, and blend in the robot coupe. Gradually add approximately 140 ml of the remaining vegetable oil (add slowly to avoid splitting). The mixture should be smooth and creamy. Set aside in a large bowl.',
  'Part B: finely chop the coriander roots and place in the blending robot coupe with the remaining ingredients. Blend till smooth but not too much or it will go bright green. Mix it in the bowl with Part A.',
  'Part C: mix the sambal oelek in with the ginger mix.',
  'Cover with cling film and allow to rest for 24 hours in the cool room.',
  'Get the kitchen supervisor to check the sambal before usage. This recipe feeds a lot of people. One person serving would be 100 g of ginger and the portion from there.',
]},
{id:160,name:'Bok Choy Dressing',category:'Sauces',difficulty:'easy',serves:8,time:'5 min',calories:70,mainIngredient:'Soy sauce',
ingredients:[
  {name:'Light soy sauce',amount:500,unit:'ml'},
  {name:'Sweet soy ABC kecap manis',amount:250,unit:'ml'},
  {name:'Sesame oil',amount:250,unit:'ml'},
],
steps:[
  'Mix all ingredients together.',
]},
{id:161,name:'DIY Taramosalata',category:'Dips & Starters',difficulty:'easy',serves:6,time:'15 min',calories:220,mainIngredient:'Cod roe',
ingredients:[
  {name:'Cod roe',amount:100,unit:'g'},
  {name:'Olive oil',amount:200,unit:'ml'},
  {name:'Lemon juice',amount:2,unit:'tbsp'},
  {name:'Bread',amount:3,unit:'slice'},
],
steps:[
  'Prepare the cod roe by removing any membranes if necessary.',
  'Soak the bread in water, then squeeze out the excess liquid.',
  'Blend the cod roe with the soaked bread until smooth.',
  'Slowly drizzle in olive oil while blending to create a creamy emulsion.',
  'Add lemon juice to taste and adjust the seasoning if needed.',
  'Chill before serving with bread or vegetables.',
]},
{id:162,name:'Slow-Cooker Thai-Style Pumpkin Soup',category:'Soups',difficulty:'easy',serves:6,time:'6 hr',calories:280,mainIngredient:'Pumpkin',
ingredients:[
  {name:'Butternut pumpkin',amount:800,unit:'g'},
  {name:'Kent pumpkin',amount:800,unit:'g'},
  {name:'Carrot',amount:1,unit:'whole'},
  {name:'Brown onion',amount:1,unit:'whole'},
  {name:'Curry paste',amount:2,unit:'tbsp'},
  {name:'Vegetable stock',amount:500,unit:'ml'},
  {name:'Coconut milk',amount:400,unit:'ml'},
  {name:'Sugar',amount:1,unit:'tsp'},
  {name:'Lime juice',amount:1,unit:'tbsp'},
  {name:'Fish sauce',amount:1,unit:'tbsp'},
  {name:'Coconut cream',amount:60,unit:'ml'},
],
steps:[
  'Place the combined pumpkin, carrot, onion, curry paste, stock and coconut milk in a slow cooker.',
  'Cover and cook for 4 hours on high (or 6 hours on low) or until the pumpkin is tender and mixture thickens slightly.',
  'Set aside to cool slightly.',
  'Use a stick blender to carefully blend the pumpkin mixture until smooth.',
  'Stir in sugar, lime juice and fish sauce. Season.',
  'Ladle the soup evenly among serving bowls.',
  'Drizzle with coconut cream. Season.',
]},
{id:163,name:'New York Style Pepperoni & Hot Honey Pizza',category:'Bread & Bakes',difficulty:'medium',serves:4,time:'48 hr',calories:850,mainIngredient:'Pepperoni',
ingredients:[
  {name:'Bread flour',amount:700,unit:'g'},
  {name:'Wholemeal flour',amount:300,unit:'g'},
  {name:'Cooking salt',amount:25,unit:'g'},
  {name:'Olive oil',amount:30,unit:'ml'},
  {name:'Sugar',amount:20,unit:'g'},
  {name:'Dry yeast',amount:5,unit:'g'},
  {name:'Water',amount:570,unit:'ml'},
  {name:'Tinned tomatoes',amount:2,unit:'tin'},
  {name:'Salt',amount:10,unit:'g'},
  {name:'Sugar',amount:5,unit:'g'},
  {name:'Dried oregano',amount:2,unit:'g'},
  {name:'Low-moisture mozzarella',prep:'grated',amount:400,unit:'g'},
  {name:'Pepperoni',prep:'sliced',amount:400,unit:'g'},
  {name:'Hot honey',amount:1,unit:'to taste'},
  {name:'Fresh basil',amount:1,unit:'handful'},
  {name:'Parmesan cheese',amount:1,unit:'to taste'},
],
steps:[
  'In a large bowl, combine bread flour, wholemeal flour, 20g sugar, dry yeast, and 570ml water. Mix by hand, then add 30ml olive oil and 25g salt. Knead briefly to distribute.',
  'Knead on your workbench for 8-10 minutes until smooth. Cover and refrigerate for 48 hours.',
  'Three hours before baking, remove from the fridge, divide into 400g portions, roll into tight balls, place on a greased tray, and prove at room temperature for 2-3 hours.',
  'Preheat your oven to 400 degrees C at least an hour ahead to heat-soak. Note: NY-style pizzas bake at lower temps than Neapolitan — some shops go as low as 330 degrees C. Experiment to find what works best.',
  'Blend tinned tomatoes with 10g salt, 5g sugar, and dried oregano until smooth. Avoid over-blending to prevent air getting into the sauce.',
  'Stretch the dough to fit your peel or baking surface. Top with tomato sauce, mozzarella, and pepperoni.',
  'Bake for 5-6 minutes until the base is crispy and cheese is golden.',
  'Finish with hot honey, torn basil, and freshly grated Parmesan.',
]},

{id:164,name:'Green Bean Salad with Anchovy and Mustard Dressing',category:'Salads',difficulty:'medium',serves:4,time:'30 min',calories:220,mainIngredient:'Green Beans',
ingredients:[
  {name:'Fine green beans',amount:500,unit:'g'},
  {name:'Garlic clove',amount:1,unit:'clove'},
  {name:'Anchovy fillets',amount:12,unit:'whole'},
  {name:'Red wine vinegar',amount:1,unit:'tbsp'},
  {name:'Dijon mustard',amount:1,unit:'tbsp'},
  {name:'Egg yolk',amount:1,unit:'whole'},
  {name:'Extra virgin olive oil',amount:3,unit:'tbsp'},
  {name:'Olive oil',amount:3,unit:'tbsp'},
  {name:'Fresh basil leaves',amount:6,unit:'whole'},
  {name:'Radishes',prep:'finely sliced',amount:2,unit:'whole'},
  {name:'Black pepper',amount:1,unit:'to taste'},
],
steps:[
  'Using a mortar and pestle, crush the garlic to a pulp. Add 6 of the anchovy fillets and pound to a smooth paste, then transfer to a bowl.',
  'Add the vinegar, mustard and egg yolk to the anchovy paste and whisk well to form a thick paste.',
  'Slowly add the oils, whisking continuously to incorporate and emulsify.',
  'Bring a large saucepan of generously salted water to the boil. Plunge half the beans into the water and cook until al dente, then remove with a slotted spoon and plunge into iced water.',
  'Repeat with the remainder of the beans. When cold, pat dry and transfer to a bowl.',
  'Tear the basil leaves over the beans and add the radishes and 4 tablespoons of the anchovy dressing.',
  'Using your hands, toss the salad until the beans are well coated.',
  'Lay the salad on a serving plate. Cut the remaining anchovy fillets in half lengthwise and arrange over the salad.',
  'Dust generously with freshly ground black pepper and serve.',
]},

{id:165,name:'Cracked Wheat and Freekeh Salad with Preserved Lemon and Barberries',category:'Salads',difficulty:'hard',serves:4,time:'1 hr 15 min',calories:380,mainIngredient:'Freekeh',
ingredients:[
  {name:'Natural yoghurt',amount:400,unit:'ml'},
  {name:'Salt',amount:1,unit:'pinch'},
  {name:'Butter',amount:60,unit:'g'},
  {name:'Celery stalks',amount:2,unit:'whole',prep:'finely chopped'},
  {name:'Golden shallots',amount:2,unit:'whole',prep:'finely chopped'},
  {name:'Garlic clove',amount:1,unit:'clove',prep:'finely chopped'},
  {name:'Cracked wheat',amount:80,unit:'g'},
  {name:'Freekeh',amount:80,unit:'g',prep:'soaked'},
  {name:'Water',amount:380,unit:'ml'},
  {name:'Water',amount:250,unit:'ml'},
  {name:'Barberries',amount:2,unit:'tbsp'},
  {name:'Caraway water or ground caraway seeds',amount:1,unit:'tbsp'},
  {name:'Chardonnay vinegar',amount:2.5,unit:'tsp'},
  {name:'Extra virgin olive oil',amount:1.5,unit:'tbsp'},
  {name:'Preserved lemon',amount:0.5,unit:'tsp',prep:'finely chopped'},
  {name:'Toasted almonds',amount:80,unit:'g',prep:'chopped'},
  {name:'Spring onions',amount:4,unit:'whole',prep:'finely sliced'},
  {name:'Fresh mint',amount:1,unit:'handful',prep:'shredded'},
  {name:'Fresh parsley',amount:1,unit:'handful',prep:'shredded'},
],
steps:[
  'Season yoghurt with a pinch of salt, line a small sieve with muslin or clean cloth, place yoghurt in the sieve over a bowl, cover and refrigerate for 6 hours or overnight to drain.',
  'Divide butter, celery, shallot and garlic equally between two medium lidded saucepans. Place over low heat and sweat the vegetables for a few minutes.',
  'Add the bulgur to one pan and drained freekeh to the other. Stir to ensure each grain is covered with butter, then add 190ml water to each pan, bring to the boil and cover with cartouche and lid.',
  'Cook gently on the stovetop for about 12 minutes, checking and tasting until the grains are tender. Spread out on a board or plate to cool quickly.',
  'Pour 250ml warm water over barberries and leave to soak for 10 minutes. Strain barberries, reserving 3 tablespoons of the soaking liquid.',
  'Add strained barberries to the soaking liquid with caraway water, chardonnay vinegar, olive oil and salt. Set aside.',
  'When grains are cold, mix together the cooked bulgur and freekeh. Combine with the barberry vinaigrette.',
  'Arrange the grain mixture on a serving plate. Top with labne, preserved lemon, toasted almonds, spring onions, mint and parsley.',
  'Drizzle with additional olive oil and serve.',
]},
{id:166,name:'Carrot Tarte Tatin',category:'Sides',difficulty:'medium',serves:4,time:'1 hr 15 min',calories:350,mainIngredient:'Carrot',
ingredients:[
  {name:'Carrots',amount:6,unit:'whole'},
  {name:'Honey',amount:2,unit:'tbsp'},
  {name:'Apple cider vinegar',amount:1,unit:'tbsp'},
  {name:'Orange juice',amount:1,unit:'tbsp'},
  {name:'Cold butter',amount:2,unit:'tbsp'},
  {name:'Orange zest',amount:1,unit:'tsp'},
  {name:'Fresh thyme',amount:4,unit:'sprigs'},
  {name:'Puff pastry',amount:1,unit:'sheet'},
  {name:'Cold water',amount:1,unit:'tsp'},
  {name:'Crumbled feta cheese',amount:100,unit:'g'},
  {name:'Olive oil',amount:2,unit:'tbsp'},
  {name:'Flaky sea salt',amount:1,unit:'to taste'},
],
steps:[
  'Preheat the oven to 150°C (convection) and peel the carrots, cutting them lengthways.',
  'Roast the carrots in the oven until tender but still with a slight bite in the centre.',
  'Increase the oven temperature to 175°C.',
  'In a 20cm pan, combine honey, apple cider vinegar, and orange juice. Cook over medium-high heat without stirring until it reduces into a syrup with excess liquid evaporated.',
  'Lower heat to medium-low, add cold butter, and stir as it melts into a smooth caramel. If it splits, add 1 teaspoon cold water and whisk back together.',
  'Stir in orange zest and fresh thyme, then arrange the roasted carrots in the caramel.',
  'Cover with a sheet of puff pastry, tucking the edges around the filling, and prick a few small holes in the pastry to release steam.',
  'Bake at 175°C until the pastry is puffed and deeply golden brown, then remove and let rest for 30 minutes.',
  'Flip the tart out of the pan onto a plate. If it sticks, warm the pan gently on low heat.',
  'Top with crumbled feta cheese, fresh thyme, a drizzle of olive oil, and a sprinkle of flaky sea salt. Serve.',
]},

{id:167,name:'Vegemite and Cheese Cabbage',category:'Sides',difficulty:'easy',serves:2,time:'45 min',calories:250,mainIngredient:'Cabbage',
ingredients:[
  {name:'Cabbage',amount:1,unit:'whole'},
  {name:'Butter',amount:60,unit:'g'},
  {name:'Vegemite',amount:0.5,unit:'tsp'},
  {name:'Chicken or vegetable stock',amount:90,unit:'ml'},
  {name:'Parmesan',amount:20,unit:'g'},
  {name:'Salt',amount:1,unit:'to taste'},
  {name:'Black pepper',amount:1,unit:'to taste'},
],
steps:[
  'Quarter the cabbage and trim away some of the core.',
  'Combine the softened butter and Vegemite and mix well.',
  'Place the cabbage in an air fryer cake pan.',
  'Smear the butter mixture over the cabbage, add the stock to the pan, and season with salt and pepper.',
  'Cover with foil and cook for 30 minutes at 200°C.',
  'Remove the foil, spoon the cooking juices over the cabbage, and cook at 200°C for a further 5 minutes.',
  'Baste again and cook for another 2 minutes, or until caramelised.',
  'Remove the cabbage from the air fryer, baste with the cooking juices, and sprinkle over the Parmesan.',
]},

{id:168,name:'Fettuccine with Sardines, Cabbage, Garlic, Chilli and Lemon',category:'Pasta & Rice',difficulty:'easy',serves:2,time:'20 min',calories:550,mainIngredient:'Sardines',
ingredients:[
  {name:'Fettuccine',amount:200,unit:'g'},
  {name:'Garlic cloves',amount:3,unit:'clove'},
  {name:'Red chilli',amount:1,unit:'whole'},
  {name:'White cabbage',amount:200,unit:'g',prep:'thinly sliced'},
  {name:'Dry white wine',amount:120,unit:'ml'},
  {name:'Sardines in extra virgin olive oil',amount:2,unit:'tin',prep:'chopped'},
  {name:'Lemon',amount:1,unit:'whole',prep:'zested and juiced'},
  {name:'Butter',amount:20,unit:'g'},
  {name:'Fresh parsley',amount:1,unit:'handful',prep:'chopped'},
],
steps:[
  'Cook the fettuccine in salted boiling water until al dente.',
  'Thinly slice the garlic and chilli.',
  'In a pan, sauté the garlic and chilli in the oil from one tin of sardines until fragrant.',
  'Add the sliced cabbage and cook for a few minutes until softened.',
  'Pour in the white wine and let it reduce slightly.',
  'Add the chopped sardines, lemon zest and juice, and butter. Stir to combine and heat through gently.',
  'Drain the pasta, reserving a little cooking water. Toss with the sardine mixture, adding a splash of cooking water if needed to coat.',
  'Serve topped with chopped parsley.',
]},

{id:169,name:'New York Style Pepperoni and Hot Honey Pizza',category:'Bread & Bakes',difficulty:'hard',serves:4,time:'48 hr',calories:700,mainIngredient:'Pizza Dough',
ingredients:[
  {name:'Bread flour',amount:700,unit:'g'},
  {name:'Wholemeal flour',amount:300,unit:'g'},
  {name:'Salt',amount:25,unit:'g'},
  {name:'Olive oil',amount:30,unit:'ml'},
  {name:'Sugar',amount:20,unit:'g'},
  {name:'Dry yeast',amount:5,unit:'g'},
  {name:'Water',amount:570,unit:'ml'},
  {name:'Tinned tomatoes',amount:2,unit:'tin'},
  {name:'Dried oregano',amount:2,unit:'g'},
  {name:'Low-moisture mozzarella',amount:400,unit:'g',prep:'grated'},
  {name:'Pepperoni',amount:400,unit:'g',prep:'sliced'},
  {name:'Hot honey',amount:4,unit:'tbsp'},
  {name:'Fresh basil',amount:1,unit:'bunch'},
  {name:'Parmesan',amount:1,unit:'to taste'},
],
steps:[
  'Combine bread flour, wholemeal flour, sugar, dry yeast, and water in a large bowl. Mix by hand, then add olive oil and salt. Knead briefly to distribute.',
  'Knead on a workbench for 8-10 minutes until smooth. Cover and refrigerate for 48 hours.',
  'Three hours before baking, remove from the fridge, divide into 400g portions, roll into tight balls, place on a greased tray, and prove at room temperature for 2-3 hours.',
  'Preheat the oven to 400°C at least an hour ahead to heat-soak the baking surface.',
  'Blend tinned tomatoes with a pinch of salt, sugar, and dried oregano until smooth.',
  'Stretch the dough to fit your peel or baking surface. Top with tomato sauce, mozzarella, and pepperoni.',
  'Bake for 5-6 minutes until the base is crispy and the cheese is golden.',
  'Finish with hot honey, torn basil leaves, and freshly grated Parmesan.',
]},

{id:170,name:'High-Protein Chocolate Date Mousse',category:'Desserts',difficulty:'easy',serves:4,time:'15 min',calories:280,mainIngredient:'Dates',
ingredients:[
  {name:'Dates',amount:150,unit:'g'},
  {name:'Chia seeds',amount:60,unit:'g'},
  {name:'Cocoa powder',amount:30,unit:'g'},
  {name:'Greek yoghurt',amount:400,unit:'g'},
  {name:'Milk',amount:150,unit:'ml'},
  {name:'Whey protein powder',amount:1,unit:'scoop'},
  {name:'Vanilla extract',amount:5,unit:'g'},
  {name:'Salt',amount:1,unit:'pinch'},
],
steps:[
  'Combine everything except the chia seeds into a blender and blend until smooth.',
  'Stir in the chia seeds.',
  'Refrigerate for at least 2 hours until set.',
]},
];
