const RECIPES4 = [

// ── DIPS & STARTERS ──────────────────────────────────────
{id:124,name:'Whipped Feta with Snap Peas and Hot Honey',category:'Dips & Starters',difficulty:'easy',serves:4,time:'20 min',calories:280,mainIngredient:'Feta',
ingredients:[
  {name:'Feta',amount:200,unit:'g'},
  {name:'Skyr or Greek yoghurt',amount:3,unit:'tbsp'},
  {name:'Olive oil',amount:1,unit:'tbsp'},
  {name:'Black pepper',amount:1,unit:'to taste'},
  {name:'Lemon, zest and juice of half',amount:0.5,unit:'whole'},
  {name:'Salt',amount:1,unit:'pinch'},
  {name:'Snap peas',amount:200,unit:'g'},
  {name:'Olive oil (for peas)',amount:1,unit:'tbsp'},
  {name:'Honey',amount:2,unit:'tbsp'},
  {name:'Smoked paprika',amount:1,unit:'tsp'},
  {name:'Espelette pepper',amount:1,unit:'tsp'},
  {name:'Cider vinegar',amount:1,unit:'to taste'},
  {name:'Fresh mint',amount:1,unit:'handful'},
  {name:'Toasted pistachios',amount:2,unit:'tbsp'},
],
steps:[
  'Blend feta, yoghurt, olive oil, lemon zest and juice, black pepper, and a pinch of salt until smooth. Chill in the fridge to firm slightly.',
  'Blanch or lightly sauté the snap peas with olive oil, salt, and black pepper until just tender but still crisp.',
  'Make the hot honey by gently warming honey with smoked paprika, Espelette pepper, and a few drops of cider vinegar to infuse.',
  'Arrange the whipped feta on a plate, top with snap peas, drizzle with hot honey, and finish with fresh mint, lemon zest, olive oil, and toasted pistachios.',
  'Serve.',
]},

{id:125,name:'Burrata, Anchovy, Mint and Extra Virgin Olive Oil',category:'Dips & Starters',difficulty:'easy',serves:2,time:'5 min',calories:320,mainIngredient:'Burrata',
ingredients:[
  {name:'Burrata',amount:1,unit:'whole'},
  {name:'Anchovies',amount:6,unit:'whole'},
  {name:'Fresh mint leaves',amount:1,unit:'handful'},
  {name:'Extra virgin olive oil',amount:3,unit:'tbsp'},
],
steps:[
  'Place the burrata on a serving plate.',
  'Arrange the anchovies over the burrata.',
  'Scatter fresh mint leaves on top.',
  'Drizzle generously with extra virgin olive oil.',
  'Serve immediately.',
]},

// ── SALADS ──────────────────────────────────────────────
{id:126,name:'Dill Caesar Salad',category:'Salads',difficulty:'medium',serves:4,time:'25 min',calories:240,mainIngredient:'Baby Gem Lettuce',
ingredients:[
  {name:'Baby gem lettuce',amount:2,unit:'whole'},
  {name:'Fresh dill',amount:1,unit:'bunch'},
  {name:'Creamy dill Caesar dressing',amount:4,unit:'tbsp'},
  {name:'Anchovy breadcrumbs (spicy)',amount:4,unit:'tbsp'},
],
steps:[
  'Prepare the creamy dill Caesar dressing.',
  'Wash and dry the baby gem lettuce thoroughly.',
  'Toss the lettuce with the creamy dill Caesar dressing until coated.',
  'Make the spicy anchovy breadcrumbs and toast them until crispy.',
  'Plate the dressed lettuce and top generously with the anchovy breadcrumbs.',
  'Garnish with extra fresh dill before serving.',
]},

{id:127,name:'Spicy Onion Salad',category:'Salads',difficulty:'easy',serves:4,time:'15 min',calories:60,mainIngredient:'Red Onion',
ingredients:[
  {name:'Red onions, thinly sliced',amount:2,unit:'whole'},
  {name:'Tomato, finely chopped',amount:1,unit:'whole'},
  {name:'Green chilli, finely chopped',amount:1,unit:'whole'},
  {name:'Fresh coriander, chopped',amount:2,unit:'tbsp'},
  {name:'Lemon juice',amount:1,unit:'tbsp'},
  {name:'Salt',amount:1,unit:'tsp'},
  {name:'Chilli powder',amount:0.5,unit:'tsp'},
  {name:'Roasted cumin powder',amount:0.5,unit:'tsp'},
],
steps:[
  'Place the sliced onions in a bowl of cold water for 10 minutes to reduce sharpness. Drain well.',
  'Combine onions, tomato, green chilli, and fresh coriander in a mixing bowl.',
  'Sprinkle in salt, chilli powder, and roasted cumin powder.',
  'Add the lemon juice and toss everything together until evenly coated.',
  'Serve immediately as a side dish with grilled or tandoori meats.',
]},

{id:128,name:'Chilled Cucumber and Asparagus with Herb Fish Sauce Dressing',category:'Salads',difficulty:'easy',serves:4,time:'15 min',calories:80,mainIngredient:'Cucumber',
ingredients:[
  {name:'Cucumbers',amount:2,unit:'whole'},
  {name:'Asparagus',amount:200,unit:'g'},
  {name:'Fresh herbs',amount:1,unit:'handful'},
  {name:'Fish sauce',amount:2,unit:'tbsp'},
],
steps:[
  'Prepare the cucumbers and asparagus by chilling them.',
  'Chop the fresh herbs.',
  'Make a dressing by combining the herbs with fish sauce.',
  'Arrange the chilled cucumbers and asparagus on a plate.',
  'Drizzle the herb and fish sauce dressing over the vegetables.',
  'Serve immediately.',
]},

{id:129,name:'Beetroot, Whipped Ricotta and Pistachios',category:'Salads',difficulty:'easy',serves:4,time:'30 min',calories:260,mainIngredient:'Beetroot',
ingredients:[
  {name:'Beetroot',amount:4,unit:'whole'},
  {name:'Ricotta',amount:200,unit:'g'},
  {name:'Lemon',amount:0.5,unit:'whole'},
  {name:'Olive oil',amount:3,unit:'tbsp'},
  {name:'Pistachios',amount:50,unit:'g'},
  {name:'Honey',amount:1,unit:'tbsp'},
  {name:'Dijon mustard',amount:1,unit:'tsp'},
  {name:'Red wine vinegar',amount:1,unit:'tbsp'},
  {name:'Aleppo pepper',amount:0.5,unit:'tsp'},
  {name:'Fresh mint',amount:1,unit:'handful'},
],
steps:[
  'Roast or boil the beetroot until tender, then peel and slice.',
  'Whip the ricotta with a bit of lemon juice and zest until smooth and fluffy.',
  'Make a dressing with olive oil, chopped pistachios, honey, dijon mustard, red wine vinegar, and Aleppo pepper.',
  'Arrange the beetroot on a plate, dollop with whipped ricotta, and drizzle with the pistachio dressing.',
  'Sprinkle fresh mint leaves over the top before serving.',
]},

// ── SEAFOOD ──────────────────────────────────────────────
{id:130,name:'Prawn Carpaccio with Prawn Head Oil Dressing',category:'Seafood',difficulty:'medium',serves:4,time:'30 min',calories:160,mainIngredient:'Prawns',
ingredients:[
  {name:'Fresh prawns',amount:500,unit:'g'},
  {name:'Olive oil',amount:4,unit:'tbsp'},
  {name:'Salt',amount:1,unit:'to taste'},
],
steps:[
  'Prepare the prawns by carefully removing the heads and shells.',
  'Reserve the prawn heads for making the oil dressing.',
  'Lay the prawn meat flat and slice thinly to create the carpaccio.',
  'Heat olive oil in a pan and gently cook the prawn heads to infuse the oil with flavour.',
  'Strain the oil to remove the prawn heads, creating the prawn head oil dressing.',
  'Arrange the prawn carpaccio on a plate and drizzle with the prawn head oil.',
  'Sprinkle with a pinch of salt and serve immediately.',
]},

{id:131,name:'Dover Sole with Fennel, Orange and Chilli Butter',category:'Seafood',difficulty:'medium',serves:2,time:'35 min',calories:520,mainIngredient:'Dover Sole',
ingredients:[
  {name:'Fennel bulb, finely sliced',amount:1,unit:'whole'},
  {name:'Lemon juice',amount:0.5,unit:'whole'},
  {name:'Chives, finely chopped',amount:1,unit:'tbsp'},
  {name:'Dill',amount:1,unit:'handful'},
  {name:'Olive oil',amount:4,unit:'tbsp'},
  {name:'Dover sole',amount:1,unit:'whole'},
  {name:'Flour',amount:3,unit:'tbsp'},
  {name:'Butter',amount:70,unit:'g'},
  {name:'Orange, zest and juice',amount:1,unit:'whole'},
  {name:'Fennel seeds',amount:1,unit:'tbsp'},
  {name:'Red chilli, finely chopped',amount:1,unit:'whole'},
  {name:'Capers',amount:2,unit:'tbsp'},
],
steps:[
  'Thinly shave the fennel bulb, then toss with the herbs, lemon juice, olive oil, salt, and fennel fronds. Set aside.',
  'Pat the Dover sole dry and season well with salt and pepper. Coat in flour and tap off the excess.',
  'Heat a large frying pan over medium-high heat with olive oil and 50g butter. Cook the Dover sole for 3–4 minutes on the first side until golden.',
  'Flip the fish and baste continuously with the butter for another 3 minutes until just cooked through. Remove the fish to a plate and rest.',
  'Lower the heat. Add fennel seeds and chilli to the pan and cook for 30 seconds, then add capers, orange zest, orange juice, and remaining butter.',
  'Let the sauce bubble for 1–2 minutes until glossy and reduced. Stir through chives and spoon over the Dover sole.',
  'Serve with the shaved fennel salad alongside.',
]},

// ── MEAT & POULTRY ───────────────────────────────────────
{id:132,name:'Ginger & Spring Onion Poached Chicken',category:'Meat & Poultry',difficulty:'easy',serves:4,time:'45 min',calories:340,mainIngredient:'Chicken',
ingredients:[
  {name:'Chicken drumsticks',amount:6,unit:'whole'},
  {name:'Ginger, thick slices',amount:3,unit:'slices'},
  {name:'Spring onions',amount:4,unit:'whole'},
  {name:'Rice bran or vegetable oil',amount:3,unit:'tbsp'},
  {name:'Ginger, finely chopped',amount:15,unit:'g'},
  {name:'Sugar',amount:1,unit:'tsp'},
  {name:'Sesame oil',amount:1,unit:'tsp'},
  {name:'Poaching liquid',amount:80,unit:'ml'},
  {name:'Light soy sauce',amount:3,unit:'tbsp'},
],
steps:[
  'Bring about 2L of water to a boil and add the ginger slices and spring onion.',
  'Add the chicken and bring back to a boil, then lower the heat, cover, and gently simmer for 10 minutes.',
  'Turn off the heat and leave the chicken in the pot, covered, for about 20 minutes to finish cooking gently. Remove, shred, and plate up.',
  'Heat the oil in a pan and fry the spring onion and ginger until fragrant and just starting to turn golden.',
  'Add the sugar, sesame oil, poaching liquid, and light soy sauce, letting it simmer for another minute.',
  'Taste and adjust seasoning, then spoon over the chicken and serve with rice.',
]},

{id:133,name:'One-Pan Sausage and Feta Shakshuka',category:'Meat & Poultry',difficulty:'easy',serves:4,time:'35 min',calories:580,mainIngredient:'Sausages',
ingredients:[
  {name:'Olive oil',amount:2,unit:'tbsp'},
  {name:'Brown onion, diced',amount:1,unit:'whole'},
  {name:'Garlic cloves, roughly chopped',amount:2,unit:'cloves'},
  {name:'Baby red peppers, halved',amount:10,unit:'whole'},
  {name:'Ground cumin',amount:2,unit:'tsp'},
  {name:'Ground coriander',amount:2,unit:'tsp'},
  {name:'Smoky paprika',amount:2,unit:'tsp'},
  {name:'Beef sausages, halved',amount:500,unit:'g'},
  {name:'Tinned chopped tomatoes',amount:400,unit:'g'},
  {name:'Tinned cherry tomatoes',amount:400,unit:'g'},
  {name:'Tinned chickpeas',amount:400,unit:'g'},
  {name:'Free-range eggs',amount:5,unit:'whole'},
  {name:'Persian feta',amount:180,unit:'g'},
  {name:'Za\'atar',amount:3,unit:'tbsp'},
  {name:'Pita bread',amount:4,unit:'whole'},
  {name:'Parsley, roughly chopped',amount:1,unit:'handful'},
],
steps:[
  'Place a large frying pan over medium-high heat. Add the olive oil, onion, garlic, and pepper with a good pinch of salt. Cook, stirring often, until slightly softened.',
  'Add the sausages and spices and cook, stirring often, for a further 2 minutes.',
  'Add the chopped tomatoes, cherry tomatoes, and chickpeas. Simmer for 10 minutes to cook the sausages.',
  'Crack in the eggs, cover the pan, and simmer over low heat for 10 minutes, until the eggs are just cooked.',
  'Warm the pita in a dry, hot pan and sprinkle over half the za\'atar.',
  'Serve the shakshuka with the feta crumbled over, the remaining za\'atar, and parsley scattered on top.',
]},

{id:134,name:'Blackened Chicken with Spiced Honey Butter and Wedge Salad',category:'Meat & Poultry',difficulty:'medium',serves:4,time:'60 min',calories:620,mainIngredient:'Chicken',
ingredients:[
  {name:'Spatchcock chicken',amount:1,unit:'whole'},
  {name:'Banana shallots',amount:6,unit:'whole'},
  {name:'Butter',amount:2,unit:'tbsp'},
  {name:'Garlic cloves, sliced',amount:4,unit:'cloves'},
  {name:'Red wine vinegar',amount:3,unit:'tbsp'},
  {name:'Honey',amount:2,unit:'tbsp'},
  {name:'Olive oil',amount:2,unit:'tbsp'},
  {name:'Black pepper',amount:2,unit:'tbsp'},
  {name:'Cumin',amount:1,unit:'tbsp'},
  {name:'Coriander',amount:1,unit:'tbsp'},
  {name:'Chilli powder',amount:1,unit:'tbsp'},
  {name:'Paprika',amount:1,unit:'tbsp'},
  {name:'Salt',amount:1,unit:'tbsp'},
  {name:'Gem lettuces',amount:4,unit:'whole'},
  {name:'Fresh dill',amount:1,unit:'bunch'},
  {name:'Fresh parsley',amount:1,unit:'bunch'},
  {name:'Lemon juice',amount:1,unit:'whole'},
  {name:'Greek yoghurt',amount:6,unit:'tbsp'},
  {name:'Tahini',amount:2,unit:'tbsp'},
  {name:'Extra virgin olive oil',amount:100,unit:'ml'},
  {name:'Spring onion, sliced',amount:1,unit:'whole'},
],
steps:[
  'Make the spice mix and marinate the chicken, reserving 1 tablespoon for the pan sauce later.',
  'Heat an ovenproof pan over medium heat. Add olive oil and place the chicken skin-side down for about 7 minutes until well coloured. Turn and cook for a further 3 minutes.',
  'Remove the chicken from the pan and add the shallots cut-side down. Sit the chicken back on top and roast for 30 minutes at 200°C, or until cooked through.',
  'For the dressing, blitz parsley, dill, olive oil, tahini, garlic, lemon juice and 2 tbsp water until smooth and bright green. Fold into the yoghurt and season.',
  'Give the lettuce wedges an ice bath and drain until dry. Drizzle with the green yoghurt dressing and garnish with spring onion, sesame seeds and chilli flakes.',
  'While the chicken rests, add butter, sliced garlic and reserved spice mix to the pan. Cook 2 minutes, scraping up the base. Remove from heat and stir in honey and red wine vinegar.',
  'Serve the warm sauce over the blackened chicken and sticky shallots alongside the wedge salad.',
]},

{id:135,name:'Tasty Chicken',category:'Meat & Poultry',difficulty:'easy',serves:4,time:'40 min',calories:310,mainIngredient:'Chicken',
ingredients:[
  {name:'Chicken thighs (boneless/skinless)',amount:4,unit:'whole'},
  {name:'Turmeric',amount:1,unit:'tsp'},
  {name:'Garlic cloves, crushed',amount:2,unit:'cloves'},
  {name:'Paprika',amount:1,unit:'tsp'},
  {name:'Cumin',amount:1,unit:'tsp'},
  {name:'Ground black pepper',amount:0.5,unit:'tsp'},
  {name:'Salt',amount:1,unit:'tsp'},
  {name:'Fish sauce',amount:1,unit:'tbsp'},
  {name:'Dijon mustard',amount:0.5,unit:'tbsp'},
  {name:'Honey',amount:1,unit:'tsp'},
  {name:'Olive oil',amount:1,unit:'tbsp'},
  {name:'Lemon juice',amount:2,unit:'tsp'},
],
steps:[
  'Combine all ingredients except the chicken and half the lemon juice. Add the chicken and coat thoroughly.',
  'Place the chicken and marinade into a small baking dish and cook for 15 minutes at 200°C.',
  'Turn the chicken over and cook for a further 15 minutes.',
  'Remove from oven, place the chicken and all cooking juices in a bowl, and let cool for 20 minutes.',
  'Shred or chop the chicken and mix with the remaining 1 tsp lemon juice. Adjust seasoning with extra salt if needed.',
]},

// ── VEGETARIAN ───────────────────────────────────────────
{id:136,name:'Miso Garlic Butter Cabbage with Braised Butter Beans',category:'Vegetarian',difficulty:'medium',serves:4,time:'50 min',calories:360,mainIngredient:'Cabbage',
ingredients:[
  {name:'Pointed cabbage',amount:1,unit:'whole'},
  {name:'Neutral oil (avocado/sunflower)',amount:2,unit:'tbsp'},
  {name:'Salted butter',amount:50,unit:'g'},
  {name:'White miso paste',amount:1,unit:'tsp'},
  {name:'Garlic cloves, minced',amount:4,unit:'cloves'},
  {name:'Smoked paprika',amount:1,unit:'tsp'},
  {name:'Shallot, finely diced',amount:1,unit:'whole'},
  {name:'Fresh parsley, finely chopped',amount:1,unit:'bunch'},
  {name:'Cider vinegar',amount:1,unit:'tbsp'},
  {name:'Butter beans',amount:570,unit:'g'},
  {name:'Nutritional yeast',amount:1,unit:'tbsp'},
  {name:'Lemon, zested',amount:0.5,unit:'whole'},
  {name:'Chilli crisp',amount:1,unit:'to serve'},
],
steps:[
  'Preheat your oven and prepare a frypan.',
  'Halve the pointed cabbage and drizzle with neutral oil. Season with salt and pepper.',
  'Mix the salted butter, white miso paste, minced garlic, and smoked paprika to make the miso-garlic butter.',
  'Sear the cabbage in the frypan until golden on the cut sides, then transfer to the oven.',
  'Roast the cabbage, basting occasionally with the miso-garlic butter, until tender and caramelised.',
  'Meanwhile, sauté the diced shallot and minced garlic in a little oil until soft.',
  'Add the chopped parsley, cider vinegar, drained butter beans, nutritional yeast, and lemon zest. Stir gently and heat through until creamy.',
  'Serve the roasted cabbage on top of the braised butter beans.',
  'Garnish with finely diced chives, toasted sesame seeds, and a spoon of chilli crisp before serving.',
]},

// ── PASTA & RICE ─────────────────────────────────────────
{id:137,name:'Mussel and \'Nduja Pasta',category:'Pasta & Rice',difficulty:'medium',serves:4,time:'35 min',calories:520,mainIngredient:'Mussels',
ingredients:[
  {name:'Fresh mussels',amount:1,unit:'kg'},
  {name:'\'Nduja sausage',amount:100,unit:'g'},
  {name:'Pasta of choice',amount:400,unit:'g'},
  {name:'Olive oil',amount:2,unit:'tbsp'},
  {name:'Garlic cloves, chopped',amount:3,unit:'cloves'},
  {name:'White wine',amount:100,unit:'ml'},
  {name:'Cherry tomatoes',amount:200,unit:'g'},
  {name:'Fresh parsley',amount:1,unit:'handful'},
  {name:'Salt and pepper',amount:1,unit:'to taste'},
],
steps:[
  'Clean and debeard the mussels thoroughly, discarding any that are open and do not close when tapped.',
  'Heat olive oil in a large pan over medium heat and sauté chopped garlic until fragrant.',
  'Add the \'nduja sausage, breaking it up with a spoon, and cook until it releases its oils.',
  'Pour in a splash of white wine and allow it to reduce slightly.',
  'Add the cherry tomatoes and cook until they begin to soften.',
  'Toss in the cleaned mussels, cover the pan, and cook for 3–4 minutes until all the mussels open.',
  'Meanwhile, cook the pasta in salted water until al dente, then drain.',
  'Add the cooked pasta to the pan with the mussels and toss to coat in the sauce.',
  'Finish with freshly chopped parsley, season with salt and pepper, and serve immediately.',
]},

// ── SIDES ─────────────────────────────────────────────────
{id:138,name:'Carrot Tarte Tatin',category:'Sides',difficulty:'medium',serves:6,time:'90 min',calories:320,mainIngredient:'Carrots',
ingredients:[
  {name:'Carrots',amount:6,unit:'whole'},
  {name:'Honey',amount:2,unit:'tbsp'},
  {name:'Apple cider vinegar',amount:1.5,unit:'tsp'},
  {name:'Orange juice',amount:1.5,unit:'tsp'},
  {name:'Cold butter',amount:2,unit:'tbsp'},
  {name:'Orange zest',amount:1,unit:'to taste'},
  {name:'Fresh thyme',amount:1,unit:'sprig'},
  {name:'Puff pastry sheet',amount:1,unit:'sheet'},
  {name:'Crumbled feta cheese',amount:60,unit:'g'},
  {name:'Olive oil',amount:1,unit:'tbsp'},
  {name:'Flaky sea salt',amount:1,unit:'to taste'},
],
steps:[
  'Preheat the oven to 150°C (300°F) convection.',
  'Peel and cut the carrots lengthways, place them in the oven and roast until tender but still with a slight bite in the centre.',
  'Once the carrots are cooked, increase the oven temperature to 175°C (350°F).',
  'In a 20cm pan, combine the honey, apple cider vinegar, and orange juice. Cook over medium-high heat without stirring until it reduces and thickens into a syrup.',
  'Lower the heat to medium-low and add cold butter, stirring until it melts and forms a smooth caramel. If it splits, add 1 tsp cold water and whisk until it comes back together.',
  'Stir in orange zest and fresh thyme, then arrange the roasted carrots in the pan.',
  'Cover the carrots with puff pastry, tucking the edges around the filling. Prick a few holes to let steam escape, then bake at 175°C until the pastry is puffed and golden brown.',
  'Remove from the oven and let rest for about 30 minutes.',
  'Flip the tart onto a plate to serve. If it sticks, warm the pan briefly over low heat.',
  'Finish with crumbled feta, fresh thyme, a drizzle of olive oil, and a sprinkle of flaky sea salt.',
]},

{id:139,name:'Potato Galette',category:'Sides',difficulty:'medium',serves:4,time:'60 min',calories:380,mainIngredient:'Potato',
ingredients:[
  {name:'Sebago potatoes, peeled and thinly sliced',amount:2,unit:'whole'},
  {name:'Salt and pepper',amount:1,unit:'to taste'},
  {name:'Clarified butter, melted',amount:500,unit:'g'},
],
steps:[
  'Preheat the oven to 160°C.',
  'Line a small ovenproof frying pan or skillet with baking paper.',
  'Using a mandolin set to 3mm, slice the potatoes on the short end.',
  'Place the slices into a medium mixing bowl, drizzle with clarified butter until well coated, and season with salt.',
  'Arrange the slices on the baking paper in overlapping circles.',
  'Pour a little more clarified butter over the top and cover with baking paper.',
  'Bake for about 40 minutes until golden brown, crispy, and the potatoes are cooked through.',
  'Remove the galette from the baking tray and season with salt to serve.',
]},

// ── SAUCES ────────────────────────────────────────────────
{id:140,name:'Copy Cat Lori-Jayne AP Sauce',category:'Sauces',difficulty:'hard',serves:8,time:'75 min',calories:180,mainIngredient:'Cream',
ingredients:[
  {name:'Butter',amount:4,unit:'tbsp'},
  {name:'Shallots',amount:6,unit:'whole'},
  {name:'Garlic cloves',amount:6,unit:'cloves'},
  {name:'Cognac',amount:30,unit:'ml'},
  {name:'White wine (Sauvignon Blanc)',amount:250,unit:'ml'},
  {name:'Soy sauce',amount:24,unit:'g'},
  {name:'Black vinegar',amount:10,unit:'g'},
  {name:'Kecap manis',amount:30,unit:'g'},
  {name:'Sherry vinegar',amount:15,unit:'g'},
  {name:'Fish sauce',amount:7,unit:'g'},
  {name:'Lemon juice',amount:12,unit:'g'},
  {name:'Chicken stock',amount:500,unit:'ml'},
  {name:'Heavy cream',amount:250,unit:'ml'},
  {name:'Fresh thyme',amount:2,unit:'sprigs'},
  {name:'Red Sichuan peppercorns',amount:2,unit:'tbsp'},
  {name:'Green Sichuan peppercorns',amount:2,unit:'tbsp'},
  {name:'Black peppercorns',amount:2,unit:'tbsp'},
],
steps:[
  'Add shallots and butter to a cold pan.',
  'Cook shallots over low heat for 30–35 minutes until deeply softened.',
  'Add minced garlic, turn heat back up to medium and cook until fragrant.',
  'Add 1 shot of cognac and let it cook off.',
  'Add the white wine and let all alcohol cook off completely.',
  'Add soy sauce, black vinegar, kecap manis, sherry vinegar, fish sauce, and lemon juice.',
  'Add chicken stock and cook down for about 20 minutes to reduce by roughly half.',
  'Add heavy cream and thyme. Bring to a boil, then cut the heat.',
  'Strain the sauce through a fine sieve.',
  'Gently toast the peppercorns until fragrant, then blend and stir into the sauce to taste.',
  'Serve warm.',
]},

// ── DESSERTS ──────────────────────────────────────────────
{id:141,name:'Strawberry & Champagne Jelly with White Chocolate Panna Cotta',category:'Desserts',difficulty:'hard',serves:4,time:'4 hr 30 min',calories:480,mainIngredient:'Cream',
ingredients:[
  {name:'Thickened cream',amount:300,unit:'g'},
  {name:'Caster sugar',amount:55,unit:'g'},
  {name:'Vanilla paste',amount:0.5,unit:'tbsp'},
  {name:'White chocolate',amount:140,unit:'g'},
  {name:'Gold-strength gelatine leaves',amount:3,unit:'whole'},
  {name:'Greek yoghurt',amount:125,unit:'g'},
  {name:'Strawberry juice',amount:100,unit:'ml'},
  {name:'Champagne or sparkling wine',amount:100,unit:'ml'},
],
steps:[
  'Place the cream, 40g sugar, and vanilla in a small saucepan and stir over medium heat until just beginning to simmer. Remove from the heat.',
  'Add the white chocolate and whisk until completely melted and smooth.',
  'Soak 1 gelatine leaf in cold water until softened. Squeeze out excess water, then stir into the warm cream mixture until fully dissolved.',
  'Transfer to a bowl and allow to cool to room temperature. Add the Greek yoghurt and whisk until smooth.',
  'Divide evenly between four serving glasses. Refrigerate for at least 2 hours, or until set.',
  'Combine the strawberry juice, Champagne, and remaining 15g sugar in a small saucepan. Warm gently over low heat, stirring until the sugar dissolves. Do not boil.',
  'Soak 2 gelatine leaves in cold water until softened. Squeeze out excess water, then stir gently into the warm strawberry mixture until dissolved.',
  'Allow the jelly mixture to cool to room temperature. Once the panna cotta has set, carefully pour the jelly over the top of each glass.',
  'Refrigerate for a further 2 hours, or until the jelly is set.',
  'Serve chilled. Best enjoyed on the day it is made.',
]},

];
