const CATEGORIES = ['Dips & Starters','Salads','Soups','Seafood','Meat & Poultry','Vegetarian','Pasta & Rice','Sides','Bread & Bakes','Sauces','Desserts'];

const SW = {
  'Dips & Starters':'sw-entrees',
  'Salads':'sw-salads',
  'Soups':'sw-soups',
  'Seafood':'sw-sky',
  'Meat & Poultry':'sw-mains',
  'Vegetarian':'sw-veggie',
  'Pasta & Rice':'sw-pasta',
  'Sides':'sw-sides',
  'Bread & Bakes':'sw-snacks',
  'Sauces':'sw-sauces',
  'Desserts':'sw-desserts',
};

const RECIPES = [

// ── DIPS & STARTERS ──────────────────────────────────────
{id:1,name:'Avocado Tzatziki',category:'Dips & Starters',difficulty:'easy',serves:3,time:'15 min',calories:180,mainIngredient:'Avocado',
ingredients:[
  {name:'Avocados',amount:2,unit:'whole'},
  {name:'Greek yoghurt',amount:260,unit:'g'},
  {name:'Cucumber, grated and squeezed dry',amount:1,unit:'whole'},
  {name:'Garlic clove, crushed',amount:1,unit:'clove'},
  {name:'White wine vinegar',amount:30,unit:'ml'},
  {name:'Fresh mint, chopped',amount:1,unit:'handful'},
  {name:'Olive oil',amount:15,unit:'ml'},
  {name:'Salt and black pepper',amount:1,unit:'to taste'},
],
steps:[
  'Mash avocados in a bowl until smooth.',
  'Mix in yoghurt, grated cucumber, garlic, vinegar and chopped mint.',
  'Season well with salt and black pepper.',
  'Transfer to a serving bowl and drizzle with olive oil.',
  'Top with radish slices, dill and fresh mint. Serve chilled.',
]},

{id:2,name:'Beetroot Dip with Yoghurt & Dukkah',category:'Dips & Starters',difficulty:'easy',serves:4,time:'70 min',calories:150,mainIngredient:'Beetroot',
ingredients:[
  {name:'Beetroot, scrubbed',amount:500,unit:'g'},
  {name:'Olive oil',amount:30,unit:'ml'},
  {name:'Greek yoghurt',amount:200,unit:'g'},
  {name:'Garlic clove, crushed',amount:1,unit:'clove'},
  {name:'Lemon juice',amount:30,unit:'ml'},
  {name:'Dukkah',amount:30,unit:'g'},
  {name:'Salt and pepper',amount:1,unit:'to taste'},
],
steps:[
  'Heat oven to 200°C. Wrap beetroot in foil, drizzle with olive oil, roast 45–60 minutes until tender.',
  'Cool, peel and chop the beetroot.',
  'Blend beetroot with yoghurt, garlic, lemon juice, salt and pepper until smooth.',
  'Spoon into a bowl, drizzle with olive oil and sprinkle with dukkah.',
]},

{id:3,name:'Edamame Dip',category:'Dips & Starters',difficulty:'easy',serves:4,time:'10 min',calories:120,mainIngredient:'Edamame',
ingredients:[
  {name:'Edamame, ready to eat',amount:500,unit:'g'},
  {name:'White soy sauce',amount:30,unit:'ml'},
  {name:'Yoghurt',amount:30,unit:'ml'},
  {name:'Mirin',amount:15,unit:'ml'},
  {name:'Wasabi',amount:15,unit:'g'},
  {name:'Salt',amount:1,unit:'to taste'},
],
steps:[
  'Blend the edamame briefly to break them down.',
  'Add white soy, yoghurt, mirin and wasabi. Blend until almost smooth — leave a little texture.',
  'Season with salt. Serve with chips or crunchy vegetables.',
]},

{id:4,name:'Loaded Spring Hummus',category:'Dips & Starters',difficulty:'easy',serves:2,time:'30 min',calories:520,mainIngredient:'Chickpeas',
ingredients:[
  {name:'Chickpeas (reserve aquafaba)',amount:400,unit:'g'},
  {name:'Garlic clove',amount:1,unit:'clove'},
  {name:'Tahini',amount:80,unit:'g'},
  {name:'Lemon juice',amount:15,unit:'ml'},
  {name:'Water',amount:125,unit:'ml'},
  {name:'Broccolini',amount:1,unit:'bunch',prep:'cut'},
  {name:'Cucumber',amount:1,unit:'whole',prep:'thinly sliced'},
  {name:'Asparagus',amount:1,unit:'bunch',prep:'thinly sliced'},
  {name:'Peas',amount:75,unit:'g',prep:'thawed'},
  {name:'Capers',amount:15,unit:'g'},
  {name:'Lemon zest',amount:1,unit:'lemon'},
  {name:'Mint, parsley and dill',amount:1,unit:'handful'},
  {name:'Vinegar',amount:15,unit:'ml'},
  {name:'Olive oil',amount:80,unit:'ml'},
  {name:'Za\'atar',amount:5,unit:'g'},
  {name:'Marinated feta',amount:100,unit:'g'},
],
steps:[
  'Blend chickpeas with aquafaba, garlic, tahini, lemon juice and water until very smooth. Season.',
  'Blanch broccolini 30 seconds, refresh in iced water.',
  'Toss broccolini, asparagus, cucumber and peas with vinegar, 2 tbsp oil, salt and pepper.',
  'Spread hummus on a plate, sprinkle za\'atar and drizzle with oil.',
  'Pile the green salad on top, finish with capers, feta and flatbread.',
]},

{id:5,name:'Burrata with Grilled Grapes & Basil',category:'Dips & Starters',difficulty:'easy',serves:4,time:'20 min',calories:280,mainIngredient:'Burrata',
ingredients:[
  {name:'Seedless grapes',amount:400,unit:'g'},
  {name:'Olive oil',amount:30,unit:'ml'},
  {name:'Honey',amount:15,unit:'ml'},
  {name:'Red wine vinegar',amount:15,unit:'ml'},
  {name:'Burrata cheese',amount:200,unit:'g'},
  {name:'Lemon zest and juice',amount:0.5,unit:'lemon'},
  {name:'Fresh basil leaves',amount:1,unit:'handful'},
  {name:'Salt and pepper',amount:1,unit:'to taste'},
],
steps:[
  'Toss grapes with olive oil, honey and vinegar.',
  'Grill grapes 3–4 minutes until blistered and caramelised.',
  'Toss warm grapes with lemon zest and juice, season well.',
  'Place burrata on a platter, arrange grapes around it, drizzle over all the juices.',
  'Scatter basil and serve with crusty bread.',
]},

{id:6,name:'Grilled Haloumi with Babaganoush, Honey & Za\'atar',category:'Dips & Starters',difficulty:'easy',serves:2,time:'20 min',calories:450,mainIngredient:'Haloumi',
ingredients:[
  {name:'Haloumi, sliced',amount:250,unit:'g'},
  {name:'Olive oil',amount:60,unit:'ml'},
  {name:'Cucumbers, sliced',amount:2,unit:'whole'},
  {name:'Dill, mint and coriander',amount:1,unit:'handful'},
  {name:'White wine vinegar',amount:15,unit:'ml'},
  {name:'Babaganoush',amount:600,unit:'g'},
  {name:'Honey',amount:30,unit:'ml'},
  {name:'Lemon juice',amount:15,unit:'ml'},
  {name:'Za\'atar',amount:15,unit:'g'},
],
steps:[
  'Fry haloumi in 1 tbsp oil over medium-high heat until golden on both sides.',
  'Toss cucumber with herbs, vinegar and remaining oil. Season.',
  'Spread babaganoush on a large platter. Top with grilled haloumi.',
  'Drizzle with honey and lemon juice, sprinkle with za\'atar.',
  'Finish with the cucumber herb salad.',
]},

{id:7,name:'Grilled Smoky Oysters with Soy & Coconut Vinaigrette',category:'Dips & Starters',difficulty:'medium',serves:4,time:'15 min',calories:80,mainIngredient:'Oysters',
ingredients:[
  {name:'Fresh shucked oysters',amount:12,unit:'whole'},
  {name:'Olive oil',amount:15,unit:'ml'},
  {name:'Soy sauce',amount:15,unit:'ml'},
  {name:'Rice vinegar',amount:15,unit:'ml'},
  {name:'Coconut cream',amount:30,unit:'ml'},
  {name:'Sesame oil',amount:5,unit:'ml'},
  {name:'Red chilli, finely sliced',amount:0.5,unit:'whole'},
  {name:'Spring onion, finely chopped',amount:1,unit:'whole'},
],
steps:[
  'Heat barbecue or grill pan until very hot.',
  'Brush oysters lightly with olive oil.',
  'Place oysters shell-side down on grill for 2–3 minutes until lightly smoky.',
  'Mix soy sauce, rice vinegar, coconut cream, sesame oil, chilli and spring onion.',
  'Spoon vinaigrette over oysters and serve immediately.',
]},

{id:8,name:'Smoky Oysters over Coals with Coconut Vinaigrette',category:'Dips & Starters',difficulty:'medium',serves:4,time:'20 min',calories:90,mainIngredient:'Oysters',
ingredients:[
  {name:'Oysters in shells',amount:12,unit:'whole'},
  {name:'Red chilli, finely diced',amount:1,unit:'whole'},
  {name:'Garlic clove, finely diced',amount:1,unit:'clove'},
  {name:'Soy sauce',amount:30,unit:'ml'},
  {name:'Coconut vinegar',amount:15,unit:'ml'},
  {name:'Mirin',amount:15,unit:'ml'},
  {name:'Coconut cream',amount:30,unit:'ml'},
  {name:'Rice vinegar',amount:15,unit:'ml'},
  {name:'Coriander stems, chopped',amount:1,unit:'handful'},
  {name:'Blood orange zest',amount:1,unit:'orange'},
],
steps:[
  'Heat coals until very hot. Place oysters shell-side down over coals, cover with a hot pan to trap smoke. Cook until shells open, about 2 minutes.',
  'Combine soy, coconut vinegar, mirin, coconut cream, rice vinegar, garlic and chilli in a small pan. Simmer 10–15 minutes then cool.',
  'Open oysters, reserving juices. Strain juices into the vinaigrette.',
  'Rinse oyster meat briefly in lightly acidulated water, then return to shells.',
  'Spoon vinaigrette over oysters, garnish with coriander stem and blood orange zest.',
]},

// ── SALADS ───────────────────────────────────────────────
{id:9,name:'Baby Cos Wedge Salad with Whipped Goat\'s Cheese',category:'Salads',difficulty:'easy',serves:2,time:'15 min',calories:280,mainIngredient:'Lettuce',
ingredients:[
  {name:'Baby cos lettuces, cut into wedges',amount:4,unit:'whole'},
  {name:'Olive oil',amount:60,unit:'ml'},
  {name:'Red wine vinegar',amount:30,unit:'ml'},
  {name:'Radishes, thinly sliced',amount:4,unit:'whole'},
  {name:'Dill, chopped',amount:1,unit:'handful'},
  {name:'Goat\'s cheese',amount:100,unit:'g'},
  {name:'Greek yoghurt',amount:95,unit:'g'},
  {name:'Garlic cloves, crushed',amount:2,unit:'cloves'},
  {name:'Lemon juice',amount:30,unit:'ml'},
],
steps:[
  'Blend goat\'s cheese, yoghurt, garlic, lemon juice and 80 ml water until smooth. Season well.',
  'Arrange cos wedges on a plate, season with salt and pepper.',
  'Drizzle with olive oil and red wine vinegar.',
  'Spoon whipped goat\'s cheese generously over the wedges.',
  'Scatter radish slices and dill. Serve with lemon.',
]},

{id:10,name:'Butter Bean Salad with Herbs & Lemon',category:'Salads',difficulty:'easy',serves:4,time:'15 min',calories:320,mainIngredient:'Butter Beans',
ingredients:[
  {name:'Butter beans, rinsed',amount:800,unit:'g'},
  {name:'Red onion, thinly sliced',amount:1,unit:'small'},
  {name:'Cucumber, diced',amount:1,unit:'whole'},
  {name:'Cherry tomatoes, halved',amount:200,unit:'g'},
  {name:'Parsley, chopped',amount:1,unit:'handful'},
  {name:'Mint leaves, chopped',amount:1,unit:'handful'},
  {name:'Lemon juice',amount:30,unit:'ml'},
  {name:'Olive oil',amount:45,unit:'ml'},
],
steps:[
  'Combine butter beans, red onion, cucumber, tomatoes, parsley and mint in a large bowl.',
  'Whisk lemon juice and olive oil together.',
  'Pour dressing over salad, season well and toss to combine.',
]},

{id:11,name:'Caprese Salad',category:'Salads',difficulty:'easy',serves:4,time:'10 min',calories:260,mainIngredient:'Tomatoes',
ingredients:[
  {name:'Ripe tomatoes, sliced',amount:500,unit:'g'},
  {name:'Fresh mozzarella, sliced',amount:250,unit:'g'},
  {name:'Fresh basil leaves',amount:1,unit:'handful'},
  {name:'Extra virgin olive oil',amount:45,unit:'ml'},
  {name:'Balsamic vinegar',amount:15,unit:'ml'},
  {name:'Salt and pepper',amount:1,unit:'to taste'},
],
steps:[
  'Layer tomato and mozzarella slices alternately on a platter.',
  'Tuck basil leaves between the slices.',
  'Drizzle generously with olive oil and balsamic vinegar.',
  'Season with flaky salt and black pepper just before serving.',
]},

{id:12,name:'Fattoush',category:'Salads',difficulty:'easy',serves:2,time:'20 min',calories:340,mainIngredient:'Flatbread',
ingredients:[
  {name:'Lebanese flatbreads, quartered',amount:2,unit:'whole'},
  {name:'Olive oil',amount:95,unit:'ml'},
  {name:'Mixed herbs (mint, parsley, dill)',amount:3,unit:'handful'},
  {name:'Radishes, wedged',amount:4,unit:'whole'},
  {name:'Lebanese cucumbers, wedged',amount:3,unit:'whole'},
  {name:'Tomatoes, wedged',amount:4,unit:'whole'},
  {name:'Spring onions, sliced',amount:2,unit:'whole'},
  {name:'Gem lettuces, chopped',amount:2,unit:'whole'},
  {name:'Sumac',amount:15,unit:'g'},
  {name:'Pomegranate molasses',amount:15,unit:'ml'},
  {name:'Lemon juice',amount:30,unit:'ml'},
],
steps:[
  'Bake flatbread pieces at 180°C for 5 minutes until crisp.',
  'Mix herbs, radish, cucumber, tomato and spring onion in a bowl.',
  'Whisk sumac, pomegranate molasses, 80 ml olive oil and lemon juice into dressing.',
  'Dress salad vegetables and lettuce separately with the dressing.',
  'Toss crisped bread into the salad and pile onto the dressed lettuce to serve.',
]},

{id:13,name:'Greek Salad',category:'Salads',difficulty:'easy',serves:4,time:'10 min',calories:230,mainIngredient:'Tomatoes',
ingredients:[
  {name:'Tomatoes',amount:4,unit:'whole',prep:'chopped'},
  {name:'Cucumber',amount:1,unit:'whole',prep:'chopped'},
  {name:'Red onion',amount:1,unit:'whole',prep:'sliced'},
  {name:'Green capsicum',amount:1,unit:'whole',prep:'chopped'},
  {name:'Kalamata olives',amount:100,unit:'g'},
  {name:'Feta cheese',amount:150,unit:'g',prep:'cubed'},
  {name:'Olive oil',amount:45,unit:'ml'},
  {name:'Red wine vinegar',amount:15,unit:'ml'},
  {name:'Dried oregano',amount:5,unit:'g'},
],
steps:[
  'Combine tomatoes, cucumber, onion, capsicum, olives and feta in a large bowl.',
  'Whisk olive oil, vinegar and oregano together. Season.',
  'Pour dressing over salad and toss gently to combine.',
]},

{id:14,name:'The Big Greek Village Salad',category:'Salads',difficulty:'easy',serves:2,time:'20 min',calories:380,mainIngredient:'Lettuce',
ingredients:[
  {name:'Iceberg lettuce, halved',amount:1,unit:'whole'},
  {name:'Cucumber, cubed',amount:1,unit:'whole'},
  {name:'Tomato, cubed',amount:1,unit:'whole'},
  {name:'Olives, chopped',amount:75,unit:'g'},
  {name:'Olive oil',amount:60,unit:'ml'},
  {name:'Pomegranate molasses',amount:30,unit:'ml'},
  {name:'Za\'atar',amount:30,unit:'g'},
  {name:'Marinated feta',amount:100,unit:'g'},
  {name:'Greek yoghurt',amount:390,unit:'g'},
  {name:'Fresh basil',amount:0.5,unit:'bunch'},
  {name:'Garlic cloves',amount:2,unit:'cloves'},
  {name:'Lemon zest and juice',amount:1,unit:'lemon'},
],
steps:[
  'Blend yoghurt, basil, garlic, lemon zest and juice until smooth. Chill.',
  'Place lettuce halves cut-side up on a platter. Season generously.',
  'Spoon herbed yoghurt over the lettuce.',
  'Top with cucumber, tomato and olives.',
  'Drizzle with olive oil, pomegranate molasses and za\'atar. Scatter feta and serve with lemon.',
]},

{id:15,name:'Heirloom Tomato & Ricotta Salad',category:'Salads',difficulty:'medium',serves:4,time:'75 min',calories:280,mainIngredient:'Tomatoes',
ingredients:[
  {name:'Heirloom tomatoes',amount:1000,unit:'g'},
  {name:'Extra virgin olive oil',amount:30,unit:'ml'},
  {name:'Fresh basil or herb leaves',amount:1,unit:'handful'},
  {name:'Full-cream milk',amount:2000,unit:'ml'},
  {name:'Buttermilk',amount:250,unit:'ml'},
  {name:'Salt',amount:5,unit:'g'},
],
steps:[
  'Heat milk, buttermilk and salt in a pot until curds form — do not boil. Rest 10 minutes.',
  'Strain curds through a muslin-lined colander for 30 minutes. Squeeze gently. Set ricotta aside.',
  'Slice tomatoes, arrange on a platter, season and drizzle with olive oil.',
  'Spoon fresh ricotta over tomatoes, scatter herbs and drizzle with more oil. Serve with bread.',
]},

{id:16,name:'Panzanella (Tuscan Bread Salad)',category:'Salads',difficulty:'easy',serves:4,time:'20 min',calories:290,mainIngredient:'Tomatoes',
ingredients:[
  {name:'Ripe tomatoes, chopped',amount:500,unit:'g'},
  {name:'Cucumber, chopped',amount:1,unit:'whole'},
  {name:'Red capsicum, chopped',amount:1,unit:'whole'},
  {name:'Red onion, thinly sliced',amount:0.5,unit:'whole'},
  {name:'Stale bread, torn',amount:200,unit:'g'},
  {name:'Olive oil',amount:60,unit:'ml'},
  {name:'Red wine vinegar',amount:30,unit:'ml'},
  {name:'Fresh basil leaves',amount:1,unit:'handful'},
],
steps:[
  'Toss tomatoes, cucumber, capsicum, onion and torn bread in a large bowl.',
  'Whisk olive oil and vinegar together and pour over salad.',
  'Season generously and toss well.',
  'Let sit 15 minutes so the bread absorbs the juices.',
  'Scatter basil leaves before serving.',
]},

{id:17,name:'Buckwheat, Pomegranate & Roasted Carrot Tabbouleh',category:'Salads',difficulty:'medium',serves:4,time:'40 min',calories:310,mainIngredient:'Buckwheat',
ingredients:[
  {name:'Carrots, cut into batons',amount:4,unit:'whole'},
  {name:'Olive oil',amount:30,unit:'ml'},
  {name:'Buckwheat groats',amount:180,unit:'g'},
  {name:'Boiling water',amount:480,unit:'ml'},
  {name:'Pomegranate seeds',amount:1,unit:'pomegranate'},
  {name:'Parsley, chopped',amount:1,unit:'handful'},
  {name:'Mint, chopped',amount:1,unit:'handful'},
  {name:'Lemon juice',amount:30,unit:'ml'},
  {name:'Mixed seeds, toasted',amount:60,unit:'g'},
],
steps:[
  'Heat oven to 200°C. Toss carrots with 1 tbsp olive oil, roast 20–25 minutes until tender.',
  'Rinse buckwheat and cook in boiling salted water for 10 minutes. Drain and cool.',
  'Combine buckwheat, roasted carrots, pomegranate seeds, parsley, mint and lemon juice.',
  'Add remaining olive oil and toss well. Season to taste.',
  'Sprinkle with toasted seeds to serve.',
]},

{id:18,name:'Roast Beetroot Salad with Goat Cheese',category:'Salads',difficulty:'easy',serves:4,time:'70 min',calories:260,mainIngredient:'Beetroot',
ingredients:[
  {name:'Beetroot, scrubbed',amount:500,unit:'g'},
  {name:'Olive oil',amount:30,unit:'ml'},
  {name:'Goat cheese, crumbled',amount:100,unit:'g'},
  {name:'Walnuts, toasted',amount:50,unit:'g'},
  {name:'Rocket leaves',amount:100,unit:'g'},
  {name:'Balsamic vinegar',amount:15,unit:'ml'},
],
steps:[
  'Heat oven to 200°C. Wrap beetroot in foil, drizzle with oil, roast 45–60 minutes until tender.',
  'Cool, peel and slice the beetroot.',
  'Toss beetroot with rocket, balsamic vinegar, salt and pepper.',
  'Scatter crumbled goat cheese and toasted walnuts over the top.',
]},

{id:19,name:'Roast Pumpkin Salad with Feta & Pepitas',category:'Salads',difficulty:'easy',serves:4,time:'35 min',calories:290,mainIngredient:'Pumpkin',
ingredients:[
  {name:'Pumpkin, peeled and diced',amount:800,unit:'g'},
  {name:'Olive oil',amount:30,unit:'ml'},
  {name:'Feta, crumbled',amount:100,unit:'g'},
  {name:'Pepitas, toasted',amount:40,unit:'g'},
  {name:'Baby spinach or rocket',amount:100,unit:'g'},
  {name:'Balsamic vinegar',amount:15,unit:'ml'},
],
steps:[
  'Heat oven to 200°C. Toss pumpkin with olive oil, season. Roast 25 minutes until golden.',
  'Combine roasted pumpkin with spinach or rocket.',
  'Drizzle with balsamic vinegar, toss gently.',
  'Scatter feta and pepitas over the top. Serve warm or at room temperature.',
]},

{id:20,name:'Roasted Baby Carrot & Farro Salad with Gremolata',category:'Salads',difficulty:'medium',serves:2,time:'45 min',calories:480,mainIngredient:'Carrots',
ingredients:[
  {name:'Farro',amount:180,unit:'g'},
  {name:'Harissa paste',amount:15,unit:'g'},
  {name:'Olive oil',amount:30,unit:'ml'},
  {name:'Baby carrots (tops reserved)',amount:3,unit:'bunches'},
  {name:'Green goddess tahini sauce',amount:265,unit:'g'},
  {name:'Almonds, toasted and crushed',amount:80,unit:'g'},
  {name:'Fennel bulb, shaved',amount:1,unit:'small'},
  {name:'Avocados, wedged',amount:2,unit:'whole'},
  {name:'Mint',amount:1,unit:'handful'},
  {name:'Carrot tops, chopped',amount:2,unit:'handful'},
  {name:'Capers, chopped',amount:30,unit:'g'},
  {name:'Garlic clove, crushed',amount:1,unit:'clove'},
  {name:'Lemon zest and juice',amount:1,unit:'lemon'},
  {name:'Cumin',amount:5,unit:'g'},
],
steps:[
  'Cook farro in salted water 15 minutes. Drain and cool.',
  'Toss carrots with harissa, oil and salt. Roast at 220°C for 15 minutes.',
  'Make gremolata: mix carrot tops, capers, garlic, lemon zest and juice, olive oil, cumin and chilli flakes.',
  'Spread tahini on a plate. Pile farro with almonds, shaved fennel and gremolata.',
  'Top with roasted carrots, avocado wedges, mint and extra gremolata.',
]},

{id:21,name:'Smoked Trout Salad with Horseradish Cream',category:'Salads',difficulty:'easy',serves:2,time:'15 min',calories:310,mainIngredient:'Smoked Trout',
ingredients:[
  {name:'Smoked trout fillet, flaked',amount:200,unit:'g'},
  {name:'Baby cos lettuce leaves',amount:1,unit:'whole'},
  {name:'Cucumber, sliced',amount:1,unit:'whole'},
  {name:'Avocado, sliced',amount:1,unit:'whole'},
  {name:'Red onion, finely sliced',amount:0.5,unit:'whole'},
  {name:'Capers',amount:30,unit:'g'},
  {name:'Dill sprigs',amount:1,unit:'handful'},
  {name:'Sour cream',amount:100,unit:'g'},
  {name:'Prepared horseradish',amount:15,unit:'g'},
  {name:'Lemon juice',amount:15,unit:'ml'},
],
steps:[
  'Mix sour cream, horseradish and lemon juice together for the dressing. Season.',
  'Arrange cos lettuce, cucumber, avocado and red onion on a platter.',
  'Scatter flaked smoked trout, capers and dill over the top.',
  'Drizzle with horseradish cream to serve.',
]},

{id:22,name:'Spicy Watermelon Salad',category:'Salads',difficulty:'easy',serves:4,time:'15 min',calories:140,mainIngredient:'Watermelon',
ingredients:[
  {name:'Seedless watermelon, cubed',amount:1000,unit:'g'},
  {name:'Lebanese cucumber, sliced',amount:1,unit:'whole'},
  {name:'Cherry tomatoes, halved',amount:250,unit:'g'},
  {name:'Fish sauce',amount:30,unit:'ml'},
  {name:'Sriracha hot sauce',amount:30,unit:'ml'},
  {name:'Soft brown sugar',amount:15,unit:'g'},
  {name:'Lime juice',amount:60,unit:'ml'},
  {name:'Crispy fried shallots',amount:30,unit:'g'},
  {name:'Coriander, mint and Thai basil',amount:1,unit:'handful'},
],
steps:[
  'Combine watermelon, cucumber and cherry tomatoes in a large bowl.',
  'Whisk fish sauce, sriracha, brown sugar and lime juice into a dressing.',
  'Pour dressing over salad and toss well.',
  'Scatter fried shallots, fried garlic and fresh herbs on top. Serve immediately.',
]},

{id:23,name:'Warm Lentil Salad with Goat\'s Cheese & Walnuts',category:'Salads',difficulty:'easy',serves:4,time:'30 min',calories:380,mainIngredient:'Lentils',
ingredients:[
  {name:'Puy lentils',amount:250,unit:'g'},
  {name:'Bay leaf',amount:1,unit:'whole'},
  {name:'Onion, halved',amount:1,unit:'whole'},
  {name:'Olive oil',amount:30,unit:'ml'},
  {name:'Red wine vinegar',amount:30,unit:'ml'},
  {name:'Goat\'s cheese, crumbled',amount:100,unit:'g'},
  {name:'Walnuts, toasted and chopped',amount:60,unit:'g'},
  {name:'Parsley, chopped',amount:1,unit:'handful'},
],
steps:[
  'Simmer lentils with bay leaf and onion halves in water for 20–25 minutes until tender. Drain, discard onion and bay leaf.',
  'Toss warm lentils with olive oil, vinegar, salt and pepper.',
  'Scatter crumbled goat\'s cheese, walnuts and parsley over the top. Serve warm.',
]},

{id:24,name:'Marinated Beetroots, Whipped Feta, Lentils & Za\'atar',category:'Salads',difficulty:'medium',serves:2,time:'1 hr 20 min',calories:420,mainIngredient:'Beetroot',
ingredients:[
  {name:'Beetroots',amount:5,unit:'whole'},
  {name:'Red wine vinegar',amount:80,unit:'ml'},
  {name:'Sugar',amount:30,unit:'g'},
  {name:'Lentils, rinsed',amount:400,unit:'g'},
  {name:'Fennel bulb, shaved',amount:1,unit:'small'},
  {name:'Rocket',amount:1,unit:'handful'},
  {name:'Almonds, toasted',amount:45,unit:'g'},
  {name:'Mint and dill',amount:1,unit:'handful'},
  {name:'Za\'atar',amount:5,unit:'g'},
  {name:'Olive oil',amount:80,unit:'ml'},
  {name:'Pomegranate molasses',amount:15,unit:'ml'},
  {name:'Soft feta',amount:150,unit:'g'},
  {name:'Greek yoghurt',amount:95,unit:'g'},
  {name:'Lemon juice',amount:15,unit:'ml'},
],
steps:[
  'Boil beetroots in salted vinegar water until soft, about 1 hour. Peel and wedge.',
  'Blend feta with yoghurt, lemon juice and 1 tbsp olive oil until fluffy.',
  'Toss beetroot with cooked lentils, fennel, rocket, almonds, mint and dill.',
  'Whisk remaining olive oil, vinegar, za\'atar and pomegranate molasses into a dressing. Toss through.',
  'Spread whipped feta on a plate, pile salad over and scatter extra za\'atar.',
]},

{id:25,name:'Tuscan Kale Salad with Fennel, Radish & Ricotta Salata',category:'Salads',difficulty:'medium',serves:2,time:'20 min',calories:280,mainIngredient:'Kale',
ingredients:[
  {name:'Tuscan kale, shredded',amount:2,unit:'bunches'},
  {name:'Red wine vinegar',amount:30,unit:'ml'},
  {name:'Lemon juice',amount:22,unit:'ml'},
  {name:'Radishes, thinly sliced',amount:6,unit:'whole'},
  {name:'Fennel bulb, shaved',amount:1,unit:'whole'},
  {name:'Garlic croutons, crushed',amount:1,unit:'handful'},
  {name:'Ricotta salata, shaved',amount:55,unit:'g'},
  {name:'Olive oil',amount:45,unit:'ml'},
],
steps:[
  'Massage kale with olive oil, vinegar, lemon juice and salt until softened, about 2 minutes.',
  'Add shaved radish and fennel and toss through.',
  'Crush croutons roughly and mix into the salad.',
  'Shave ricotta salata over the top and toss gently before serving.',
]},

{id:26,name:'Wild Rice, Pickled Zucchini, Dukkah & Mozzarella Salad',category:'Salads',difficulty:'medium',serves:2,time:'45 min',calories:520,mainIngredient:'Wild Rice',
ingredients:[
  {name:'Cooked wild rice',amount:150,unit:'g'},
  {name:'Mint leaves',amount:1,unit:'handful'},
  {name:'Mozzarella',amount:300,unit:'g'},
  {name:'White wine vinegar',amount:150,unit:'ml'},
  {name:'Honey',amount:30,unit:'ml'},
  {name:'Red chilli, minced',amount:0.5,unit:'whole'},
  {name:'Zucchini, diced',amount:2,unit:'cups'},
  {name:'Hazelnuts, chopped',amount:130,unit:'g'},
  {name:'Sesame seeds',amount:100,unit:'g'},
  {name:'Coriander seeds',amount:15,unit:'g'},
  {name:'Cumin',amount:15,unit:'g'},
  {name:'Lemon zest',amount:1,unit:'lemon'},
  {name:'Olive oil',amount:300,unit:'ml'},
  {name:'Bread, cubed',amount:0.5,unit:'loaf'},
],
steps:[
  'Heat vinegar with honey, chilli, cloves and a cinnamon stick for 5 minutes. Pour over diced zucchini and steep until cool.',
  'Mix dukkah spices (hazelnuts, sesame, coriander seeds, cumin, lemon zest, pepper, salt). Coat bread cubes with oil and 5 tbsp spice mix. Bake at 180°C until crisp, 15–20 minutes.',
  'Drain pickled zucchini and toss with cooked wild rice, bread crumbs and mint.',
  'Tear mozzarella over the top and sprinkle with more dukkah.',
]},

{id:27,name:'Potato & Pea Salad with Horseradish Ranch',category:'Salads',difficulty:'easy',serves:2,time:'30 min',calories:400,mainIngredient:'Potatoes',
ingredients:[
  {name:'Chat potatoes',amount:1000,unit:'g'},
  {name:'Olive oil',amount:30,unit:'ml'},
  {name:'Leek, sliced',amount:0.5,unit:'small'},
  {name:'Frozen peas, thawed',amount:140,unit:'g'},
  {name:'Mint, chopped',amount:1,unit:'handful'},
  {name:'Dill, chopped',amount:1,unit:'handful'},
  {name:'Baby capers, rinsed',amount:50,unit:'g'},
  {name:'Pea sprouts',amount:1,unit:'handful'},
  {name:'Greek yoghurt',amount:130,unit:'g'},
  {name:'Buttermilk',amount:60,unit:'ml'},
  {name:'Garlic clove, crushed',amount:1,unit:'clove'},
  {name:'White wine vinegar',amount:15,unit:'ml'},
  {name:'Lemon juice',amount:30,unit:'ml'},
  {name:'Horseradish',amount:30,unit:'g'},
],
steps:[
  'Whisk all dressing ingredients (yoghurt, buttermilk, garlic, vinegar, lemon juice, horseradish) together. Season and chill.',
  'Boil potatoes in salted water 15 minutes until tender. Cool and halve.',
  'Fry sliced leek in oil with a pinch of salt for 3 minutes until softened.',
  'Toss potatoes, leek, peas, herbs and capers with dressing until well coated.',
  'Top with pea sprouts to serve.',
]},

{id:28,name:'Grilled Asparagus & Butter Bean Salad',category:'Salads',difficulty:'easy',serves:2,time:'15 min',calories:330,mainIngredient:'Asparagus',
ingredients:[
  {name:'Asparagus, trimmed',amount:2,unit:'bunches'},
  {name:'Olive oil',amount:75,unit:'ml'},
  {name:'Butter beans, rinsed',amount:400,unit:'g'},
  {name:'Capers',amount:30,unit:'g'},
  {name:'Spring onions, sliced',amount:2,unit:'whole'},
  {name:'Dill',amount:1,unit:'handful'},
  {name:'Parsley',amount:1,unit:'handful'},
  {name:'Sherry vinegar',amount:30,unit:'ml'},
  {name:'Chilli in oil',amount:15,unit:'ml'},
  {name:'Lemon zest',amount:1,unit:'lemon'},
],
steps:[
  'Toss asparagus with 1 tbsp oil, salt and pepper. Grill 2 minutes until lightly charred.',
  'Combine charred asparagus with butter beans, capers, spring onions, dill and parsley.',
  'Dress with sherry vinegar, remaining olive oil and chilli in oil. Season well.',
  'Finish with lemon zest and serve.',
]},

{id:29,name:'Grilled Asparagus with Lemon & Parmesan',category:'Salads',difficulty:'easy',serves:2,time:'10 min',calories:150,mainIngredient:'Asparagus',
ingredients:[
  {name:'Asparagus, trimmed',amount:1,unit:'bunch'},
  {name:'Olive oil',amount:30,unit:'ml'},
  {name:'Lemon juice',amount:15,unit:'ml'},
  {name:'Parmesan, shaved',amount:30,unit:'g'},
],
steps:[
  'Toss asparagus with olive oil, salt and pepper.',
  'Grill 3–4 minutes until tender and lightly charred.',
  'Squeeze lemon juice over the top and scatter shaved parmesan to serve.',
]},

{id:30,name:'Kale, Chickpea, Fennel & Date Salad',category:'Salads',difficulty:'easy',serves:2,time:'20 min',calories:450,mainIngredient:'Kale',
ingredients:[
  {name:'Kale leaves, chopped',amount:3,unit:'whole'},
  {name:'Cooked chickpeas',amount:180,unit:'g'},
  {name:'Fennel bulb, finely sliced',amount:1,unit:'whole'},
  {name:'Mint leaves',amount:1,unit:'handful'},
  {name:'Parsley leaves',amount:1,unit:'handful'},
  {name:'Oranges, segmented',amount:2,unit:'whole'},
  {name:'Olive oil',amount:100,unit:'ml'},
  {name:'Orange juice',amount:60,unit:'ml'},
  {name:'Dates, quartered',amount:6,unit:'whole'},
  {name:'Walnuts (optional)',amount:30,unit:'g'},
],
steps:[
  'Massage kale with half the olive oil and some of the orange juice until softened.',
  'Add chickpeas, fennel, herbs, dates and orange segments. Toss well.',
  'Drizzle with remaining oil and orange juice. Season.',
  'Scatter walnuts if using and serve.',
]},

{id:31,name:'Chickpea & Date Salad with Citrus Dressing',category:'Salads',difficulty:'easy',serves:2,time:'15 min',calories:420,mainIngredient:'Chickpeas',
ingredients:[
  {name:'Chickpeas',amount:200,unit:'g'},
  {name:'Fennel bulb, shaved',amount:1,unit:'whole'},
  {name:'Mint and parsley',amount:1,unit:'handful'},
  {name:'Oranges, segmented',amount:2,unit:'whole'},
  {name:'Olive oil',amount:100,unit:'ml'},
  {name:'Orange juice',amount:60,unit:'ml'},
  {name:'Dates, sliced',amount:6,unit:'whole'},
  {name:'Walnuts (optional)',amount:30,unit:'g'},
],
steps:[
  'Whisk olive oil and orange juice together for the dressing.',
  'Toss chickpeas, fennel, herbs, dates and orange segments with the dressing.',
  'Scatter walnuts to serve.',
]},

{id:32,name:'Chickpea, Tomato & Herb Salad with Pomegranate Dressing',category:'Salads',difficulty:'easy',serves:2,time:'20 min',calories:480,mainIngredient:'Chickpeas',
ingredients:[
  {name:'Chickpeas, rinsed',amount:400,unit:'g'},
  {name:'Tomatoes, halved and grated',amount:2,unit:'whole'},
  {name:'Olive oil',amount:80,unit:'ml'},
  {name:'Lemon juice',amount:30,unit:'ml'},
  {name:'Garlic cloves, grated',amount:2,unit:'cloves'},
  {name:'Pomegranate molasses',amount:30,unit:'ml'},
  {name:'Sumac',amount:10,unit:'g'},
  {name:'Tahini',amount:90,unit:'g'},
  {name:'Dill and mint',amount:1,unit:'handful'},
  {name:'Cucumbers, chopped',amount:2,unit:'whole'},
  {name:'Avocados, wedged',amount:2,unit:'whole'},
  {name:'Kalamata olives',amount:50,unit:'g'},
],
steps:[
  'If using canned chickpeas, simmer with a splash of their liquid for 3 minutes until creamy.',
  'Mix grated tomato, chickpeas, olive oil, lemon juice, garlic, half the pomegranate molasses and sumac.',
  'Pile into a bowl. Drizzle tahini and remaining molasses over the top. Sprinkle sumac.',
  'Top with herbs, cucumber, avocado wedges and olives. Drizzle with more oil.',
]},

{id:33,name:'Quinoa Tabbouleh with Pomegranate & Mint',category:'Salads',difficulty:'easy',serves:2,time:'20 min',calories:340,mainIngredient:'Quinoa',
ingredients:[
  {name:'Quinoa, cooked',amount:120,unit:'g'},
  {name:'Tomatoes, diced',amount:2,unit:'whole'},
  {name:'Cucumber, diced',amount:1,unit:'whole'},
  {name:'Spring onions, sliced',amount:3,unit:'whole'},
  {name:'Parsley, chopped',amount:1,unit:'handful'},
  {name:'Mint, chopped',amount:1,unit:'handful'},
  {name:'Pomegranate seeds',amount:0.5,unit:'pomegranate'},
  {name:'Lemon juice',amount:30,unit:'ml'},
  {name:'Olive oil',amount:60,unit:'ml'},
],
steps:[
  'Cook quinoa, rinse and cool completely.',
  'Toss with tomatoes, cucumber, spring onions, parsley, mint and pomegranate seeds.',
  'Dress with lemon juice and olive oil. Season with salt and pepper.',
]},

{id:34,name:'Warm Farro Salad with Roasted Capsicum & Herbs',category:'Salads',difficulty:'easy',serves:2,time:'30 min',calories:360,mainIngredient:'Farro',
ingredients:[
  {name:'Farro, cooked',amount:150,unit:'g'},
  {name:'Roasted capsicum, sliced',amount:1,unit:'whole'},
  {name:'Cucumber, diced',amount:1,unit:'whole'},
  {name:'Tomato, diced',amount:1,unit:'whole'},
  {name:'Parsley and mint',amount:1,unit:'handful'},
  {name:'Lemon juice',amount:30,unit:'ml'},
  {name:'Olive oil',amount:60,unit:'ml'},
],
steps:[
  'Cook farro in salted water, drain and cool slightly.',
  'Toss with roasted capsicum, cucumber, tomato and herbs.',
  'Dress with lemon juice and olive oil. Season generously.',
]},

// ── SOUPS ────────────────────────────────────────────────
{id:35,name:'Gazpacho (Chilled Tomato Soup)',category:'Soups',difficulty:'easy',serves:4,time:'15 min + 2 hr chill',calories:120,mainIngredient:'Tomatoes',
ingredients:[
  {name:'Ripe tomatoes, chopped',amount:1000,unit:'g'},
  {name:'Cucumber, chopped',amount:1,unit:'whole'},
  {name:'Red capsicum, chopped',amount:1,unit:'whole'},
  {name:'Red onion, chopped',amount:1,unit:'small'},
  {name:'Garlic cloves, chopped',amount:2,unit:'cloves'},
  {name:'Olive oil',amount:45,unit:'ml'},
  {name:'Red wine vinegar',amount:30,unit:'ml'},
  {name:'Stale bread, soaked in water',amount:2,unit:'slices'},
],
steps:[
  'Blend tomatoes, cucumber, capsicum, onion, garlic, olive oil, vinegar and soaked bread until very smooth.',
  'Season well with salt and pepper.',
  'Chill for at least 2 hours before serving.',
  'Serve cold with a drizzle of olive oil.',
]},

{id:36,name:'Minestrone Soup',category:'Soups',difficulty:'easy',serves:4,time:'35 min',calories:280,mainIngredient:'Vegetables',
ingredients:[
  {name:'Olive oil',amount:30,unit:'ml'},
  {name:'Onion, chopped',amount:1,unit:'whole'},
  {name:'Carrots, diced',amount:2,unit:'whole'},
  {name:'Celery sticks, diced',amount:2,unit:'stalks'},
  {name:'Garlic cloves, chopped',amount:2,unit:'cloves'},
  {name:'Zucchini, diced',amount:1,unit:'whole'},
  {name:'Tinned chopped tomatoes',amount:400,unit:'g'},
  {name:'Vegetable stock',amount:1000,unit:'ml'},
  {name:'Cannellini beans, drained',amount:400,unit:'g'},
  {name:'Small pasta (ditalini)',amount:100,unit:'g'},
  {name:'Parsley, chopped',amount:1,unit:'handful'},
],
steps:[
  'Heat oil in a large pot. Sauté onion, carrots, celery and garlic until soft, about 8 minutes.',
  'Add zucchini, tomatoes and stock. Simmer 15 minutes.',
  'Stir in cannellini beans and pasta. Cook until pasta is tender.',
  'Season well and scatter parsley before serving.',
]},

{id:37,name:'Minestrone Verde with Poached Fish',category:'Soups',difficulty:'medium',serves:2,time:'40 min',calories:380,mainIngredient:'Fish',
ingredients:[
  {name:'Olive oil',amount:60,unit:'ml'},
  {name:'Leek, sliced',amount:0.5,unit:'whole'},
  {name:'Fennel bulb, sliced (fronds kept)',amount:1,unit:'whole'},
  {name:'Garlic cloves, sliced',amount:3,unit:'cloves'},
  {name:'Zucchinis, sliced',amount:4,unit:'whole'},
  {name:'Vegetable or chicken stock',amount:2000,unit:'ml'},
  {name:'Cavolo nero, sliced',amount:1,unit:'handful'},
  {name:'Cannellini beans, rinsed',amount:400,unit:'g'},
  {name:'Asparagus or sugar snaps',amount:1,unit:'bunch'},
  {name:'White fish (ling, snapper), cubed',amount:300,unit:'g'},
  {name:'Peas',amount:140,unit:'g'},
  {name:'Salmoriglio',amount:80,unit:'ml'},
  {name:'Lemon zest and juice',amount:1,unit:'lemon'},
],
steps:[
  'Fry leek, fennel and garlic in oil with a pinch of salt for 8 minutes. Add zucchini, cook 5 minutes.',
  'Add stock and simmer 15 minutes. Stir in cavolo nero.',
  'Add cannellini beans, asparagus and fish. Cover and poach for 3 minutes.',
  'Crush peas and mix with salmoriglio, lemon zest and juice, salt and pepper.',
  'Ladle soup into bowls and spoon pea pesto over. Top with fennel fronds and chilli flakes.',
]},

{id:38,name:'Minestrone Verde (Vegetarian)',category:'Soups',difficulty:'medium',serves:2,time:'35 min',calories:290,mainIngredient:'Vegetables',
ingredients:[
  {name:'Olive oil',amount:60,unit:'ml'},
  {name:'Leek, sliced',amount:0.5,unit:'whole'},
  {name:'Fennel bulb, sliced',amount:1,unit:'whole'},
  {name:'Garlic cloves, sliced',amount:3,unit:'cloves'},
  {name:'Zucchinis, sliced',amount:4,unit:'whole'},
  {name:'Vegetable stock',amount:2000,unit:'ml'},
  {name:'Cavolo nero, sliced',amount:1,unit:'handful'},
  {name:'Cannellini beans, rinsed',amount:400,unit:'g'},
  {name:'Asparagus or sugar snaps',amount:1,unit:'bunch'},
  {name:'Peas',amount:140,unit:'g'},
  {name:'Lemon zest and juice',amount:1,unit:'lemon'},
  {name:'Salmoriglio (optional)',amount:80,unit:'ml'},
],
steps:[
  'Fry leek, fennel and garlic with salt in oil for 8 minutes. Add zucchini, cook 5 minutes.',
  'Add stock and simmer 15 minutes. Stir in cavolo nero.',
  'Add cannellini beans, peas and asparagus. Cook until just tender.',
  'Season with lemon zest, lemon juice, chilli flakes and olive oil or salmoriglio.',
]},

{id:39,name:'Prawn Laksa',category:'Soups',difficulty:'medium',serves:4,time:'30 min',calories:420,mainIngredient:'Prawns',
ingredients:[
  {name:'Vegetable oil',amount:30,unit:'ml'},
  {name:'Onion, chopped',amount:1,unit:'whole'},
  {name:'Garlic cloves, chopped',amount:2,unit:'cloves'},
  {name:'Fresh ginger, grated',amount:15,unit:'g'},
  {name:'Laksa paste',amount:30,unit:'g'},
  {name:'Chicken stock',amount:750,unit:'ml'},
  {name:'Coconut milk',amount:400,unit:'ml'},
  {name:'Rice noodles',amount:200,unit:'g'},
  {name:'Prawns, peeled',amount:300,unit:'g'},
  {name:'Bean sprouts, coriander and lime',amount:1,unit:'to serve'},
],
steps:[
  'Heat oil in a pot. Fry onion, garlic and ginger until soft, about 4 minutes.',
  'Stir in laksa paste and cook 1 minute until fragrant.',
  'Add stock and coconut milk. Simmer 10 minutes.',
  'Cook rice noodles separately and divide into bowls.',
  'Add prawns to soup and cook until pink, 2–3 minutes. Pour over noodles and serve with sprouts, coriander and lime.',
]},

{id:40,name:'Roast Pumpkin Soup with Coconut & Chilli',category:'Soups',difficulty:'easy',serves:4,time:'45 min',calories:260,mainIngredient:'Pumpkin',
ingredients:[
  {name:'Pumpkin, peeled and diced',amount:1000,unit:'g'},
  {name:'Olive oil',amount:30,unit:'ml'},
  {name:'Onion, chopped',amount:1,unit:'whole'},
  {name:'Garlic cloves, chopped',amount:2,unit:'cloves'},
  {name:'Red chilli, chopped',amount:1,unit:'whole'},
  {name:'Vegetable stock',amount:750,unit:'ml'},
  {name:'Coconut milk',amount:400,unit:'ml'},
  {name:'Lime juice',amount:30,unit:'ml'},
],
steps:[
  'Heat oven to 200°C. Toss pumpkin with olive oil, roast 25 minutes until tender.',
  'Sauté onion, garlic and chilli in a pot until soft.',
  'Add roasted pumpkin, stock and coconut milk. Simmer 10 minutes.',
  'Blend until smooth. Stir in lime juice and season to taste. Serve hot.',
]},

{id:41,name:'Seafood Chowder',category:'Soups',difficulty:'medium',serves:4,time:'45 min',calories:380,mainIngredient:'Seafood',
ingredients:[
  {name:'Butter',amount:30,unit:'g'},
  {name:'Onion, chopped',amount:1,unit:'whole'},
  {name:'Celery sticks, chopped',amount:2,unit:'stalks'},
  {name:'Carrots, diced',amount:2,unit:'whole'},
  {name:'Potatoes, diced',amount:2,unit:'whole'},
  {name:'Plain flour',amount:30,unit:'g'},
  {name:'Fish stock',amount:750,unit:'ml'},
  {name:'Milk',amount:300,unit:'ml'},
  {name:'White fish fillets, cubed',amount:200,unit:'g'},
  {name:'Prawns, peeled',amount:200,unit:'g'},
  {name:'Mussels, cleaned',amount:200,unit:'g'},
  {name:'Parsley, chopped',amount:1,unit:'handful'},
],
steps:[
  'Melt butter in a pot. Cook onion, celery and carrots until soft. Stir in flour.',
  'Gradually add stock and milk, stirring until smooth. Simmer 10 minutes.',
  'Add potatoes and cook until tender, about 10 minutes.',
  'Stir in fish, prawns and mussels. Cook until seafood is just done, about 5 minutes.',
  'Season and scatter parsley before serving.',
]},

{id:42,name:'Sicilian Fish Soup',category:'Soups',difficulty:'medium',serves:4,time:'50 min',calories:310,mainIngredient:'Fish',
ingredients:[
  {name:'Red onion',amount:1,unit:'whole'},
  {name:'Celery sticks',amount:2,unit:'stalks'},
  {name:'Fennel bulb',amount:0.5,unit:'small'},
  {name:'Garlic cloves',amount:2,unit:'cloves'},
  {name:'Red chilli, deseeded',amount:1,unit:'whole'},
  {name:'Olive oil',amount:30,unit:'ml'},
  {name:'Dry white wine',amount:150,unit:'ml'},
  {name:'Chopped plum tomatoes or passata',amount:800,unit:'g'},
  {name:'Butternut squash, grated',amount:0.5,unit:'whole'},
  {name:'Fish stock',amount:500,unit:'ml'},
  {name:'Salmon fillet, skinned',amount:200,unit:'g'},
  {name:'Halibut fillet, skinned',amount:300,unit:'g'},
  {name:'Raw peeled prawns',amount:12,unit:'whole'},
  {name:'Lemon juice',amount:15,unit:'ml'},
  {name:'Flat-leaf parsley, chopped',amount:1,unit:'handful'},
],
steps:[
  'Finely chop onion, celery, fennel, garlic and chilli. Heat oil in a large pan and sweat vegetables gently until soft.',
  'Add wine, tomatoes, grated squash and stock. Bring to the boil, cover and simmer 30 minutes. Season.',
  'Roughly chop salmon and halibut, add to the pan with prawns. Cover and simmer 10 minutes.',
  'Taste and season with salt, pepper and lemon juice.',
  'Serve drizzled with olive oil and scattered with parsley.',
]},

]; // end of first batch — continued in recipes2.js
