// ── SIDES ────────────────────────────────────────────────
const RECIPES3 = [

{id:79,name:'Charred Corn with Lime & Feta',category:'Sides',difficulty:'easy',serves:2,time:'15 min',calories:180,mainIngredient:'Corn',
ingredients:[
  {name:'Fresh corn cobs',amount:2,unit:'whole'},
  {name:'Olive oil',amount:15,unit:'ml'},
  {name:'Feta',prep:'crumbled',amount:40,unit:'g'},
  {name:'Lime zest and juice',amount:1,unit:'lime'},
  {name:'Coriander',prep:'chopped',amount:1,unit:'handful'},
],
steps:[
  'Heat a barbecue or grill pan until very hot.',
  'Rub corn with olive oil and grill 10 minutes, turning until charred all over.',
  'Slice kernels off the cob into a bowl.',
  'Toss with lime zest, lime juice, crumbled feta and coriander. Season and serve.',
]},

{id:80,name:'Braised Sweet Corn with Chilli, Feta & Lime',category:'Sides',difficulty:'medium',serves:4,time:'40 min',calories:160,mainIngredient:'Corn',
ingredients:[
  {name:'Corn',prep:'kernels shaved',amount:6,unit:'whole'},
  {name:'Olive oil',amount:45,unit:'ml'},
  {name:'Chillies',prep:'minced',amount:2,unit:'whole'},
  {name:'Shallot',prep:'minced',amount:1,unit:'whole'},
  {name:'Feta',prep:'crumbled',amount:70,unit:'g'},
  {name:'Lime juice',amount:30,unit:'ml'},
  {name:'Coriander leaves',amount:1,unit:'handful'},
],
steps:[
  'Simmer corn cobs in salted water for 20–30 minutes. Strain, reserving 120 ml corn stock.',
  'Fry chilli and shallot in oil for 3 minutes.',
  'Add kernels, corn stock and half the feta. Cook 2–3 minutes until slightly thickened.',
  'Stir in lime juice and season. Serve topped with remaining feta and coriander.',
]},

{id:81,name:'Garlic Green Beans',category:'Sides',difficulty:'easy',serves:4,time:'10 min',calories:80,mainIngredient:'Green Beans',
ingredients:[
  {name:'Green beans',prep:'trimmed',amount:300,unit:'g'},
  {name:'Olive oil',amount:30,unit:'ml'},
  {name:'Garlic cloves',prep:'thinly sliced',amount:2,unit:'cloves'},
],
steps:[
  'Blanch beans in boiling salted water for 2 minutes. Drain.',
  'Heat olive oil in a pan, add garlic and cook 30 seconds.',
  'Add beans and toss until coated and just tender. Season and serve.',
]},

{id:82,name:'Honey-Glazed Carrots',category:'Sides',difficulty:'easy',serves:4,time:'30 min',calories:130,mainIngredient:'Carrots',
ingredients:[
  {name:'Carrots',prep:'peeled and halved lengthways',amount:500,unit:'g'},
  {name:'Olive oil',amount:30,unit:'ml'},
  {name:'Honey',amount:30,unit:'ml'},
],
steps:[
  'Heat oven to 200°C. Place carrots on a baking tray.',
  'Drizzle with olive oil and honey, season well.',
  'Roast 25–30 minutes until tender and caramelised.',
]},

{id:83,name:'Potato Gratin',category:'Sides',difficulty:'medium',serves:4,time:'65 min',calories:420,mainIngredient:'Potatoes',
ingredients:[
  {name:'Potatoes',prep:'thinly sliced',amount:1000,unit:'g'},
  {name:'Cream',amount:300,unit:'ml'},
  {name:'Garlic cloves',prep:'crushed',amount:2,unit:'cloves'},
  {name:'Gruyère or cheddar, grated',amount:100,unit:'g'},
  {name:'Fresh thyme leaves',amount:5,unit:'g'},
],
steps:[
  'Heat oven to 180°C. Rub a baking dish with garlic.',
  'Layer potato slices in the dish, seasoning each layer with salt, pepper and some cheese.',
  'Pour cream over the top and finish with remaining cheese.',
  'Bake for 1 hour until golden on top and tender throughout.',
]},

{id:84,name:'Roasted Brussels Sprouts with Bacon',category:'Sides',difficulty:'easy',serves:4,time:'30 min',calories:160,mainIngredient:'Brussels Sprouts',
ingredients:[
  {name:'Brussels sprouts',prep:'halved',amount:400,unit:'g'},
  {name:'Streaky bacon',prep:'chopped',amount:100,unit:'g'},
  {name:'Olive oil',amount:30,unit:'ml'},
],
steps:[
  'Heat oven to 200°C.',
  'Toss brussels sprouts and bacon with olive oil, salt and pepper.',
  'Spread on a baking tray and roast 20–25 minutes until crisp and golden.',
]},

{id:85,name:'Roasted Sweet Potato with Cumin & Yoghurt',category:'Sides',difficulty:'easy',serves:4,time:'35 min',calories:220,mainIngredient:'Sweet Potato',
ingredients:[
  {name:'Large sweet potatoes, cut into wedges',amount:2,unit:'whole'},
  {name:'Olive oil',amount:30,unit:'ml'},
  {name:'Ground cumin',amount:5,unit:'g'},
  {name:'Greek yoghurt',amount:200,unit:'g'},
  {name:'Lemon juice',amount:15,unit:'ml'},
],
steps:[
  'Heat oven to 200°C. Toss sweet potato with olive oil, cumin, salt and pepper.',
  'Roast 25–30 minutes until golden and tender.',
  'Mix yoghurt with lemon juice. Dollop over sweet potato to serve.',
]},

{id:86,name:'Roasted Sweet Potato with Chickpeas & Tahini',category:'Sides',difficulty:'easy',serves:2,time:'45 min',calories:380,mainIngredient:'Sweet Potato',
ingredients:[
  {name:'Medium sweet potatoes, halved',amount:2,unit:'whole'},
  {name:'Olive oil',amount:15,unit:'ml'},
  {name:'Chickpeas',prep:'rinsed',amount:200,unit:'g'},
  {name:'Ground cumin',amount:5,unit:'g'},
  {name:'Smoked paprika',amount:2,unit:'g'},
  {name:'Garlicky whipped tahini',amount:30,unit:'g'},
  {name:'Lemon juice',amount:15,unit:'ml'},
  {name:'Parsley',amount:1,unit:'handful'},
],
steps:[
  'Roast sweet potatoes at 200°C for 30–40 minutes until very tender.',
  'Toss chickpeas with oil, cumin and paprika. Roast on a separate tray for 15 minutes.',
  'Thin tahini with lemon juice and a little water.',
  'Top sweet potatoes with spiced chickpeas, drizzle tahini and scatter parsley.',
]},

{id:87,name:'Charred Broccoli with Lemon & Almonds',category:'Sides',difficulty:'easy',serves:4,time:'15 min',calories:120,mainIngredient:'Broccoli',
ingredients:[
  {name:'Broccoli',prep:'cut into florets',amount:2,unit:'whole heads'},
  {name:'Olive oil',amount:30,unit:'ml'},
  {name:'Lemon zest and juice',amount:1,unit:'lemon'},
  {name:'Toasted almonds',prep:'chopped',amount:40,unit:'g'},
],
steps:[
  'Toss broccoli florets with olive oil, salt and pepper.',
  'Grill or cook in a hot pan 5–6 minutes until charred and just tender.',
  'Squeeze lemon juice over, scatter zest and chopped toasted almonds.',
]},

{id:88,name:'Grilled Eggplant with Miso Dressing',category:'Sides',difficulty:'easy',serves:4,time:'25 min',calories:140,mainIngredient:'Eggplant',
ingredients:[
  {name:'Large eggplants, halved lengthways',amount:2,unit:'whole'},
  {name:'Olive oil',amount:30,unit:'ml'},
  {name:'White miso paste',amount:30,unit:'g'},
  {name:'Mirin',amount:15,unit:'ml'},
  {name:'Rice vinegar',amount:15,unit:'ml'},
  {name:'Sesame oil',amount:5,unit:'ml'},
],
steps:[
  'Heat barbecue or grill pan. Brush eggplant with olive oil.',
  'Grill cut-side down until charred, then turn and cook until tender throughout.',
  'Mix miso, mirin, rice vinegar and sesame oil into a glaze.',
  'Brush glaze over eggplant and cook 2 minutes more.',
]},

{id:89,name:'Roasted Eggplant with Pomegranate & Yoghurt',category:'Sides',difficulty:'easy',serves:2,time:'45 min',calories:220,mainIngredient:'Eggplant',
ingredients:[
  {name:'Eggplants, halved',amount:2,unit:'whole'},
  {name:'Olive oil',amount:30,unit:'ml'},
  {name:'Greek yoghurt',amount:200,unit:'g'},
  {name:'Lemon juice',amount:15,unit:'ml'},
  {name:'Pomegranate seeds',amount:0.5,unit:'pomegranate'},
  {name:'Fresh mint leaves',amount:1,unit:'handful'},
],
steps:[
  'Score eggplant flesh, drizzle with oil. Roast at 200°C for 35–40 minutes until very soft.',
  'Mix yoghurt with lemon juice, salt and pepper.',
  'Spread yoghurt on a plate, place roasted eggplant on top.',
  'Scatter pomegranate seeds and mint leaves.',
]},

{id:90,name:'Grilled Zucchini with Lemon, Dill & Feta',category:'Sides',difficulty:'easy',serves:2,time:'15 min',calories:150,mainIngredient:'Zucchini',
ingredients:[
  {name:'Zucchinis',prep:'sliced lengthways',amount:2,unit:'whole'},
  {name:'Olive oil',amount:15,unit:'ml'},
  {name:'Feta',prep:'crumbled',amount:50,unit:'g'},
  {name:'Fresh dill',prep:'chopped',amount:1,unit:'handful'},
  {name:'Lemon juice',amount:15,unit:'ml'},
],
steps:[
  'Brush zucchini slices with olive oil and season.',
  'Grill until charred on both sides, about 2–3 minutes per side.',
  'Place on a platter. Top with crumbled feta, dill and a squeeze of lemon.',
]},

{id:91,name:'Roasted Cauliflower with Garlic, Parsley & Vinegar',category:'Sides',difficulty:'easy',serves:4,time:'20 min',calories:120,mainIngredient:'Cauliflower',
ingredients:[
  {name:'Cauliflower',prep:'cut into large florets',amount:1,unit:'whole'},
  {name:'Garlic confit cloves',amount:3,unit:'cloves'},
  {name:'Olive oil',amount:75,unit:'ml'},
  {name:'Parsley',prep:'chopped',amount:30,unit:'g'},
  {name:'Chilli flakes',amount:1,unit:'pinch'},
  {name:'Red wine vinegar',amount:30,unit:'ml'},
],
steps:[
  'Heat oven to 260°C. Toss cauliflower with oil, salt and pepper.',
  'Sear in a hot cast-iron pan until browned, 3 minutes.',
  'Transfer to oven and roast 5 minutes, flip and roast 3 more minutes.',
  'Stir through garlic confit, parsley, chilli and vinegar. Season well.',
]},

{id:92,name:'Grilled King Oyster Mushrooms with Tarragon Butter',category:'Sides',difficulty:'easy',serves:2,time:'15 min',calories:180,mainIngredient:'Mushrooms',
ingredients:[
  {name:'Unsalted butter',prep:'softened',amount:40,unit:'g'},
  {name:'Tarragon',prep:'chopped',amount:15,unit:'g'},
  {name:'Chives',prep:'snipped',amount:5,unit:'g'},
  {name:'Garlic clove',prep:'minced',amount:1,unit:'clove'},
  {name:'Lemon zest',amount:5,unit:'g'},
  {name:'King oyster mushrooms, halved lengthways',amount:250,unit:'g'},
  {name:'Olive oil',amount:30,unit:'ml'},
  {name:'Lemon juice',amount:15,unit:'ml'},
],
steps:[
  'Mix butter with tarragon, chives, garlic and lemon zest. Leave at room temperature.',
  'Toss mushrooms with olive oil, salt and pepper.',
  'Grill cut-side down until caramelised, about 4 minutes. Turn and cook 3 minutes more.',
  'Brush with herb butter as they cook. Finish with lemon juice and flaky salt.',
]},

{id:93,name:'Grilled Kale with Shallot-Yoghurt Dressing & Hazelnuts',category:'Sides',difficulty:'medium',serves:4,time:'20 min',calories:220,mainIngredient:'Kale',
ingredients:[
  {name:'Kale bunches',amount:3,unit:'bunches'},
  {name:'Hazelnuts',amount:80,unit:'g'},
  {name:'Olive oil',amount:75,unit:'ml'},
  {name:'Greek yoghurt',amount:240,unit:'g'},
  {name:'Shallot confit',amount:60,unit:'g'},
  {name:'Mint',prep:'chopped',amount:60,unit:'g'},
  {name:'Lemon juice',amount:37,unit:'ml'},
],
steps:[
  'Blend yoghurt, shallot confit, olive oil (or shallot oil), mint and lemon juice. Season.',
  'Toast hazelnuts in a dry pan and chop roughly.',
  'Toss kale with oil, salt, pepper and a splash of water. Grill over high heat until charred and wilted.',
  'Plate charred kale, drizzle with dressing and scatter hazelnuts.',
]},

{id:94,name:'Crispy Brussels Sprouts with Tahini, Maple & Za\'atar',category:'Sides',difficulty:'medium',serves:2,time:'25 min',calories:320,mainIngredient:'Brussels Sprouts',
ingredients:[
  {name:'Olive oil',amount:60,unit:'ml'},
  {name:'Brussels sprouts',prep:'halved',amount:500,unit:'g'},
  {name:'Crispy roast chickpeas',amount:180,unit:'g'},
  {name:'Long red chilli',prep:'finely chopped',amount:0.5,unit:'whole'},
  {name:'Maple syrup',amount:30,unit:'ml'},
  {name:'Lemon juice',amount:30,unit:'ml'},
  {name:'Garlicky whipped tahini',amount:140,unit:'g'},
  {name:'Mint leaves',amount:1,unit:'handful'},
  {name:'Za\'atar',amount:30,unit:'g'},
],
steps:[
  'Heat oven to 210°C. Fry sprouts in oil with a pinch of salt until coloured, 3 minutes.',
  'Transfer pan to oven, roast 10 minutes until caramelised.',
  'Toss sprouts with half the chickpeas, chilli, maple syrup and lemon juice.',
  'Pile onto tahini on a plate. Top with remaining chickpeas, fresh mint and za\'atar.',
]},

{id:95,name:'Roasted Pumpkin with Whipped Feta & Dukkah',category:'Sides',difficulty:'medium',serves:2,time:'30 min',calories:320,mainIngredient:'Pumpkin',
ingredients:[
  {name:'Pumpkin',prep:'sliced',amount:600,unit:'g'},
  {name:'Olive oil',amount:30,unit:'ml'},
  {name:'Cumin seeds',amount:5,unit:'g'},
  {name:'Soft feta',amount:150,unit:'g'},
  {name:'Greek yoghurt',amount:95,unit:'g'},
  {name:'Lemon juice',amount:15,unit:'ml'},
  {name:'Dukkah',amount:30,unit:'g'},
],
steps:[
  'Toss pumpkin with olive oil, cumin seeds, salt and pepper. Roast at 200°C for 25 minutes.',
  'Blend feta, yoghurt and lemon juice until very smooth.',
  'Spread whipped feta on a plate. Top with roasted pumpkin.',
  'Sprinkle generously with dukkah.',
]},

{id:96,name:'Roasted Acorn Squash with Hazelnuts, Brown Butter & Rosemary',category:'Sides',difficulty:'medium',serves:4,time:'40 min',calories:260,mainIngredient:'Squash',
ingredients:[
  {name:'Acorn squash, halved and seeded',amount:1,unit:'whole'},
  {name:'Hazelnuts',prep:'chopped',amount:30,unit:'g'},
  {name:'Butter',amount:55,unit:'g'},
  {name:'Water',amount:60,unit:'ml'},
  {name:'Brown sugar',amount:15,unit:'g'},
  {name:'Rosemary',prep:'chopped',amount:5,unit:'g'},
  {name:'Vegetable stock',amount:120,unit:'ml'},
  {name:'Lemon juice',amount:2,unit:'ml'},
],
steps:[
  'Toast hazelnuts in a dry pan. Set aside.',
  'Roast squash cut-side down with 60 ml water, covered, for 25 minutes. Uncover and roast 10 more. Cut into chunks.',
  'Brown butter in a pan with hazelnuts, brown sugar and rosemary. Gradually add stock, cook until thickened. Stir in lemon juice.',
  'Pour butter sauce over squash and season.',
]},

{id:97,name:'Spicy Carrots with Maple, Pepitas, Yoghurt & Mint',category:'Sides',difficulty:'easy',serves:2,time:'35 min',calories:280,mainIngredient:'Carrots',
ingredients:[
  {name:'Carrots',prep:'roasted with spices',amount:500,unit:'g'},
  {name:'Maple syrup',amount:30,unit:'ml'},
  {name:'Lemon zest',amount:1,unit:'lemon'},
  {name:'Mint and dill',amount:1,unit:'handful'},
  {name:'Greek yoghurt or whipped tahini',amount:260,unit:'g'},
  {name:'Za\'atar',amount:15,unit:'g'},
  {name:'Pepitas',amount:15,unit:'g'},
  {name:'Pomegranate molasses',amount:15,unit:'ml'},
  {name:'Lemon juice',amount:15,unit:'ml'},
],
steps:[
  'Roast spiced carrots until tender. While hot, toss with maple syrup, lemon zest and fresh herbs.',
  'Spread yoghurt or tahini on a serving plate.',
  'Pile the glazed carrots over the yoghurt.',
  'Sprinkle with za\'atar and pepitas, drizzle with pomegranate molasses and lemon juice.',
]},

{id:98,name:'Roast Carrots with Harissa & Yoghurt',category:'Sides',difficulty:'easy',serves:4,time:'30 min',calories:160,mainIngredient:'Carrots',
ingredients:[
  {name:'Dutch carrots, trimmed',amount:1,unit:'bunch'},
  {name:'Olive oil',amount:30,unit:'ml'},
  {name:'Harissa paste',amount:15,unit:'g'},
  {name:'Greek yoghurt',amount:200,unit:'g'},
  {name:'Lemon juice',amount:15,unit:'ml'},
  {name:'Coriander leaves',amount:1,unit:'handful'},
],
steps:[
  'Heat oven to 200°C. Toss carrots with olive oil and harissa. Season.',
  'Roast 20–25 minutes until tender and caramelised.',
  'Mix yoghurt with lemon juice and spread on a plate.',
  'Lay roasted carrots over yoghurt and scatter with coriander.',
]},

{id:99,name:'Pea & Mint Fritters',category:'Sides',difficulty:'easy',serves:4,time:'20 min',calories:200,mainIngredient:'Peas',
ingredients:[
  {name:'Frozen peas',prep:'thawed',amount:300,unit:'g'},
  {name:'Spring onions',prep:'chopped',amount:2,unit:'whole'},
  {name:'Eggs',amount:2,unit:'whole'},
  {name:'Self-raising flour',amount:100,unit:'g'},
  {name:'Baking powder',amount:2,unit:'g'},
  {name:'Fresh mint leaves, chopped',amount:1,unit:'handful'},
  {name:'Feta',prep:'crumbled',amount:50,unit:'g'},
  {name:'Olive oil, for frying',amount:30,unit:'ml'},
],
steps:[
  'Mash half the peas and keep the rest whole. Mix with spring onions, eggs, flour, baking powder, mint and feta.',
  'Heat olive oil in a pan. Fry spoonfuls of batter for 2–3 minutes per side until golden.',
  'Drain on paper towel, season lightly. Serve hot.',
]},

{id:100,name:'Homemade Baked Beans',category:'Sides',difficulty:'easy',serves:4,time:'40 min',calories:280,mainIngredient:'Beans',
ingredients:[
  {name:'Olive oil',amount:30,unit:'ml'},
  {name:'Onion',prep:'finely chopped',amount:1,unit:'whole'},
  {name:'Garlic cloves',prep:'chopped',amount:2,unit:'cloves'},
  {name:'Cannellini beans',prep:'drained',amount:800,unit:'g'},
  {name:'Tinned chopped tomatoes',amount:400,unit:'g'},
  {name:'Tomato paste',amount:30,unit:'g'},
  {name:'Brown sugar',amount:15,unit:'g'},
  {name:'Worcestershire sauce',amount:15,unit:'ml'},
  {name:'Smoked paprika',amount:5,unit:'g'},
],
steps:[
  'Heat oil in a pot. Sauté onion and garlic until very soft.',
  'Add beans, tomatoes, paste, sugar, Worcestershire sauce and paprika.',
  'Simmer gently for 30 minutes until thick and saucy.',
  'Season to taste and serve.',
]},

{id:101,name:'Lemony Crushed Butter Beans',category:'Sides',difficulty:'easy',serves:4,time:'10 min',calories:240,mainIngredient:'Butter Beans',
ingredients:[
  {name:'Butter beans',prep:'rinsed',amount:800,unit:'g'},
  {name:'Olive oil',amount:80,unit:'ml'},
  {name:'Garlic cloves',prep:'grated',amount:2,unit:'cloves'},
  {name:'Lemon juice',amount:30,unit:'ml'},
  {name:'Fennel bulb',prep:'finely chopped',amount:0.5,unit:'small'},
  {name:'Spring onion',prep:'sliced',amount:15,unit:'g'},
  {name:'Parsley',prep:'chopped',amount:5,unit:'g'},
  {name:'Chilli in oil',amount:30,unit:'ml'},
],
steps:[
  'Blitz butter beans, olive oil, garlic and lemon juice to a chunky purée.',
  'Fold in chopped fennel, spring onion and parsley. Season well.',
  'Top with chilli oil and fennel fronds to serve.',
]},

{id:102,name:'Brown Rice & Herb Pilaf with Toasted Almonds',category:'Sides',difficulty:'easy',serves:2,time:'40 min',calories:340,mainIngredient:'Brown Rice',
ingredients:[
  {name:'Brown rice',amount:150,unit:'g'},
  {name:'Onion',prep:'finely chopped',amount:1,unit:'whole'},
  {name:'Olive oil',amount:15,unit:'ml'},
  {name:'Vegetable stock',amount:400,unit:'ml'},
  {name:'Parsley and dill',amount:1,unit:'handful'},
  {name:'Toasted almonds',amount:30,unit:'g'},
],
steps:[
  'Fry onion in olive oil until soft.',
  'Add brown rice, stir to coat, then pour in vegetable stock.',
  'Simmer covered until all liquid is absorbed and rice is tender.',
  'Stir in herbs, season, and top with toasted almonds.',
]},

// ── BREAD & BAKES ─────────────────────────────────────────
{id:103,name:'BBQ Bread (Matt Stone)',category:'Bread & Bakes',difficulty:'medium',serves:12,time:'2 hr 30 min',calories:280,mainIngredient:'Bread',
ingredients:[
  {name:'Caster sugar',amount:15,unit:'g'},
  {name:'Dried yeast',amount:15,unit:'g'},
  {name:'Olive oil',amount:60,unit:'ml'},
  {name:'Plain yoghurt',amount:60,unit:'ml'},
  {name:'Lukewarm water',amount:600,unit:'ml'},
  {name:'Strong bread flour',amount:1000,unit:'g'},
  {name:'Fine sea salt',amount:7,unit:'g'},
],
steps:[
  'Mix sugar, yeast, 2 tbsp olive oil, yoghurt and 550 ml lukewarm water until yeast dissolves.',
  'Add flour and salt. Mix to a soft dough and knead 10 minutes until smooth.',
  'Place in an oiled bowl, cover and rise 1 hour until doubled. Knock back, fold, rise 30 more minutes.',
  'Divide into 12 pieces, roll into balls, rest 15 minutes. Roll each into 5 mm thick circles.',
  'Brush with oil and cook on a hot barbecue hotplate 2–3 minutes per side until puffed and charred.',
  'Serve warm with olive oil and sea salt.',
]},

{id:104,name:'Potato Flatbreads',category:'Bread & Bakes',difficulty:'easy',serves:8,time:'45 min',calories:180,mainIngredient:'Potato',
ingredients:[
  {name:'Potatoes',prep:'peeled and diced',amount:500,unit:'g'},
  {name:'Plain flour, plus extra',amount:250,unit:'g'},
  {name:'Baking powder',amount:5,unit:'g'},
  {name:'Salt',amount:5,unit:'g'},
  {name:'Olive oil',amount:30,unit:'ml'},
],
steps:[
  'Boil potatoes until tender. Drain, mash until smooth and cool.',
  'Mix flour, baking powder and salt. Stir in mashed potato and olive oil, knead to a soft dough.',
  'Divide into 8 pieces and roll into rounds on a floured surface.',
  'Cook flatbreads in a hot dry pan 2–3 minutes per side until golden spots appear.',
]},

{id:105,name:'Spinach & Feta Gozleme',category:'Bread & Bakes',difficulty:'medium',serves:4,time:'90 min',calories:420,mainIngredient:'Spinach',
ingredients:[
  {name:'Bread flour',amount:500,unit:'g'},
  {name:'Dried yeast',amount:7,unit:'g'},
  {name:'Caster sugar',amount:5,unit:'g'},
  {name:'Warm water',amount:300,unit:'ml'},
  {name:'Olive oil',amount:30,unit:'ml'},
  {name:'Baby spinach',prep:'wilted and squeezed dry',amount:300,unit:'g'},
  {name:'Feta',prep:'crumbled',amount:200,unit:'g'},
  {name:'Red onion',prep:'finely chopped',amount:1,unit:'small'},
  {name:'Flat-leaf parsley',prep:'chopped',amount:1,unit:'handful'},
],
steps:[
  'Combine flour, yeast, sugar and salt. Add warm water and oil, mix to a dough. Knead 10 minutes. Rise 1 hour.',
  'Mix spinach, feta, red onion and parsley for filling. Season with pepper.',
  'Divide dough into 4. Roll each into a rectangle. Fill with mixture, fold and press edges to seal.',
  'Brush with oil and cook in a frying pan 2–3 minutes per side until golden.',
  'Slice and serve hot with lemon wedges.',
]},

{id:106,name:'Spinach & Feta Pie',category:'Bread & Bakes',difficulty:'medium',serves:4,time:'60 min',calories:360,mainIngredient:'Spinach',
ingredients:[
  {name:'Olive oil',amount:30,unit:'ml'},
  {name:'Onion',prep:'finely chopped',amount:1,unit:'whole'},
  {name:'Garlic cloves',prep:'chopped',amount:2,unit:'cloves'},
  {name:'Spinach',prep:'washed and chopped',amount:500,unit:'g'},
  {name:'Feta cheese',prep:'crumbled',amount:200,unit:'g'},
  {name:'Eggs',prep:'lightly beaten',amount:2,unit:'whole'},
  {name:'Dill',prep:'chopped',amount:30,unit:'g'},
  {name:'Filo pastry sheets',amount:10,unit:'sheets'},
  {name:'Butter',prep:'melted',amount:100,unit:'g'},
],
steps:[
  'Fry onion and garlic in oil. Add spinach and cook until wilted. Cool slightly.',
  'Mix spinach with feta, eggs, dill, salt and pepper.',
  'Layer filo sheets in a greased dish, brushing each with butter. Spread filling inside, fold pastry over.',
  'Bake at 180°C for 35–40 minutes until golden.',
]},

{id:107,name:'Tomato & Ricotta Galette',category:'Bread & Bakes',difficulty:'medium',serves:4,time:'60 min',calories:320,mainIngredient:'Tomatoes',
ingredients:[
  {name:'Plain flour',amount:200,unit:'g'},
  {name:'Cold butter',prep:'cubed',amount:100,unit:'g'},
  {name:'Cold water',amount:45,unit:'ml'},
  {name:'Ricotta',amount:250,unit:'g'},
  {name:'Egg',amount:1,unit:'whole'},
  {name:'Olive oil',amount:15,unit:'ml'},
  {name:'Ripe tomatoes',prep:'sliced',amount:500,unit:'g'},
  {name:'Fresh basil leaves',amount:1,unit:'handful'},
],
steps:[
  'Rub butter into flour until it resembles breadcrumbs. Add water and mix to a dough. Chill 30 minutes.',
  'Heat oven to 200°C. Roll dough into a rough circle on a lined baking tray.',
  'Mix ricotta, egg and olive oil. Spread over centre of pastry, leaving a 4 cm border.',
  'Layer tomato slices over ricotta, season. Fold pastry edges over filling.',
  'Bake 30–35 minutes until golden. Scatter basil to serve.',
]},

{id:108,name:'Zucchini Slice',category:'Bread & Bakes',difficulty:'easy',serves:6,time:'50 min',calories:280,mainIngredient:'Zucchini',
ingredients:[
  {name:'Zucchini',prep:'grated',amount:2,unit:'medium'},
  {name:'Onion',prep:'finely chopped',amount:1,unit:'whole'},
  {name:'Self-raising flour',amount:150,unit:'g'},
  {name:'Grated cheddar cheese',amount:150,unit:'g'},
  {name:'Olive oil',amount:120,unit:'ml'},
  {name:'Eggs',prep:'lightly beaten',amount:5,unit:'whole'},
],
steps:[
  'Heat oven to 180°C. Grease and line a 20×30 cm slice tin.',
  'Combine all ingredients in a large bowl. Season well and mix.',
  'Pour into the tin and bake 35–40 minutes until golden and set.',
  'Cool 5 minutes before slicing.',
]},

{id:109,name:'Quiche Lorraine',category:'Bread & Bakes',difficulty:'medium',serves:6,time:'75 min',calories:420,mainIngredient:'Eggs',
ingredients:[
  {name:'Plain flour',amount:200,unit:'g'},
  {name:'Cold butter',prep:'cubed',amount:100,unit:'g'},
  {name:'Egg yolk',amount:1,unit:'whole'},
  {name:'Cold water',amount:30,unit:'ml'},
  {name:'Bacon',prep:'chopped',amount:200,unit:'g'},
  {name:'Onion',prep:'finely chopped',amount:1,unit:'whole'},
  {name:'Eggs',amount:3,unit:'whole'},
  {name:'Cream',amount:200,unit:'ml'},
  {name:'Milk',amount:100,unit:'ml'},
  {name:'Gruyère cheese, grated',amount:100,unit:'g'},
],
steps:[
  'Rub butter into flour, add egg yolk and water, mix to dough. Chill 30 minutes.',
  'Heat oven to 180°C. Roll dough, line a tart tin and blind bake 15 minutes.',
  'Fry bacon and onion until golden. Whisk eggs, cream and milk together.',
  'Spread bacon and onion in pastry shell. Pour egg mixture over, top with cheese.',
  'Bake 30 minutes until golden and just set.',
]},

// ── SAUCES & CONDIMENTS ────────────────────────────────────
{id:110,name:'3-Minute Romesco Sauce',category:'Sauces & Condiments',difficulty:'easy',serves:8,time:'5 min',calories:120,mainIngredient:'Capsicum',
ingredients:[
  {name:'Roasted capsicum',amount:200,unit:'g'},
  {name:'Garlic cloves',amount:2,unit:'cloves'},
  {name:'Toasted hazelnuts or almonds',amount:100,unit:'g'},
  {name:'Tomato paste',amount:30,unit:'g'},
  {name:'Smoked paprika',amount:10,unit:'g'},
  {name:'Red wine vinegar',amount:30,unit:'ml'},
  {name:'Chilli powder',amount:1,unit:'pinch'},
  {name:'Olive oil',amount:125,unit:'ml'},
],
steps:[
  'Place all ingredients in a food processor or blender.',
  'Blitz until chunky — don\'t over-process, you want some texture.',
  'Taste and adjust with salt, pepper or extra vinegar.',
]},

{id:111,name:'Green Goddess Tahini Sauce',category:'Sauces & Condiments',difficulty:'easy',serves:6,time:'5 min',calories:90,mainIngredient:'Tahini',
ingredients:[
  {name:'Tahini',amount:135,unit:'g'},
  {name:'Lemon juice',amount:30,unit:'ml'},
  {name:'Garlic cloves',prep:'crushed',amount:2,unit:'cloves'},
  {name:'Parsley',prep:'chopped',amount:1,unit:'handful'},
  {name:'Coriander',prep:'chopped',amount:1,unit:'handful'},
  {name:'Water',amount:170,unit:'ml'},
],
steps:[
  'Blend tahini, lemon juice, garlic, parsley, coriander and water until very smooth and green.',
  'Adjust with more water for a pourable consistency or more lemon for brightness. Season.',
]},

{id:112,name:'Garlicky Whipped Tahini',category:'Sauces & Condiments',difficulty:'easy',serves:6,time:'5 min',calories:110,mainIngredient:'Tahini',
ingredients:[
  {name:'Tahini',amount:135,unit:'g'},
  {name:'Lemon juice',amount:30,unit:'ml'},
  {name:'Garlic cloves',prep:'crushed',amount:2,unit:'cloves'},
  {name:'Water',amount:170,unit:'ml'},
],
steps:[
  'Blend or whisk tahini, lemon juice, garlic and water until very smooth and silky.',
  'Add more water for a thinner consistency, more lemon for brightness. Season with salt.',
]},

{id:113,name:'Sumac Yoghurt',category:'Sauces & Condiments',difficulty:'easy',serves:6,time:'5 min',calories:80,mainIngredient:'Yoghurt',
ingredients:[
  {name:'Greek yoghurt',amount:390,unit:'g'},
  {name:'Garlic cloves',prep:'crushed',amount:2,unit:'cloves'},
  {name:'Ground sumac',amount:15,unit:'g'},
  {name:'Lemon juice',amount:30,unit:'ml'},
  {name:'Olive oil',amount:30,unit:'ml'},
],
steps:[
  'Stir yoghurt, garlic, sumac, lemon juice and olive oil together in a bowl.',
  'Season with salt and black pepper. Taste and adjust.',
]},

{id:114,name:'Herbed Yoghurt with Lemon & Garlic',category:'Sauces & Condiments',difficulty:'easy',serves:4,time:'5 min',calories:60,mainIngredient:'Yoghurt',
ingredients:[
  {name:'Greek yoghurt',amount:200,unit:'g'},
  {name:'Lemon juice and zest',amount:1,unit:'lemon'},
  {name:'Garlic clove',prep:'crushed',amount:1,unit:'clove'},
  {name:'Parsley and mint',prep:'chopped',amount:1,unit:'handful'},
],
steps:[
  'Mix yoghurt, lemon juice, lemon zest, garlic and herbs together.',
  'Season with salt and pepper to taste.',
]},

{id:115,name:'Roast Tomato & White Bean Raita',category:'Sauces & Condiments',difficulty:'medium',serves:2,time:'50 min',calories:280,mainIngredient:'Tomatoes',
ingredients:[
  {name:'Tomatoes',prep:'halved',amount:3,unit:'whole'},
  {name:'Olive oil',amount:60,unit:'ml'},
  {name:'Greek yoghurt',amount:780,unit:'g'},
  {name:'Garlic clove',prep:'crushed',amount:1,unit:'clove'},
  {name:'Kalamata olives, chopped',amount:40,unit:'g'},
  {name:'Coriander',prep:'chopped',amount:1,unit:'handful'},
  {name:'Mustard seeds',amount:5,unit:'g'},
  {name:'Cumin seeds',amount:5,unit:'g'},
  {name:'Butter beans',prep:'rinsed',amount:400,unit:'g'},
  {name:'Zhoug or pesto',amount:30,unit:'ml'},
  {name:'Mint leaves',prep:'chopped',amount:1,unit:'handful'},
  {name:'Lemon juice',amount:30,unit:'ml'},
],
steps:[
  'Roast tomatoes at 180°C with oil, salt and pepper for 40 minutes. Chop, reserve a quarter for the beans.',
  'Mix yoghurt with garlic, olives, coriander and the remaining tomatoes.',
  'Fry mustard and cumin seeds in oil until fragrant. Stir through yoghurt mixture. Chill 30 minutes.',
  'Toss butter beans with zhoug, reserved tomato, mint and lemon juice.',
  'Spread yoghurt on a plate, top with dressed beans and drizzle with oil.',
]},

{id:116,name:'Salmoriglio',category:'Sauces & Condiments',difficulty:'easy',serves:6,time:'5 min',calories:130,mainIngredient:'Herbs',
ingredients:[
  {name:'Garlic cloves',prep:'crushed',amount:2,unit:'cloves'},
  {name:'Fresh oregano, leaves picked',amount:1,unit:'bunch'},
  {name:'Parsley leaves',amount:1,unit:'handful'},
  {name:'Lemon juice',amount:60,unit:'ml'},
  {name:'Olive oil',amount:200,unit:'ml'},
],
steps:[
  'Blend garlic, oregano, parsley, lemon juice and olive oil into a loose, fragrant sauce.',
  'Or pound garlic and herbs in a mortar, then stir through juice and oil.',
  'Season well. Keeps a week in the fridge.',
]},

{id:117,name:'Zhoug',category:'Sauces & Condiments',difficulty:'easy',serves:6,time:'5 min',calories:110,mainIngredient:'Herbs',
ingredients:[
  {name:'Coriander',amount:0.5,unit:'bunch'},
  {name:'Parsley',amount:0.5,unit:'bunch'},
  {name:'Long red chilli',prep:'sliced',amount:1,unit:'whole'},
  {name:'Ground cumin',amount:10,unit:'g'},
  {name:'Ground coriander',amount:5,unit:'g'},
  {name:'Ground cinnamon',amount:2,unit:'g'},
  {name:'Smoked paprika',amount:2,unit:'g'},
  {name:'Lemon juice',amount:15,unit:'ml'},
  {name:'Olive oil',amount:170,unit:'ml'},
],
steps:[
  'Blitz herbs, chilli, spices and half the olive oil together.',
  'Add remaining oil and blitz again. Season to taste.',
]},

{id:118,name:'Pickled Red Onions (Zuni Cafe)',category:'Sauces & Condiments',difficulty:'easy',serves:8,time:'30 min',calories:60,mainIngredient:'Onions',
ingredients:[
  {name:'Red onions',prep:'cut into rings',amount:450,unit:'g'},
  {name:'White vinegar',amount:750,unit:'ml'},
  {name:'Sugar',amount:300,unit:'g'},
  {name:'Cinnamon stick',amount:1,unit:'whole'},
  {name:'Cloves',amount:4,unit:'whole'},
  {name:'Black peppercorns',amount:1,unit:'handful'},
  {name:'Bay leaves',amount:2,unit:'whole'},
  {name:'Dried chilli',amount:1,unit:'whole'},
],
steps:[
  'Bring vinegar, sugar, cinnamon, cloves, peppercorns, bay leaves and chilli to a boil.',
  'Simmer onion rings in three batches for 20 seconds each. Remove and cool on a tray.',
  'Let the brine cool completely, then pour over onions and store in the fridge.',
]},

// ── DESSERTS ─────────────────────────────────────────────
{id:119,name:'Lemon Tart',category:'Desserts',difficulty:'medium',serves:6,time:'75 min',calories:380,mainIngredient:'Lemon',
ingredients:[
  {name:'Plain flour',amount:200,unit:'g'},
  {name:'Cold butter',prep:'cubed',amount:100,unit:'g'},
  {name:'Icing sugar',amount:30,unit:'g'},
  {name:'Egg yolk',amount:1,unit:'whole'},
  {name:'Cold water',amount:30,unit:'ml'},
  {name:'Eggs',amount:4,unit:'whole'},
  {name:'Caster sugar',amount:150,unit:'g'},
  {name:'Lemon juice',amount:150,unit:'ml'},
  {name:'Cream',amount:200,unit:'ml'},
  {name:'Lemon zest',amount:2,unit:'lemons'},
],
steps:[
  'Rub butter into flour until it resembles breadcrumbs. Stir in icing sugar, egg yolk and water. Form dough and chill 30 minutes.',
  'Heat oven to 180°C. Roll dough, line a tart tin and blind bake 15 minutes. Cool.',
  'Whisk eggs, sugar, lemon juice, cream and zest until smooth.',
  'Pour into the tart shell and bake 30 minutes until just set.',
  'Cool completely before serving.',
]},

{id:120,name:'Crème Caramel',category:'Desserts',difficulty:'hard',serves:6,time:'5 hr (including chill)',calories:280,mainIngredient:'Eggs',
ingredients:[
  {name:'Caster sugar',amount:150,unit:'g'},
  {name:'Water',amount:45,unit:'ml'},
  {name:'Full-cream milk',amount:600,unit:'ml'},
  {name:'Vanilla bean',prep:'split',amount:1,unit:'whole'},
  {name:'Eggs',amount:4,unit:'whole'},
  {name:'Egg yolks',amount:2,unit:'yolks'},
  {name:'Caster sugar',amount:100,unit:'g'},
],
steps:[
  'Heat oven to 150°C. Melt 150 g sugar with water in a pan until golden caramel. Pour into 6 ramekins.',
  'Heat milk with vanilla bean until steaming. Whisk eggs, yolks and remaining sugar in a bowl.',
  'Slowly pour hot milk into eggs, whisking constantly. Strain and pour over caramel.',
  'Place ramekins in a baking dish, fill halfway with hot water. Bake 40–45 minutes until just set.',
  'Chill at least 4 hours. Unmould onto plates just before serving.',
]},

{id:121,name:'Tiramisu',category:'Desserts',difficulty:'medium',serves:6,time:'30 min + 4 hr chill',calories:420,mainIngredient:'Mascarpone',
ingredients:[
  {name:'Mascarpone',amount:250,unit:'g'},
  {name:'Eggs, separated',amount:3,unit:'whole'},
  {name:'Caster sugar',amount:100,unit:'g'},
  {name:'Strong coffee',prep:'cooled',amount:200,unit:'ml'},
  {name:'Marsala or brandy',amount:30,unit:'ml'},
  {name:'Savoiardi biscuits',amount:200,unit:'g'},
  {name:'Cocoa powder, for dusting',amount:1,unit:'to serve'},
],
steps:[
  'Whisk egg yolks with sugar until pale. Beat in mascarpone until smooth.',
  'Whisk egg whites to soft peaks. Fold gently into mascarpone mixture.',
  'Mix cooled coffee with marsala. Dip biscuits briefly and layer in a dish.',
  'Spread mascarpone mixture over biscuits. Repeat layers.',
  'Chill at least 4 hours. Dust generously with cocoa powder before serving.',
]},

{id:122,name:'Grilled Peaches with Honey & Mascarpone',category:'Desserts',difficulty:'easy',serves:4,time:'15 min',calories:260,mainIngredient:'Peaches',
ingredients:[
  {name:'Ripe peaches',prep:'halved and pitted',amount:4,unit:'whole'},
  {name:'Olive oil',amount:15,unit:'ml'},
  {name:'Mascarpone',amount:200,unit:'g'},
  {name:'Honey',amount:30,unit:'ml'},
  {name:'Fresh mint leaves',amount:1,unit:'handful'},
],
steps:[
  'Heat a grill pan or barbecue to high.',
  'Brush peach halves with olive oil and grill cut-side down for 3–4 minutes until charred.',
  'Serve warm with a generous dollop of mascarpone, a drizzle of honey and scattered mint.',
]},

{id:123,name:'Fresh Fruit Salad with Citrus Syrup',category:'Desserts',difficulty:'easy',serves:4,time:'15 min',calories:180,mainIngredient:'Fruit',
ingredients:[
  {name:'Pineapple',prep:'peeled and chopped',amount:1,unit:'whole'},
  {name:'Mangos, peeled and chopped',amount:2,unit:'whole'},
  {name:'Kiwifruit, sliced',amount:2,unit:'whole'},
  {name:'Strawberries',prep:'halved',amount:1,unit:'punnet'},
  {name:'Oranges',prep:'segmented',amount:2,unit:'whole'},
  {name:'Mint leaves',amount:1,unit:'handful'},
  {name:'Orange juice',amount:60,unit:'ml'},
  {name:'Lime juice',amount:30,unit:'ml'},
  {name:'Honey',amount:30,unit:'ml'},
],
steps:[
  'Mix all prepared fruit in a large bowl.',
  'Whisk orange juice, lime juice and honey together for the syrup.',
  'Pour syrup over fruit and toss gently.',
  'Scatter fresh mint leaves before serving.',
]},

]; // end recipes3
