const RECIPES4 = [

// ── DIPS & STARTERS ──────────────────────────────────────
{id:124,name:'Whipped Feta with Snap Peas and Hot Honey',category:'Dips & Starters',difficulty:'easy',serves:4,time:'20 min',calories:280,mainIngredient:'Feta',
ingredients:[
  {name:'Feta',amount:200,unit:'g'},
  {name:'Skyr or Greek yoghurt',amount:3,unit:'tbsp'},
  {name:'Olive oil',amount:1,unit:'tbsp'},
  {name:'Black pepper',amount:1,unit:'to taste'},
  {name:'Lemon, zest and juice of half',amount:0.5,unit:'whole'},
  {name:'Salt',amount:1,unit:'pinch'},
  {name:'Snap peas',amount:200,unit:'g'},
  {name:'Olive oil',amount:1,unit:'tbsp'},
  {name:'Honey',amount:2,unit:'tbsp'},
  {name:'Smoked paprika',amount:1,unit:'tsp'},
  {name:'Espelette pepper',amount:1,unit:'tsp'},
  {name:'Cider vinegar',amount:1,unit:'to taste'},
  {name:'Fresh mint',amount:1,unit:'handful'},
  {name:'Toasted pistachios',amount:2,unit:'tbsp'},
],
steps:[
  'Blend feta, yoghurt, olive oil, lemon zest and juice, black pepper, and a pinch of salt until smooth. Chill in the fridge to firm slightly.',
  'Blanch or lightly sauté the snap peas with olive oil, salt, and black pepper until just tender but still crisp.',
  'Make the hot honey by gently warming honey with smoked paprika, Espelette pepper, and a few drops of cider vinegar to infuse.',
  'Arrange the whipped feta on a plate, top with snap peas, drizzle with hot honey, and finish with fresh mint, lemon zest, olive oil, and toasted pistachios.',
  'Serve.',
]},

{id:125,name:'Burrata, Anchovy, Mint and Extra Virgin Olive Oil',category:'Dips & Starters',difficulty:'easy',serves:2,time:'5 min',calories:320,mainIngredient:'Burrata',
ingredients:[
  {name:'Burrata',amount:1,unit:'whole'},
  {name:'Anchovies',amount:6,unit:'whole'},
  {name:'Fresh mint leaves',amount:1,unit:'handful'},
  {name:'Extra virgin olive oil',amount:3,unit:'tbsp'},
],
steps:[
  'Place the burrata on a serving plate.',
  'Arrange the anchovies over the burrata.',
  'Scatter fresh mint leaves on top.',
  'Drizzle generously with extra virgin olive oil.',
  'Serve immediately.',
]},

// ── SALADS ──────────────────────────────────────────────
{id:126,name:'Dill Caesar Salad',category:'Salads',difficulty:'medium',serves:4,time:'25 min',calories:240,mainIngredient:'Baby Gem Lettuce',
ingredients:[
  {name:'Baby gem lettuce',amount:2,unit:'whole'},
  {name:'Fresh dill',amount:1,unit:'bunch'},
  {name:'Creamy dill Caesar dressing',amount:4,unit:'tbsp'},
  {name:'Anchovy breadcrumbs',prep:'spicy',amount:4,unit:'tbsp'},
],
steps:[
  'Prepare the creamy dill Caesar dressing.',
  'Wash and dry the baby gem lettuce thoroughly.',
  'Toss the lettuce with the creamy dill Caesar dressing until coated.',
  'Make the spicy anchovy breadcrumbs and toast them until crispy.',
  'Plate the dressed lettuce and top generously with the anchovy breadcrumbs.',
  'Garnish with extra fresh dill before serving.',
]},

{id:127,name:'Spicy Onion Salad',category:'Salads',difficulty:'easy',serves:4,time:'15 min',calories:60,mainIngredient:'Red Onion',
ingredients:[
  {name:'Red onions',amount:2,unit:'whole',prep:'thinly sliced'},
  {name:'Tomato',amount:1,unit:'whole',prep:'finely chopped'},
  {name:'Green chilli',amount:1,unit:'whole',prep:'finely chopped'},
  {name:'Fresh coriander',amount:2,unit:'tbsp',prep:'chopped'},
  {name:'Lemon juice',amount:1,unit:'tbsp'},
  {name:'Salt',amount:1,unit:'tsp'},
  {name:'Chilli powder',amount:0.5,unit:'tsp'},
  {name:'Roasted cumin powder',amount:0.5,unit:'tsp'},
],
steps:[
  'Place the sliced onions in a bowl of cold water for 10 minutes to reduce sharpness. Drain well.',
  'Combine onions, tomato, green chilli, and fresh coriander in a mixing bowl.',
  'Sprinkle in salt, chilli powder, and roasted cumin powder.',
  'Add the lemon juice and toss everything together until evenly coated.',
  'Serve immediately as a side dish with grilled or tandoori meats.',
]},

{id:128,name:'Chilled Cucumber and Asparagus with Herb Fish Sauce Dressing',category:'Salads',difficulty:'easy',serves:4,time:'15 min',calories:80,mainIngredient:'Cucumber',
ingredients:[
  {name:'Cucumbers',amount:2,unit:'whole'},
  {name:'Asparagus',amount:200,unit:'g'},
  {name:'Fresh herbs',amount:1,unit:'handful'},
  {name:'Fish sauce',amount:2,unit:'tbsp'},
],
steps:[
  'Prepare the cucumbers and asparagus by chilling them.',
  'Chop the fresh herbs.',
  'Make a dressing by combining the herbs with fish sauce.',
  'Arrange the chilled cucumbers and asparagus on a plate.',
  'Drizzle the herb and fish sauce dressing over the vegetables.',
  'Serve immediately.',
]},

{id:129,name:'Beetroot, Whipped Ricotta and Pistachios',category:'Salads',difficulty:'easy',serves:4,time:'30 min',calories:260,mainIngredient:'Beetroot',
ingredients:[
  {name:'Beetroot',amount:4,unit:'whole'},
  {name:'Ricotta',amount:200,unit:'g'},
  {name:'Lemon',amount:0.5,unit:'whole'},
  {name:'Olive oil',amount:3,unit:'tbsp'},
  {name:'Pistachios',amount:50,unit:'g'},
  {name:'Honey',amount:1,unit:'tbsp'},
  {name:'Dijon mustard',amount:1,unit:'tsp'},
  {name:'Red wine vinegar',amount:1,unit:'tbsp'},
  {name:'Aleppo pepper',amount:0.5,unit:'tsp'},
  {name:'Fresh mint',amount:1,unit:'handful'},
],
steps:[
  'Roast or boil the beetroot until tender, then peel and slice.',
  'Whip the ricotta with a bit of lemon juice and zest until smooth and fluffy.',
  'Make a dressing with olive oil, chopped pistachios, honey, dijon mustard, red wine vinegar, and Aleppo pepper.',
  'Arrange the beetroot on a plate, dollop with whipped ricotta, and drizzle with the pistachio dressing.',
  'Sprinkle fresh mint leaves over the top before serving.',
]},

// ── SEAFOOD ──────────────────────────────────────────────
{id:130,name:'Prawn Carpaccio with Prawn Head Oil Dressing',category:'Seafood',difficulty:'medium',serves:4,time:'30 min',calories:160,mainIngredient:'Prawns',
ingredients:[
  {name:'Fresh prawns',amount:500,unit:'g'},
  {name:'Olive oil',amount:4,unit:'tbsp'},
  {name:'Salt',amount:1,unit:'to taste'},
],
steps:[
  'Prepare the prawns by carefully removing the heads and shells.',
  'Reserve the prawn heads for making the oil dressing.',
  'Lay the prawn meat flat and slice thinly to create the carpaccio.',
  'Heat olive oil in a pan and gently cook the prawn heads to infuse the oil with flavour.',
  'Strain the oil to remove the prawn heads, creating the prawn head oil dressing.',
  'Arrange the prawn carpaccio on a plate and drizzle with the prawn head oil.',
  'Sprinkle with a pinch of salt and serve immediately.',
]},

{id:131,name:'Dover Sole with Fennel, Orange and Chilli Butter',category:'Seafood',difficulty:'medium',serves:2,time:'35 min',calories:520,mainIngredient:'Dover Sole',
ingredients:[
  {name:'Fennel bulb',prep:'finely sliced',amount:1,unit:'whole'},
  {name:'Lemon juice',amount:0.5,unit:'whole'},
  {name:'Chives',prep:'finely chopped',amount:1,unit:'tbsp'},
  {name:'Dill',amount:1,unit:'handful'},
  {name:'Olive oil',amount:4,unit:'tbsp'},
  {name:'Dover sole',amount:1,unit:'whole'},
  {name:'Flour',amount:3,unit:'tbsp'},
  {name:'Butter',amount:70,unit:'g'},
  {name:'Orange, zest and juice',amount:1,unit:'whole'},
  {name:'Fennel seeds',amount:1,unit:'tbsp'},
  {name:'Red chilli',prep:'finely chopped',amount:1,unit:'whole'},
  {name:'Capers',amount:2,unit:'tbsp'},
],
steps:[
  'Thinly shave the fennel bulb, then toss with the herbs, lemon juice, olive oil, salt, and fennel fronds. Set aside.',
  'Pat the Dover sole dry and season well with salt and pepper. Coat in flour and tap off the excess.',
  'Heat a large frying pan over medium-high heat with olive oil and 50g butter. Cook the Dover sole for 3–4 minutes on the first side until golden.',
  'Flip the fish and baste continuously with the butter for another 3 minutes until just cooked through. Remove the fish to a plate and rest.',
  'Lower the heat. Add fennel seeds and chilli to the pan and cook for 30 seconds, then add capers, orange zest, orange juice, and remaining butter.',
  'Let the sauce bubble for 1–2 minutes until glossy and reduced. Stir through chives and spoon over the Dover sole.',
  'Serve with the shaved fennel salad alongside.',
]},

// ── MEAT & POULTRY ───────────────────────────────────────
{id:132,name:'Ginger & Spring Onion Poached Chicken',category:'Meat & Poultry',difficulty:'easy',serves:4,time:'45 min',calories:340,mainIngredient:'Chicken',
ingredients:[
  {name:'Chicken drumsticks',amount:6,unit:'whole'},
  {name:'Ginger',prep:'thick slices',amount:3,unit:'slices'},
  {name:'Spring onions',amount:4,unit:'whole'},
  {name:'Rice bran or vegetable oil',amount:3,unit:'tbsp'},
  {name:'Ginger',prep:'finely chopped',amount:15,unit:'g'},
  {name:'Sugar',amount:1,unit:'tsp'},
  {name:'Sesame oil',amount:1,unit:'tsp'},
  {name:'Poaching liquid',amount:80,unit:'ml'},
  {name:'Light soy sauce',amount:3,unit:'tbsp'},
],
steps:[
  'Bring about 2L of water to a boil and add the ginger slices and spring onion.',
  'Add the chicken and bring back to a boil, then lower the heat, cover, and gently simmer for 10 minutes.',
  'Turn off the heat and leave the chicken in the pot, covered, for about 20 minutes to finish cooking gently. Remove, shred, and plate up.',
  'Heat the oil in a pan and fry the spring onion and ginger until fragrant and just starting to turn golden.',
  'Add the sugar, sesame oil, poaching liquid, and light soy sauce, letting it simmer for another minute.',
  'Taste and adjust seasoning, then spoon over the chicken and serve with rice.',
]},

{id:133,name:'One-Pan Sausage and Feta Shakshuka',category:'Meat & Poultry',difficulty:'easy',serves:4,time:'35 min',calories:580,mainIngredient:'Sausages',
ingredients:[
  {name:'Olive oil',amount:2,unit:'tbsp'},
  {name:'Brown onion',prep:'diced',amount:1,unit:'whole'},
  {name:'Garlic cloves',prep:'roughly chopped',amount:2,unit:'cloves'},
  {name:'Baby red peppers',prep:'halved',amount:10,unit:'whole'},
  {name:'Ground cumin',amount:2,unit:'tsp'},
  {name:'Ground coriander',amount:2,unit:'tsp'},
  {name:'Smoky paprika',amount:2,unit:'tsp'},
  {name:'Beef sausages',prep:'halved',amount:500,unit:'g'},
  {name:'Tinned chopped tomatoes',amount:400,unit:'g'},
  {name:'Tinned cherry tomatoes',amount:400,unit:'g'},
  {name:'Tinned chickpeas',amount:400,unit:'g'},
  {name:'Free-range eggs',amount:5,unit:'whole'},
  {name:'Persian feta',amount:180,unit:'g'},
  {name:'Za\'atar',amount:3,unit:'tbsp'},
  {name:'Pita bread',amount:4,unit:'whole'},
  {name:'Parsley',prep:'roughly chopped',amount:1,unit:'handful'},
],
steps:[
  'Place a large frying pan over medium-high heat. Add the olive oil, onion, garlic, and pepper with a good pinch of salt. Cook, stirring often, until slightly softened.',
  'Add the sausages and spices and cook, stirring often, for a further 2 minutes.',
  'Add the chopped tomatoes, cherry tomatoes, and chickpeas. Simmer for 10 minutes to cook the sausages.',
  'Crack in the eggs, cover the pan, and simmer over low heat for 10 minutes, until the eggs are just cooked.',
  'Warm the pita in a dry, hot pan and sprinkle over half the za\'atar.',
  'Serve the shakshuka with the feta crumbled over, the remaining za\'atar, and parsley scattered on top.',
]},

{id:134,name:'Blackened Chicken with Spiced Honey Butter and Wedge Salad',category:'Meat & Poultry',difficulty:'medium',serves:4,time:'60 min',calories:620,mainIngredient:'Chicken',
ingredients:[
  {name:'Spatchcock chicken',amount:1,unit:'whole'},
  {name:'Banana shallots',amount:6,unit:'whole'},
  {name:'Butter',amount:2,unit:'tbsp'},
  {name:'Garlic cloves',prep:'sliced',amount:4,unit:'cloves'},
  {name:'Red wine vinegar',amount:3,unit:'tbsp'},
  {name:'Honey',amount:2,unit:'tbsp'},
  {name:'Olive oil',amount:2,unit:'tbsp'},
  {name:'Black pepper',amount:2,unit:'tbsp'},
  {name:'Cumin',amount:1,unit:'tbsp'},
  {name:'Coriander',amount:1,unit:'tbsp'},
  {name:'Chilli powder',amount:1,unit:'tbsp'},
  {name:'Paprika',amount:1,unit:'tbsp'},
  {name:'Salt',amount:1,unit:'tbsp'},
  {name:'Gem lettuces',amount:4,unit:'whole'},
  {name:'Fresh dill',amount:1,unit:'bunch'},
  {name:'Fresh parsley',amount:1,unit:'bunch'},
  {name:'Lemon juice',amount:1,unit:'whole'},
  {name:'Greek yoghurt',amount:6,unit:'tbsp'},
  {name:'Tahini',amount:2,unit:'tbsp'},
  {name:'Extra virgin olive oil',amount:100,unit:'ml'},
  {name:'Spring onion',prep:'sliced',amount:1,unit:'whole'},
],
steps:[
  'Make the spice mix and marinate the chicken, reserving 1 tablespoon for the pan sauce later.',
  'Heat an ovenproof pan over medium heat. Add olive oil and place the chicken skin-side down for about 7 minutes until well coloured. Turn and cook for a further 3 minutes.',
  'Remove the chicken from the pan and add the shallots cut-side down. Sit the chicken back on top and roast for 30 minutes at 200°C, or until cooked through.',
  'For the dressing, blitz parsley, dill, olive oil, tahini, garlic, lemon juice and 2 tbsp water until smooth and bright green. Fold into the yoghurt and season.',
  'Give the lettuce wedges an ice bath and drain until dry. Drizzle with the green yoghurt dressing and garnish with spring onion, sesame seeds and chilli flakes.',
  'While the chicken rests, add butter, sliced garlic and reserved spice mix to the pan. Cook 2 minutes, scraping up the base. Remove from heat and stir in honey and red wine vinegar.',
  'Serve the warm sauce over the blackened chicken and sticky shallots alongside the wedge salad.',
]},

{id:135,name:'Tasty Chicken',category:'Meat & Poultry',difficulty:'easy',serves:4,time:'40 min',calories:310,mainIngredient:'Chicken',
ingredients:[
  {name:'Chicken thighs',amount:4,unit:'whole'},
  {name:'Turmeric',amount:1,unit:'tsp'},
  {name:'Garlic cloves',prep:'crushed',amount:2,unit:'cloves'},
  {name:'Paprika',amount:1,unit:'tsp'},
  {name:'Cumin',amount:1,unit:'tsp'},
  {name:'Ground black pepper',amount:0.5,unit:'tsp'},
  {name:'Salt',amount:1,unit:'tsp'},
  {name:'Fish sauce',amount:1,unit:'tbsp'},
  {name:'Dijon mustard',amount:0.5,unit:'tbsp'},
  {name:'Honey',amount:1,unit:'tsp'},
  {name:'Olive oil',amount:1,unit:'tbsp'},
  {name:'Lemon juice',amount:2,unit:'tsp'},
],
steps:[
  'Combine all ingredients except the chicken and half the lemon juice. Add the chicken and coat thoroughly.',
  'Place the chicken and marinade into a small baking dish and cook for 15 minutes at 200°C.',
  'Turn the chicken over and cook for a further 15 minutes.',
  'Remove from oven, place the chicken and all cooking juices in a bowl, and let cool for 20 minutes.',
  'Shred or chop the chicken and mix with the remaining 1 tsp lemon juice. Adjust seasoning with extra salt if needed.',
]},

// ── VEGETARIAN ───────────────────────────────────────────
{id:136,name:'Miso Garlic Butter Cabbage with Braised Butter Beans',category:'Vegetarian',difficulty:'medium',serves:4,time:'50 min',calories:360,mainIngredient:'Cabbage',
ingredients:[
  {name:'Pointed cabbage',amount:1,unit:'whole'},
  {name:'Neutral oil',amount:2,unit:'tbsp'},
  {name:'Salted butter',amount:50,unit:'g'},
  {name:'White miso paste',amount:1,unit:'tsp'},
  {name:'Garlic cloves',prep:'minced',amount:4,unit:'cloves'},
  {name:'Smoked paprika',amount:1,unit:'tsp'},
  {name:'Shallot',prep:'finely diced',amount:1,unit:'whole'},
  {name:'Fresh parsley',prep:'finely chopped',amount:1,unit:'bunch'},
  {name:'Cider vinegar',amount:1,unit:'tbsp'},
  {name:'Butter beans',amount:570,unit:'g'},
  {name:'Nutritional yeast',amount:1,unit:'tbsp'},
  {name:'Lemon',prep:'zested',amount:0.5,unit:'whole'},
  {name:'Chilli crisp',amount:1,unit:'to serve'},
],
steps:[
  'Preheat your oven and prepare a frypan.',
  'Halve the pointed cabbage and drizzle with neutral oil. Season with salt and pepper.',
  'Mix the salted butter, white miso paste, minced garlic, and smoked paprika to make the miso-garlic butter.',
  'Sear the cabbage in the frypan until golden on the cut sides, then transfer to the oven.',
  'Roast the cabbage, basting occasionally with the miso-garlic butter, until tender and caramelised.',
  'Meanwhile, sauté the diced shallot and minced garlic in a little oil until soft.',
  'Add the chopped parsley, cider vinegar, drained butter beans, nutritional yeast, and lemon zest. Stir gently and heat through until creamy.',
  'Serve the roasted cabbage on top of the braised butter beans.',
  'Garnish with finely diced chives, toasted sesame seeds, and a spoon of chilli crisp before serving.',
]},

// ── PASTA & RICE ─────────────────────────────────────────
{id:137,name:'Mussel and \'Nduja Pasta',category:'Pasta & Rice',difficulty:'medium',serves:4,time:'35 min',calories:520,mainIngredient:'Mussels',
ingredients:[
  {name:'Fresh mussels',amount:1,unit:'kg'},
  {name:'\'Nduja sausage',amount:100,unit:'g'},
  {name:'Pasta of choice',amount:400,unit:'g'},
  {name:'Olive oil',amount:2,unit:'tbsp'},
  {name:'Garlic cloves',prep:'chopped',amount:3,unit:'cloves'},
  {name:'White wine',amount:100,unit:'ml'},
  {name:'Cherry tomatoes',amount:200,unit:'g'},
  {name:'Fresh parsley',amount:1,unit:'handful'},
  {name:'Salt and pepper',amount:1,unit:'to taste'},
],
steps:[
  'Clean and debeard the mussels thoroughly, discarding any that are open and do not close when tapped.',
  'Heat olive oil in a large pan over medium heat and sauté chopped garlic until fragrant.',
  'Add the \'nduja sausage, breaking it up with a spoon, and cook until it releases its oils.',
  'Pour in a splash of white wine and allow it to reduce slightly.',
  'Add the cherry tomatoes and cook until they begin to soften.',
  'Toss in the cleaned mussels, cover the pan, and cook for 3–4 minutes until all the mussels open.',
  'Meanwhile, cook the pasta in salted water until al dente, then drain.',
  'Add the cooked pasta to the pan with the mussels and toss to coat in the sauce.',
  'Finish with freshly chopped parsley, season with salt and pepper, and serve immediately.',
]},

// ── SIDES ─────────────────────────────────────────────────
{id:138,name:'Carrot Tarte Tatin',category:'Sides',difficulty:'medium',serves:6,time:'90 min',calories:320,mainIngredient:'Carrots',
ingredients:[
  {name:'Carrots',amount:6,unit:'whole'},
  {name:'Honey',amount:2,unit:'tbsp'},
  {name:'Apple cider vinegar',amount:1.5,unit:'tsp'},
  {name:'Orange juice',amount:1.5,unit:'tsp'},
  {name:'Cold butter',amount:2,unit:'tbsp'},
  {name:'Orange zest',amount:1,unit:'to taste'},
  {name:'Fresh thyme',amount:1,unit:'sprig'},
  {name:'Puff pastry sheet',amount:1,unit:'sheet'},
  {name:'Crumbled feta cheese',amount:60,unit:'g'},
  {name:'Olive oil',amount:1,unit:'tbsp'},
  {name:'Flaky sea salt',amount:1,unit:'to taste'},
],
steps:[
  'Preheat the oven to 150°C (300°F) convection.',
  'Peel and cut the carrots lengthways, place them in the oven and roast until tender but still with a slight bite in the centre.',
  'Once the carrots are cooked, increase the oven temperature to 175°C (350°F).',
  'In a 20cm pan, combine the honey, apple cider vinegar, and orange juice. Cook over medium-high heat without stirring until it reduces and thickens into a syrup.',
  'Lower the heat to medium-low and add cold butter, stirring until it melts and forms a smooth caramel. If it splits, add 1 tsp cold water and whisk until it comes back together.',
  'Stir in orange zest and fresh thyme, then arrange the roasted carrots in the pan.',
  'Cover the carrots with puff pastry, tucking the edges around the filling. Prick a few holes to let steam escape, then bake at 175°C until the pastry is puffed and golden brown.',
  'Remove from the oven and let rest for about 30 minutes.',
  'Flip the tart onto a plate to serve. If it sticks, warm the pan briefly over low heat.',
  'Finish with crumbled feta, fresh thyme, a drizzle of olive oil, and a sprinkle of flaky sea salt.',
]},

{id:139,name:'Potato Galette',category:'Sides',difficulty:'medium',serves:4,time:'60 min',calories:380,mainIngredient:'Potato',
ingredients:[
  {name:'Sebago potatoes',prep:'peeled and thinly sliced',amount:2,unit:'whole'},
  {name:'Salt and pepper',amount:1,unit:'to taste'},
  {name:'Clarified butter, melted',amount:500,unit:'g'},
],
steps:[
  'Preheat the oven to 160°C.',
  'Line a small ovenproof frying pan or skillet with baking paper.',
  'Using a mandolin set to 3mm, slice the potatoes on the short end.',
  'Place the slices into a medium mixing bowl, drizzle with clarified butter until well coated, and season with salt.',
  'Arrange the slices on the baking paper in overlapping circles.',
  'Pour a little more clarified butter over the top and cover with baking paper.',
  'Bake for about 40 minutes until golden brown, crispy, and the potatoes are cooked through.',
  'Remove the galette from the baking tray and season with salt to serve.',
]},

// ── SAUCES ────────────────────────────────────────────────
{id:140,name:'Copy Cat Lori-Jayne AP Sauce',category:'Sauces',difficulty:'hard',serves:8,time:'75 min',calories:180,mainIngredient:'Cream',
ingredients:[
  {name:'Butter',amount:4,unit:'tbsp'},
  {name:'Shallots',amount:6,unit:'whole'},
  {name:'Garlic cloves',amount:6,unit:'cloves'},
  {name:'Cognac',amount:30,unit:'ml'},
  {name:'White wine',amount:250,unit:'ml'},
  {name:'Soy sauce',amount:24,unit:'g'},
  {name:'Black vinegar',amount:10,unit:'g'},
  {name:'Kecap manis',amount:30,unit:'g'},
  {name:'Sherry vinegar',amount:15,unit:'g'},
  {name:'Fish sauce',amount:7,unit:'g'},
  {name:'Lemon juice',amount:12,unit:'g'},
  {name:'Chicken stock',amount:500,unit:'ml'},
  {name:'Heavy cream',amount:250,unit:'ml'},
  {name:'Fresh thyme',amount:2,unit:'sprigs'},
  {name:'Red Sichuan peppercorns',amount:2,unit:'tbsp'},
  {name:'Green Sichuan peppercorns',amount:2,unit:'tbsp'},
  {name:'Black peppercorns',amount:2,unit:'tbsp'},
],
steps:[
  'Add shallots and butter to a cold pan.',
  'Cook shallots over low heat for 30–35 minutes until deeply softened.',
  'Add minced garlic, turn heat back up to medium and cook until fragrant.',
  'Add 1 shot of cognac and let it cook off.',
  'Add the white wine and let all alcohol cook off completely.',
  'Add soy sauce, black vinegar, kecap manis, sherry vinegar, fish sauce, and lemon juice.',
  'Add chicken stock and cook down for about 20 minutes to reduce by roughly half.',
  'Add heavy cream and thyme. Bring to a boil, then cut the heat.',
  'Strain the sauce through a fine sieve.',
  'Gently toast the peppercorns until fragrant, then blend and stir into the sauce to taste.',
  'Serve warm.',
]},

// ── DESSERTS ──────────────────────────────────────────────
{id:141,name:'Strawberry & Champagne Jelly with White Chocolate Panna Cotta',category:'Desserts',difficulty:'hard',serves:4,time:'4 hr 30 min',calories:480,mainIngredient:'Cream',
ingredients:[
  {name:'Thickened cream',amount:300,unit:'g'},
  {name:'Caster sugar',amount:55,unit:'g'},
  {name:'Vanilla paste',amount:0.5,unit:'tbsp'},
  {name:'White chocolate',amount:140,unit:'g'},
  {name:'Gold-strength gelatine leaves',amount:3,unit:'whole'},
  {name:'Greek yoghurt',amount:125,unit:'g'},
  {name:'Strawberry juice',amount:100,unit:'ml'},
  {name:'Champagne or sparkling wine',amount:100,unit:'ml'},
],
steps:[
  'Place the cream, 40g sugar, and vanilla in a small saucepan and stir over medium heat until just beginning to simmer. Remove from the heat.',
  'Add the white chocolate and whisk until completely melted and smooth.',
  'Soak 1 gelatine leaf in cold water until softened. Squeeze out excess water, then stir into the warm cream mixture until fully dissolved.',
  'Transfer to a bowl and allow to cool to room temperature. Add the Greek yoghurt and whisk until smooth.',
  'Divide evenly between four serving glasses. Refrigerate for at least 2 hours, or until set.',
  'Combine the strawberry juice, Champagne, and remaining 15g sugar in a small saucepan. Warm gently over low heat, stirring until the sugar dissolves. Do not boil.',
  'Soak 2 gelatine leaves in cold water until softened. Squeeze out excess water, then stir gently into the warm strawberry mixture until dissolved.',
  'Allow the jelly mixture to cool to room temperature. Once the panna cotta has set, carefully pour the jelly over the top of each glass.',
  'Refrigerate for a further 2 hours, or until the jelly is set.',
  'Serve chilled. Best enjoyed on the day it is made.',
]},


// ── SIDES ──────────────────────────────────────────────
{id:142,name:'Easy Greek-Style Lemon Potatoes',category:'Sides',difficulty:'easy',serves:4,time:'55 min',calories:280,mainIngredient:'Potatoes',
ingredients:[
  {name:'Potatoes',amount:800,unit:'g'},
  {name:'Olive oil',amount:60,unit:'ml'},
  {name:'Fresh lemon juice',amount:60,unit:'ml'},
  {name:'Garlic',amount:3,unit:'cloves'},
  {name:'Salt',amount:1,unit:'to taste'},
  {name:'Pepper',amount:1,unit:'to taste'},
  {name:'Water or vegetable broth',amount:120,unit:'ml'},
],
steps:[
  'Preheat the oven to 200°C.',
  'Peel and cut the potatoes into wedges.',
  'Arrange the potato wedges in a single layer in a large baking dish or pan.',
  'In a bowl, whisk together olive oil, lemon juice, minced garlic, salt, pepper, and water or vegetable broth.',
  'Pour the mixture over the potatoes, ensuring they are evenly coated.',
  'Roast in the oven until the edges are crispy and the insides are tender, basting occasionally with the pan juices.',
  'Serve hot.',
]},

{id:143,name:'Spicy Crab Toast',category:'Dips & Starters',difficulty:'easy',serves:4,time:'25 min',calories:240,mainIngredient:'Crab',
ingredients:[
  {name:'Snow crab meat',amount:300,unit:'g'},
  {name:'Jalapeno',amount:1,unit:'whole'},
  {name:'Spring onion',amount:2,unit:'whole'},
  {name:'Pepperoncini',amount:2,unit:'whole'},
  {name:'Capers',amount:1,unit:'tbsp'},
  {name:'Mixed fresh herbs',amount:1,unit:'handful'},
  {name:'Bread',prep:'sliced',amount:4,unit:'whole'},
],
steps:[
  'Prepare the snow crab by cleaning and shredding the meat.',
  'Finely chop the jalapeno, spring onion, and pepperoncini.',
  'Mix the crab meat with the chopped vegetables, capers, and a generous amount of fresh herbs.',
  'Toast slices of bread to your liking.',
  'Spoon the crab mixture onto the toast.',
  'Serve as a classy little snack for your friends.',
]},
{id:144,name:'Dill Caesar Salad',category:'Salads',difficulty:'easy',serves:4,time:'25 min',calories:260,mainIngredient:'Lettuce',
ingredients:[
  {name:'Baby gem lettuce',amount:3,unit:'whole'},
  {name:'Creamy dill Caesar dressing',amount:120,unit:'ml'},
  {name:'Anchovy breadcrumbs',amount:80,unit:'g'},
],
steps:[
  'Prepare the creamy dill Caesar dressing.',
  'Wash and dry the baby gem lettuce, keeping the leaves whole.',
  'Make the anchovy breadcrumbs and toast them until crispy.',
  'Arrange the baby gem lettuce on a plate.',
  'Drizzle generously with the creamy dill Caesar dressing.',
  'Sprinkle the spicy anchovy breadcrumbs over the top.',
  'Serve immediately.',
]},
{id:145,name:'Cioppino (Fisherman\'s Stew)',category:'Soups',difficulty:'medium',serves:6,time:'1 hr',calories:420,mainIngredient:'Seafood',
ingredients:[
  {name:'Mussels',amount:1,unit:'kg'},
  {name:'Olive oil',amount:80,unit:'ml'},
  {name:'Fennel bulbs',prep:'finely sliced',amount:2,unit:'whole'},
  {name:'Fennel seeds',amount:1,unit:'tbsp'},
  {name:'Brown onions',prep:'finely sliced',amount:2,unit:'whole'},
  {name:'Celery stalks',prep:'finely sliced',amount:2,unit:'whole'},
  {name:'Chilli flakes',amount:1,unit:'pinch'},
  {name:'Bay leaves',amount:2,unit:'whole'},
  {name:'Garlic',prep:'crushed',amount:4,unit:'clove'},
  {name:'Chopped tomatoes',amount:800,unit:'g'},
  {name:'Fish stock',amount:1,unit:'L'},
  {name:'Chicken stock',amount:1,unit:'L'},
  {name:'Snapper',prep:'cut into chunks',amount:600,unit:'g'},
  {name:'Raw prawn cutlets',amount:300,unit:'g'},
  {name:'Edenvale Alcohol Removed Pinot Gris',amount:250,unit:'ml'},
  {name:'Flat leaf parsley, chopped',amount:1,unit:'handful'},
  {name:'Crusty bread',amount:1,unit:'whole'},
],
steps:[
  'Begin by scrubbing and debearding your mussels. Set aside.',
  'Heat a large saucepan over medium heat and add olive oil. Once warm, add fennel, fennel seeds, onion, celery, bay leaves and chilli flakes. Cook, stirring occasionally, for 5-8 minutes or until softened.',
  'Add garlic and the Pinot Gris and cook for a further two minutes.',
  'Add tomatoes, stir through, then add both types of stock. Simmer for 20-30 minutes until slightly reduced.',
  'Ladle two cups of the stock into a saute pan with a lid and bring to the boil. Add the mussels and cook for 4 minutes or until opened.',
  'Meanwhile, add the fish and prawns to the large pot to cook for 5 minutes.',
  'Return mussels and their stock to the pan and stir to combine.',
  'Ladle into bowls and garnish with parsley and reserved fennel fronds. Serve with crusty bread and enjoy.',
]},
{id:146,name:'Cantonese Steamed Fish in Under 20 Minutes',category:'Seafood',difficulty:'easy',serves:2,time:'20 min',calories:320,mainIngredient:'Fish',
ingredients:[
  {name:'Whole fresh white fish',prep:'cleaned and scaled',amount:600,unit:'g'},
  {name:'Spring onion',prep:'sliced into 5 cm lengths',amount:2,unit:'whole'},
  {name:'Fresh ginger',prep:'sliced',amount:3,unit:'slice'},
  {name:'Light soy sauce',amount:2,unit:'tbsp'},
  {name:'Shaoxing wine',amount:1,unit:'tbsp'},
  {name:'Sesame oil',amount:1,unit:'tsp'},
  {name:'Vegetable oil',amount:2,unit:'tbsp'},
  {name:'Fresh coriander leaves',amount:1,unit:'handful'},
],
steps:[
  'Clean and pat dry the fish thoroughly. Score each side of the fish with 2-3 diagonal cuts.',
  'Place the ginger slices and half the spring onions both inside the cavity and on top of the fish.',
  'Set up a steamer or a wok with a steaming rack and bring water to a boil.',
  'Place the fish on a heatproof plate and steam over high heat for 8-10 minutes, or until the fish is just cooked through and flakes easily.',
  'Carefully remove the plate from the steamer. Discard the ginger and spring onions used during steaming.',
  'In a small saucepan, heat the vegetable oil until hot.',
  'Scatter the remaining fresh spring onions over the steamed fish.',
  'Pour the hot oil over the fish to sizzle the aromatics.',
  'Drizzle with soy sauce, Shaoxing wine, and sesame oil. Garnish with coriander if desired. Serve immediately.',
]},
{id:147,name:'Thai Basil and Oyster Sauce Pipis',category:'Seafood',difficulty:'easy',serves:4,time:'15 min',calories:230,mainIngredient:'Pipis',
ingredients:[
  {name:'Vegetable oil',amount:1,unit:'tsp'},
  {name:'Garlic cloves',prep:'crushed',amount:3,unit:'clove'},
  {name:'Pipis',amount:1.5,unit:'kg'},
  {name:'Long red chillies',prep:'sliced',amount:2,unit:'whole'},
  {name:'Thai basil leaves',amount:60,unit:'g'},
  {name:'Oyster sauce',amount:3,unit:'tsp'},
  {name:'Caster sugar',amount:1,unit:'tsp'},
],
steps:[
  'Heat a wok over high heat. Add the oil and garlic and cook for 30 seconds until fragrant.',
  'Throw in the pipis and toss quickly.',
  'Add the chilli, Thai basil, oyster sauce and sugar, reserving a little chilli and basil for the end.',
  'Cover with a lid and let everything steam for 2-4 minutes or until the pipis open up.',
  'Remove the lid and toss everything through the sauce.',
  'Finish with the remaining chilli and basil and serve immediately.',
]},
{id:148,name:'Mongolian Beef',category:'Meat & Poultry',difficulty:'medium',serves:4,time:'45 min',calories:560,mainIngredient:'Beef',
ingredients:[
  {name:'Steak',prep:'thinly sliced',amount:720,unit:'g'},
  {name:'Soy sauce',amount:60,unit:'ml'},
  {name:'Cornflour',amount:100,unit:'g'},
  {name:'MSG',amount:1,unit:'pinch'},
  {name:'Bicarbonate of soda',amount:0.5,unit:'tsp'},
  {name:'Cracked white pepper',amount:1,unit:'to taste'},
  {name:'Brown onion',amount:1,unit:'whole'},
  {name:'Spring onions',amount:4,unit:'whole'},
  {name:'Garlic cloves',amount:4,unit:'clove'},
  {name:'Birdseye red chillies',amount:2,unit:'whole'},
  {name:'Fresh ginger, finely grated',amount:1,unit:'thumb'},
  {name:'Tallow or peanut oil for frying',amount:500,unit:'ml'},
  {name:'Water',amount:50,unit:'ml'},
  {name:'Steamed rice',amount:1,unit:'to serve'},
],
steps:[
  'Trim the beef of any excess fat or sinew and slice thinly into strips.',
  'Combine 30 ml of the soy sauce, 2 tablespoons of the cornflour, white pepper, MSG, and bicarb soda in a large bowl. Add the beef and mix well to combine. Cover and refrigerate for 1 to 3 hours to marinate.',
  'Thinly slice the onion. Thickly slice the spring onions, keeping the white and green parts separate. Finely dice the garlic, finely slice the red chilli, and finely grate the ginger. Set aside.',
  'Heat enough tallow or oil in a wok to shallow fry, to 180C. Test with a chopstick, if it bubbles, the oil is ready.',
  'Remove the beef from the fridge and add the remaining cornflour, tossing well to coat.',
  'Fry the beef in batches for 3-4 minutes, then drain on a wire rack over a tray.',
  'Carefully remove most of the oil from the wok. Return the wok to high heat.',
  'Add the onions and stir-fry for 2 minutes, tossing occasionally. Add the spring onion whites, garlic, chilli, and ginger. Toss well and cook for a further minute.',
  'Return the beef to the wok and toss to combine. Add the remaining soy sauce and the water. Bring to a boil and cook for 2 more minutes.',
  'Stir in the spring onion greens. Serve over steamed rice and enjoy.',
]},
{id:149,name:'San Choy Bow',category:'Meat & Poultry',difficulty:'easy',serves:4,time:'30 min',calories:380,mainIngredient:'Beef',
ingredients:[
  {name:'Beef mince',amount:720,unit:'g'},
  {name:'Peanut oil',amount:1,unit:'tbsp'},
  {name:'Garlic cloves',prep:'minced',amount:2,unit:'clove'},
  {name:'Ginger',prep:'finely grated',amount:1,unit:'tbsp'},
  {name:'Small onion',prep:'finely chopped',amount:1,unit:'whole'},
  {name:'Shiitake mushrooms',prep:'diced',amount:100,unit:'g'},
  {name:'Canned water chestnuts, drained and chopped',amount:225,unit:'g'},
  {name:'Soy sauce',amount:2,unit:'tbsp'},
  {name:'Oyster sauce',amount:1,unit:'tbsp'},
  {name:'Hoisin sauce',amount:1,unit:'tbsp'},
  {name:'Rice wine vinegar',amount:1,unit:'tbsp'},
  {name:'Sesame oil',amount:1,unit:'tsp'},
  {name:'Iceberg lettuce leaves, washed and dried',amount:8,unit:'whole'},
  {name:'Spring onions',prep:'sliced thinly',amount:2,unit:'whole'},
  {name:'Fresh coriander leaves',amount:1,unit:'handful'},
],
steps:[
  'Heat the peanut oil in a wok or large frying pan over medium-high heat.',
  'Add the garlic, ginger, and onion. Stir-fry for 1-2 minutes until fragrant and softened.',
  'Add the beef mince and cook, breaking it up with a spatula, until browned.',
  'Stir in the mushrooms and water chestnuts, and cook for another 2-3 minutes.',
  'Add the soy sauce, oyster sauce, hoisin sauce, rice wine vinegar, and sesame oil. Mix well and cook for 2-3 minutes until the sauce thickens and coats the beef mixture.',
  'Spoon the beef mixture into the lettuce leaves.',
  'Garnish with sliced spring onions and coriander. Serve immediately and enjoy.',
]},
{id:150,name:'Chicken with Butter Ponzu',category:'Meat & Poultry',difficulty:'easy',serves:2,time:'25 min',calories:410,mainIngredient:'Chicken',
ingredients:[
  {name:'Chicken thigh',amount:300,unit:'g'},
  {name:'Shimeji mushrooms',amount:80,unit:'g'},
  {name:'Oil',amount:1,unit:'tsp'},
  {name:'Salt',amount:1,unit:'pinch'},
  {name:'Sake',amount:1,unit:'tbsp'},
  {name:'Potato starch',amount:1,unit:'tbsp'},
  {name:'Ponzu',amount:2,unit:'tbsp'},
  {name:'Sugar',amount:1,unit:'tsp'},
  {name:'Soy sauce',amount:1,unit:'tsp'},
  {name:'Butter',amount:5,unit:'g'},
  {name:'Black pepper',amount:1,unit:'to taste'},
  {name:'Chopped green onions',amount:1,unit:'to taste'},
],
steps:[
  'Cut the chicken thigh into bite-sized pieces. Rub in the marinade ingredients.',
  'Trim off the base of the shimeji mushrooms and separate them.',
  'Heat the oil in a pan and cook the chicken skin-side down.',
  'Once browned, flip the chicken and add the shimeji mushrooms.',
  'When everything is cooked through, add the sauce ingredients.',
  'Simmer lightly, then add your favourite toppings.',
]},
{id:151,name:'Grilled Chicken with Hummus and Chilli Oil',category:'Meat & Poultry',difficulty:'easy',serves:4,time:'30 min',calories:480,mainIngredient:'Chicken',
ingredients:[
  {name:'Chicken',amount:1,unit:'kg'},
  {name:'Garlic cloves',amount:4,unit:'clove'},
  {name:'Chilli oil',amount:2,unit:'tbsp'},
  {name:'Salt',amount:1,unit:'to taste'},
  {name:'Pepper',amount:1,unit:'to taste'},
  {name:'Dried oregano',amount:1,unit:'tbsp'},
  {name:'Lemon zest',amount:1,unit:'whole'},
  {name:'Lemon juice',amount:1,unit:'tbsp'},
  {name:'Extra virgin olive oil',amount:2,unit:'tbsp'},
  {name:'Hummus',amount:200,unit:'g'},
  {name:'Coriander',amount:1,unit:'handful'},
],
steps:[
  'Marinate the chicken very well for a few hours or ideally overnight.',
  'Cook on the BBQ skin side down for 12-15 minutes, then turn and briefly grill the flesh side. Aim for an internal temperature of 74C to be safe.',
  'Spoon hummus onto your favourite plate and top with lashings of chilli oil and some finely chopped coriander.',
  'Serve with a salad of your choice or your favourite sides. This absolutely slaps and would be great in a wrap too.',
]},
{id:152,name:'Pad Thai with Shrimps and Tofu',category:'Pasta & Rice',difficulty:'medium',serves:2,time:'35 min',calories:520,mainIngredient:'Noodles',
ingredients:[
  {name:'Dried rice noodles',amount:180,unit:'g'},
  {name:'Raw shrimp',prep:'peeled',amount:150,unit:'g'},
  {name:'Firm tofu, cubed',amount:150,unit:'g'},
  {name:'Eggs',amount:2,unit:'whole'},
  {name:'Garlic cloves',prep:'finely chopped',amount:2,unit:'clove'},
  {name:'Shallot',prep:'finely sliced',amount:1,unit:'whole'},
  {name:'Spring onions',prep:'sliced',amount:2,unit:'whole'},
  {name:'Bean sprouts',amount:1,unit:'handful'},
  {name:'Neutral oil for cooking',amount:2,unit:'tbsp'},
  {name:'Tamarind paste',amount:2,unit:'tbsp'},
  {name:'Fish sauce',amount:1.5,unit:'tbsp'},
  {name:'Palm sugar',amount:1,unit:'tbsp'},
  {name:'Oyster sauce',amount:1,unit:'tsp'},
  {name:'Crushed roasted peanuts',amount:2,unit:'tbsp'},
  {name:'Lime wedges',amount:2,unit:'whole'},
  {name:'Sliced bird chilli',amount:1,unit:'whole'},
],
steps:[
  'Prepare the rice noodles according to the package instructions until just tender. Drain and set aside.',
  'Mix together the pad Thai sauce: tamarind paste, fish sauce, palm sugar, and optional oyster sauce.',
  'Heat neutral oil in a wok or large pan over medium-high heat. Add garlic and shallot, and stir-fry until fragrant.',
  'Add tofu cubes and cook until lightly golden. Push to one side of the pan.',
  'Add the shrimp, cooking until pink and just cooked through.',
  'Crack in the eggs and scramble lightly, mixing with the other ingredients.',
  'Add the noodles and the prepared sauce. Toss everything together to coat evenly.',
  'Stir in bean sprouts and spring onions, cooking briefly until just wilted.',
  'Serve hot, topped with crushed roasted peanuts, lime wedges, and sliced bird chilli.',
]},
{id:153,name:'Ossobucco & Risotto alla Milanese',category:'Pasta & Rice',difficulty:'hard',serves:4,time:'2 hr 30 min',calories:680,mainIngredient:'Veal',
ingredients:[
  {name:'Veal shanks',amount:4,unit:'whole'},
  {name:'Onion',amount:1,unit:'whole'},
  {name:'Carrot',amount:1,unit:'whole'},
  {name:'Celery',amount:2,unit:'stalk'},
  {name:'Garlic',amount:2,unit:'clove'},
  {name:'Tomato paste',amount:2,unit:'tbsp'},
  {name:'White wine',amount:250,unit:'ml'},
  {name:'Chicken stock',amount:1.5,unit:'L'},
  {name:'Butter',amount:80,unit:'g'},
  {name:'Olive oil',amount:2,unit:'tbsp'},
  {name:'Saffron',amount:1,unit:'pinch'},
  {name:'Arborio rice',amount:320,unit:'g'},
  {name:'Parmesan cheese',amount:80,unit:'g'},
  {name:'Salt',amount:1,unit:'to taste'},
  {name:'Pepper',amount:1,unit:'to taste'},
  {name:'Lemon zest',amount:1,unit:'whole'},
  {name:'Parsley',amount:1,unit:'handful'},
],
steps:[
  'Season the veal shanks with salt and pepper.',
  'Sear the shanks in a hot pan with olive oil until browned on all sides, then remove and set aside.',
  'In the same pan, saute chopped onion, carrot, celery, and garlic until softened.',
  'Stir in tomato paste and cook briefly, then deglaze the pan with white wine.',
  'Return the shanks to the pan, add chicken stock, and simmer gently until the meat is tender.',
  'Separately, prepare the risotto: heat butter in a pan and toast the Arborio rice.',
  'Gradually add warm chicken stock while stirring continuously until the rice is creamy and al dente.',
  'Stir in saffron threads, butter, and grated Parmesan cheese.',
  'Prepare gremolata by combining lemon zest and parsley.',
  'Serve the ossobucco over the risotto, topped with gremolata.',
]},
{id:154,name:'Asian Greens Cooking Instructions',category:'Sides',difficulty:'easy',serves:8,time:'20 min',calories:60,mainIngredient:'Greens',
ingredients:[
  {name:'Bok choy',amount:10,unit:'bunch'},
  {name:'Chinese broccoli',prep:'cut stalks',amount:10,unit:'bunch'},
  {name:'Choy sum',prep:'cut stalks',amount:10,unit:'bunch'},
],
steps:[
  'To blanch: bring the water to the boil then place the Asian green into the boiled water stalks first.',
  'Blanch them for 1 minute or until the Asian green stalks are soft.',
  'Submerge leaves for 20 seconds then immediately place them into cold water and store in the fridge.',
  'To cook: cook the Asian green on the low heat side of the grill, just until warm and the garlic is still a white colour (not brown or black). Do not overcook.',
]},
{id:155,name:'Spicy Honey Christmas Carrots',category:'Sides',difficulty:'easy',serves:6,time:'40 min',calories:150,mainIngredient:'Carrots',
ingredients:[
  {name:'Carrots',prep:'halved',amount:800,unit:'g'},
  {name:'Gochujang',amount:2,unit:'tbsp'},
  {name:'Honey',amount:2,unit:'tbsp'},
],
steps:[
  'Preheat the oven to a high temperature suitable for roasting.',
  'Cut the carrots in half to create more surface area for charring.',
  'Roast the carrots until their natural sugars caramelise and they develop a smoky, sweet char.',
  'Mix gochujang and honey into a luscious sauce.',
  'Toss the roasted carrots in the gochujang-honey mixture until evenly coated.',
  'Serve hot as a festive side dish.',
]},
{id:156,name:'Easy Greek-Style Lemon Potatoes',category:'Sides',difficulty:'easy',serves:6,time:'1 hr',calories:280,mainIngredient:'Potatoes',
ingredients:[
  {name:'Potatoes',amount:1,unit:'kg'},
  {name:'Olive oil',amount:80,unit:'ml'},
  {name:'Fresh lemon juice',amount:60,unit:'ml'},
  {name:'Garlic',prep:'minced',amount:3,unit:'clove'},
  {name:'Salt',amount:1,unit:'to taste'},
  {name:'Pepper',amount:1,unit:'to taste'},
  {name:'Water or vegetable broth',amount:250,unit:'ml'},
],
steps:[
  'Preheat the oven to 200C.',
  'Peel and cut the potatoes into wedges.',
  'Arrange the potato wedges in a single layer in a large baking dish or pan.',
  'In a bowl, whisk together olive oil, lemon juice, minced garlic, salt, pepper, and water or vegetable broth.',
  'Pour the mixture over the potatoes, ensuring they are evenly coated.',
  'Roast in the oven until the edges are crispy and the insides are tender, basting occasionally with the pan juices.',
  'Serve hot as a flavourful side dish.',
]},
{id:157,name:'Chilli Sauce with Roasted Shrimp Paste',category:'Sauces',difficulty:'medium',serves:8,time:'30 min',calories:60,mainIngredient:'Chilli',
ingredients:[
  {name:'Fresh long red chillis, seeds removed, coarsely chopped',amount:300,unit:'g'},
  {name:'Large garlic cloves, sliced',amount:4,unit:'clove'},
  {name:'Salt',amount:1,unit:'tsp'},
  {name:'Distilled white vinegar',amount:250,unit:'ml'},
  {name:'Palm sugar or castor sugar',amount:2,unit:'tbsp'},
  {name:'Belachan/shrimp paste',amount:20,unit:'g'},
],
steps:[
  'Place the chopped chillis, garlic, salt, and vinegar into a bowl, cover, and let sit overnight to mellow.',
  'Preheat the oven or air fryer to 180C.',
  'Place the piece of shrimp paste into a square of foil, scrunch together to enclose. Roast for 5 minutes until it releases aroma, becomes slightly brown around the edges, and crumbly. If shrimp paste makes you nervous, you can leave it out.',
  'Transfer the chilli and garlic mixture into a saucepan. Add the sugar and roasted shrimp paste.',
  'Bring to a simmer and cook for 5 minutes. Remove from heat and cool to room temperature.',
  'Blend in a food processor until super smooth, then pour into a sterilised bottle or jar.',
  'Seal with a lid and place in the fridge. The sauce will last up to 3 months, but it likely will be eaten long before that.',
  'Enjoy with BBQ chicken or by dipping a cheese toastie into a generous dollop of kewpie topped with the chilli sauce.',
]},
{id:158,name:'Quick Mayonnaise',category:'Sauces',difficulty:'easy',serves:8,time:'5 min',calories:180,mainIngredient:'Egg',
ingredients:[
  {name:'Egg yolks',amount:2,unit:'whole'},
  {name:'Dijon mustard',amount:1,unit:'tbsp'},
  {name:'Lemon, juice of',amount:1,unit:'whole'},
  {name:'Neutral flavoured oil',amount:450,unit:'ml'},
  {name:'Salt',amount:1,unit:'tsp'},
],
steps:[
  'Add everything to a tall jug, then put a stick blender to the bottom.',
  'Turn the stick blender on and after a few seconds start moving the stick blender to the top of the jug until a smooth sauce forms.',
  'If it is too thick, simply add a small amount of room temperature water and mix again until you reach the desired consistency.',
]},
{id:159,name:'Sambal',category:'Sauces',difficulty:'medium',serves:8,time:'45 min',calories:90,mainIngredient:'Ginger',
ingredients:[
  {name:'Ginger',prep:'chopped into thin pieces',amount:1,unit:'kg'},
  {name:'Fresh garlic',amount:150,unit:'g'},
  {name:'Vegetable oil',amount:450,unit:'ml'},
  {name:'White vinegar',amount:250,unit:'ml'},
  {name:'Salt',amount:5,unit:'tbsp'},
  {name:'Lemongrass, defrosted',amount:320,unit:'g'},
  {name:'Fish sauce',amount:125,unit:'ml'},
  {name:'Raw sugar',amount:425,unit:'g'},
  {name:'Coriander roots',prep:'chopped',amount:86,unit:'g'},
  {name:'Sambal oelek',amount:250,unit:'g'},
],
steps:[
  'Part A: slice 1 kilo of ginger using the robot coupe slicing blade. Add salt and garlic, 250 ml of vegetable oil and 250 ml of vinegar, and blend in the robot coupe. Gradually add approximately 140 ml of the remaining vegetable oil (add slowly to avoid splitting). The mixture should be smooth and creamy. Set aside in a large bowl.',
  'Part B: finely chop the coriander roots and place in the blending robot coupe with the remaining ingredients. Blend till smooth but not too much or it will go bright green. Mix it in the bowl with Part A.',
  'Part C: mix the sambal oelek in with the ginger mix.',
  'Cover with cling film and allow to rest for 24 hours in the cool room.',
  'Get the kitchen supervisor to check the sambal before usage. This recipe feeds a lot of people. One person serving would be 100 g of ginger and the portion from there.',
]},
{id:160,name:'Bok Choy Dressing',category:'Sauces',difficulty:'easy',serves:8,time:'5 min',calories:70,mainIngredient:'Soy sauce',
ingredients:[
  {name:'Light soy sauce',amount:500,unit:'ml'},
  {name:'Sweet soy ABC kecap manis',amount:250,unit:'ml'},
  {name:'Sesame oil',amount:250,unit:'ml'},
],
steps:[
  'Mix all ingredients together.',
]},
{id:161,name:'DIY Taramosalata',category:'Dips & Starters',difficulty:'easy',serves:6,time:'15 min',calories:220,mainIngredient:'Cod roe',
ingredients:[
  {name:'Cod roe',amount:100,unit:'g'},
  {name:'Olive oil',amount:200,unit:'ml'},
  {name:'Lemon juice',amount:2,unit:'tbsp'},
  {name:'Bread',amount:3,unit:'slice'},
],
steps:[
  'Prepare the cod roe by removing any membranes if necessary.',
  'Soak the bread in water, then squeeze out the excess liquid.',
  'Blend the cod roe with the soaked bread until smooth.',
  'Slowly drizzle in olive oil while blending to create a creamy emulsion.',
  'Add lemon juice to taste and adjust the seasoning if needed.',
  'Chill before serving with bread or vegetables.',
]},
{id:162,name:'Slow-Cooker Thai-Style Pumpkin Soup',category:'Soups',difficulty:'easy',serves:6,time:'6 hr',calories:280,mainIngredient:'Pumpkin',
ingredients:[
  {name:'Butternut pumpkin',amount:800,unit:'g'},
  {name:'Kent pumpkin',amount:800,unit:'g'},
  {name:'Carrot',amount:1,unit:'whole'},
  {name:'Brown onion',amount:1,unit:'whole'},
  {name:'Curry paste',amount:2,unit:'tbsp'},
  {name:'Vegetable stock',amount:500,unit:'ml'},
  {name:'Coconut milk',amount:400,unit:'ml'},
  {name:'Sugar',amount:1,unit:'tsp'},
  {name:'Lime juice',amount:1,unit:'tbsp'},
  {name:'Fish sauce',amount:1,unit:'tbsp'},
  {name:'Coconut cream',amount:60,unit:'ml'},
],
steps:[
  'Place the combined pumpkin, carrot, onion, curry paste, stock and coconut milk in a slow cooker.',
  'Cover and cook for 4 hours on high (or 6 hours on low) or until the pumpkin is tender and mixture thickens slightly.',
  'Set aside to cool slightly.',
  'Use a stick blender to carefully blend the pumpkin mixture until smooth.',
  'Stir in sugar, lime juice and fish sauce. Season.',
  'Ladle the soup evenly among serving bowls.',
  'Drizzle with coconut cream. Season.',
]},
{id:163,name:'New York Style Pepperoni & Hot Honey Pizza',category:'Bread & Bakes',difficulty:'medium',serves:4,time:'48 hr',calories:850,mainIngredient:'Pepperoni',
ingredients:[
  {name:'Bread flour',amount:700,unit:'g'},
  {name:'Wholemeal flour',amount:300,unit:'g'},
  {name:'Cooking salt',amount:25,unit:'g'},
  {name:'Olive oil',amount:30,unit:'ml'},
  {name:'Sugar',amount:20,unit:'g'},
  {name:'Dry yeast',amount:5,unit:'g'},
  {name:'Water',amount:570,unit:'ml'},
  {name:'Tinned tomatoes',amount:2,unit:'tin'},
  {name:'Salt',amount:10,unit:'g'},
  {name:'Sugar',amount:5,unit:'g'},
  {name:'Dried oregano',amount:2,unit:'g'},
  {name:'Low-moisture mozzarella',prep:'grated',amount:400,unit:'g'},
  {name:'Pepperoni',prep:'sliced',amount:400,unit:'g'},
  {name:'Hot honey',amount:1,unit:'to taste'},
  {name:'Fresh basil',amount:1,unit:'handful'},
  {name:'Parmesan cheese',amount:1,unit:'to taste'},
],
steps:[
  'In a large bowl, combine bread flour, wholemeal flour, 20g sugar, dry yeast, and 570ml water. Mix by hand, then add 30ml olive oil and 25g salt. Knead briefly to distribute.',
  'Knead on your workbench for 8-10 minutes until smooth. Cover and refrigerate for 48 hours.',
  'Three hours before baking, remove from the fridge, divide into 400g portions, roll into tight balls, place on a greased tray, and prove at room temperature for 2-3 hours.',
  'Preheat your oven to 400 degrees C at least an hour ahead to heat-soak. Note: NY-style pizzas bake at lower temps than Neapolitan — some shops go as low as 330 degrees C. Experiment to find what works best.',
  'Blend tinned tomatoes with 10g salt, 5g sugar, and dried oregano until smooth. Avoid over-blending to prevent air getting into the sauce.',
  'Stretch the dough to fit your peel or baking surface. Top with tomato sauce, mozzarella, and pepperoni.',
  'Bake for 5-6 minutes until the base is crispy and cheese is golden.',
  'Finish with hot honey, torn basil, and freshly grated Parmesan.',
]},

{id:171,name:'Raw Shellfish and Horseradish',category:'Dips & Starters',difficulty:'hard',serves:4,time:'20 min',calories:180,mainIngredient:'Shellfish',
ingredients:[
  {name:'Fresh shellfish',amount:500,unit:'g'},
  {name:'Fresh horseradish',amount:85,unit:'g'},
  {name:'Garlic clove',amount:1,unit:'clove'},
  {name:'Caster sugar',amount:30,unit:'g'},
  {name:'Brown rice vinegar',amount:125,unit:'ml'},
  {name:'Cottonseed oil',amount:350,unit:'ml'},
  {name:'Egg yolks',amount:2,unit:'whole'},
  {name:'Olive oil',amount:1,unit:'tbsp'},
  {name:'Salt',amount:1,unit:'to taste'},
],
steps:[
  'Blend horseradish, garlic, sugar and vinegar in a blender on high speed until it becomes a thick paste.',
  'With the motor running, carefully drizzle a thin steady stream of cottonseed oil into the spinning paste.',
  'Add egg yolks one at a time and blend on high until incorporated and the mixture thickens.',
  'Shuck oysters, scallops or razorfish and wash away any sand with cold 5% brine if necessary.',
  'Slice the meat into small bite-sized pieces and arrange back in the shell.',
  'Set them on a bed of coarse salt or crushed ice.',
  'Spoon horseradish dressing over the top and finish with a few drops of olive oil and a pinch of salt.',
]},

{id:172,name:'Grilled Caesar Salad',category:'Salads',difficulty:'hard',serves:4,time:'1 hr 15 min',calories:420,mainIngredient:'Lettuce',
ingredients:[
  {name:'Cos lettuce',amount:2,unit:'whole'},
  {name:'2% salt brine',amount:1,unit:'L'},
  {name:'Parmigiano Reggiano',amount:30,unit:'g'},
  {name:'Toast',amount:2,unit:'slice'},
  {name:'Confit garlic cloves',amount:25,unit:'g'},
  {name:'Raw garlic clove',amount:1,unit:'clove'},
  {name:'Egg yolks',amount:2,unit:'whole'},
  {name:'Anchovy fillets',amount:25,unit:'g'},
  {name:'Dijon mustard',amount:2,unit:'tsp'},
  {name:'Brown rice vinegar',amount:50,unit:'ml'},
  {name:'Olive oil',amount:175,unit:'ml'},
  {name:'Lemon juice',amount:1,unit:'tsp'},
],
steps:[
  'For anchovy mayonnaise, blitz garlic, egg yolks, anchovies and mustard in a blender until well combined.',
  'Slowly add olive oil in a thin steady stream until emulsified.',
  'Season with salt and lemon juice.',
  'Split lettuces in half lengthwise and submerge in brine for 1 hour.',
  'Heat a grill or cast-iron pan until very hot.',
  'Make sure the cut surface is dry, oil lightly and sear very hot and very quickly, cut-side down.',
  'Char the surface then flip, cut-side up, and cool to room temperature.',
  'Separate leaves, pat dry and toss with 60-80ml anchovy mayonnaise in a large bowl.',
  'Grate Parmesan over the top, add toast and freshly ground black pepper.',
  'Mix well, adding more dressing if needed.',
  'Serve with a final drizzle of olive oil and light shower of Parmesan.',
]},

{id:173,name:'Potato Salad',category:'Salads',difficulty:'easy',serves:6,time:'1 hr 15 min',calories:320,mainIngredient:'Potatoes',
ingredients:[
  {name:'Large waxy potatoes',amount:2,unit:'kg'},
  {name:'Red wine vinegar',amount:1,unit:'splash'},
  {name:'Eggs',amount:5,unit:'whole'},
  {name:'Celery stalks',amount:3,unit:'whole'},
  {name:'White onion',amount:60,unit:'g'},
  {name:'Onion aioli or mayonnaise',amount:380,unit:'g'},
  {name:'Yellow mustard',amount:2,unit:'tbsp'},
  {name:'Brown rice vinegar',amount:3,unit:'tsp'},
  {name:'Capers',amount:1,unit:'tbsp'},
  {name:'Smoked sweet paprika',amount:0.5,unit:'tsp'},
  {name:'Flaky sea salt',amount:1,unit:'tsp'},
  {name:'Black pepper',amount:1,unit:'to taste'},
],
steps:[
  'Start potatoes in salted cold water with a splash of red wine vinegar over high heat.',
  'Bring to boil, reduce heat to medium and simmer for about 40 minutes until soft enough to mash slightly.',
  'Drain potatoes, slip from skins and chop into bite-sized chunks.',
  'For the dressing, combine aioli, mustard, vinegar, capers and paprika in a bowl.',
  'Season with salt and adjust to taste.',
  'While potatoes are still warm, gently fold in the dressing until well coated.',
  'Fold in chopped hard-boiled eggs, raw celery for crunch and onion for bite.',
  'Cover and refrigerate overnight for best effect.',
  'Let reacclimatise to room temperature before serving.',
]},

{id:174,name:'Raw Kingfish with Burnt Mandarin and Nori Paste',category:'Seafood',difficulty:'hard',serves:4,time:'45 min',calories:320,mainIngredient:'Kingfish',
ingredients:[
  {name:'Kingfish fillet',amount:500,unit:'g'},
  {name:'Mandarin orange',amount:1,unit:'whole'},
  {name:'Caster sugar',amount:40,unit:'g'},
  {name:'Brown rice vinegar',amount:80,unit:'ml'},
  {name:'Tamari',amount:80,unit:'ml'},
  {name:'Toasted sesame oil',amount:1,unit:'tbsp'},
  {name:'Extra-virgin olive oil',amount:1,unit:'tbsp'},
  {name:'Fresh ginger',amount:1,unit:'tbsp'},
  {name:'White onion, grated',amount:1,unit:'tbsp'},
  {name:'Dried nori sheets',amount:6,unit:'whole'},
  {name:'Rice bran oil',amount:125,unit:'ml'},
  {name:'Brown onion',amount:1,unit:'whole'},
  {name:'Lebanese cucumber',amount:1,unit:'whole'},
  {name:'Flaky sea salt',amount:1,unit:'tbsp'},
],
steps:[
  'For tamari-vinegar dressing, cook sugar and 60ml water over high heat to dark caramel.',
  'Remove from heat, stir in vinegar and cool to room temperature.',
  'Add sesame oil, olive oil, ginger and grated onion.',
  'For nori paste, toast nori sheets until crisp, cool and break into pieces.',
  'Heat oil over low heat, add finely diced onion and cook until relaxed.',
  'Pour over nori, cover and let sit 1 hour to soften completely, then blend until smooth.',
  'For cucumber pickle, toss sliced cucumber with sugar and salt and let sit 1 hour.',
  'Add vinegar and mix well, then strain.',
  'Slice kingfish into 5mm slices with sharpest knife.',
  'Sear mandarin cut-side down on hot grill or pan until highly caramelised.',
  'Arrange cucumber on plate, top with fish, add nori paste and mandarin kosho.',
  'Dress fish liberally with tamari vinegar dressing.',
  'Squeeze caramelised mandarin juice over everything and serve.',
]},

{id:175,name:'T-Bone Steak Marinated in Koji',category:'Meat & Poultry',difficulty:'medium',serves:2,time:'30 min',calories:680,mainIngredient:'Steak',
ingredients:[
  {name:'T-bone steak',amount:1.2,unit:'kg'},
  {name:'Koji paste',amount:100,unit:'g'},
  {name:'Olive oil',amount:2,unit:'tbsp'},
  {name:'Flaky sea salt',amount:1,unit:'to taste'},
  {name:'Black pepper',amount:1,unit:'to taste'},
],
steps:[
  'Rub steak all over with koji paste and marinate in fridge for at least 1 hour but no longer than overnight.',
  'Fire up wood grill with white hot glowing coals.',
  'Scrape as much koji off the steak as possible as it burns easily.',
  'Brush steak with olive oil and season well with flaky sea salt.',
  'Grill on one side until deep golden brown crust forms, about 5-10 minutes.',
  'Turn over and cook the other side for 5-10 minutes, aiming for 52°C internal temperature.',
  'Before removing from grill, brush a little marinade back on and caramelise quickly, about 1 minute per side.',
  'Rest steak in warm spot for 10 minutes then slice and serve with olive oil and black pepper.',
]},

{id:176,name:'Roast Cauliflower with Almond Sauce and Mint',category:'Sides',difficulty:'hard',serves:4,time:'1 hr',calories:280,mainIngredient:'Cauliflower',
ingredients:[
  {name:'Whole cauliflower',amount:1,unit:'whole'},
  {name:'2% salt brine',amount:2,unit:'L'},
  {name:'Extra-virgin olive oil',amount:3,unit:'tbsp'},
  {name:'Lemon juice',amount:2,unit:'tbsp'},
  {name:'Fresh mint leaves',amount:50,unit:'g'},
  {name:'Roasted almonds',amount:80,unit:'g'},
  {name:'Almond meal',amount:100,unit:'g'},
  {name:'Brown rice vinegar',amount:1,unit:'tbsp'},
  {name:'Egg yolks',amount:2,unit:'whole'},
],
steps:[
  'For almond sauce, spread almond meal on baking tray and roast at 180°C for 5 minutes until lightly golden.',
  'Mix roasted meal with 150ml water and heat gently to 50°C.',
  'Blend to smooth paste, season with vinegar and salt.',
  'With motor running, add egg yolks then slowly drizzle oil in thin stream.',
  'Remove tough outer leaves from cauliflower and submerge in brine for 2 hours.',
  'Drain well and steam over boiling water for about 10 minutes until tender.',
  'Cool to room temperature then cut in half.',
  'Roast in large pan cut-side down at 220°C for 10-15 minutes until dark golden brown.',
  'Spoon almond sauce onto plate and prop cauliflower on top.',
  'Dress with olive oil, lemon juice, salt and black pepper.',
  'Finish with mint and chopped almonds.',
]},

{id:177,name:'Roasted Pineapple with Star Anise',category:'Desserts',difficulty:'medium',serves:6,time:'1 hr',calories:240,mainIngredient:'Pineapple',
ingredients:[
  {name:'Whole pineapple',amount:1,unit:'whole'},
  {name:'Brown sugar',amount:185,unit:'g'},
  {name:'Star anise',amount:6,unit:'whole'},
  {name:'Dried chilli flakes',amount:20,unit:'g'},
  {name:'Flaky sea salt',amount:20,unit:'g'},
  {name:'Lime',amount:1,unit:'whole'},
],
steps:[
  'Remove pineapple skin attractively and massage all over with brown sugar.',
  'Place on rotisserie over coals or on wire rack in oven at 200°C.',
  'Add star anise, 500ml water and any excess sugar to dripping tray below.',
  'Baste pineapple liberally with liquid as it rotates or roasts.',
  'Cook until darkly caramelised and tender, about 30 minutes.',
  'Cool to room temperature.',
  'If using oven, turn grill to high and cook, turning and basting every few minutes until caramelised.',
  'Heat heavy-based frying pan over high heat, add lime cut-side down and cook until deeply caramelised, about 5 minutes.',
  'Slice pineapple off core into bite-sized pieces.',
  'Mix chilli and salt together for dipping.',
  'Serve pineapple with chilli-salt mixture and caramelised lime for squeezing.',
]},

{id:178,name:'Roasted Mango',category:'Desserts',difficulty:'easy',serves:4,time:'30 min',calories:280,mainIngredient:'Mango',
ingredients:[
  {name:'Large ripe mangoes',amount:2,unit:'whole'},
  {name:'Dark brown sugar',amount:100,unit:'g'},
  {name:'Pure cream',amount:125,unit:'ml'},
  {name:'Coconut cream',amount:125,unit:'ml'},
  {name:'Lime or lemon wedges',amount:2,unit:'whole'},
  {name:'Flaky sea salt',amount:1,unit:'to taste'},
],
steps:[
  'Cut four cheeks from mangoes keeping skin on.',
  'Score flesh side with sharp knife in crisscross pattern, cutting halfway to skin.',
  'Coat flesh with brown sugar, giving each cheek a flex to open cuts and let sugar in.',
  'Cut and scrape mango flesh from pit and puree until smooth.',
  'Whisk cream and coconut cream to soft peaks then fold through puree.',
  'Heat cast-iron pan over high heat until smoking.',
  'Lay mango cheeks in flesh-side down.',
  'Give them half a minute on stove then place pan straight in 220°C oven.',
  'Cook 3-4 minutes until softened and surrounded by caramelised sugar.',
  'Cool to room temperature.',
  'Eat with spoon straight from skin, seasoned with salt, lime juice and whipped mango fool.',
]},

{id:164,name:'Green Bean Salad with Anchovy and Mustard Dressing',category:'Salads',difficulty:'medium',serves:4,time:'30 min',calories:220,mainIngredient:'Green Beans',
ingredients:[
  {name:'Fine green beans',amount:500,unit:'g'},
  {name:'Garlic clove',amount:1,unit:'clove'},
  {name:'Anchovy fillets',amount:12,unit:'whole'},
  {name:'Red wine vinegar',amount:1,unit:'tbsp'},
  {name:'Dijon mustard',amount:1,unit:'tbsp'},
  {name:'Egg yolk',amount:1,unit:'whole'},
  {name:'Extra virgin olive oil',amount:3,unit:'tbsp'},
  {name:'Olive oil',amount:3,unit:'tbsp'},
  {name:'Fresh basil leaves',amount:6,unit:'whole'},
  {name:'Radishes',prep:'finely sliced',amount:2,unit:'whole'},
  {name:'Black pepper',amount:1,unit:'to taste'},
],
steps:[
  'Using a mortar and pestle, crush the garlic to a pulp. Add 6 of the anchovy fillets and pound to a smooth paste, then transfer to a bowl.',
  'Add the vinegar, mustard and egg yolk to the anchovy paste and whisk well to form a thick paste.',
  'Slowly add the oils, whisking continuously to incorporate and emulsify.',
  'Bring a large saucepan of generously salted water to the boil. Plunge half the beans into the water and cook until al dente, then remove with a slotted spoon and plunge into iced water.',
  'Repeat with the remainder of the beans. When cold, pat dry and transfer to a bowl.',
  'Tear the basil leaves over the beans and add the radishes and 4 tablespoons of the anchovy dressing.',
  'Using your hands, toss the salad until the beans are well coated.',
  'Lay the salad on a serving plate. Cut the remaining anchovy fillets in half lengthwise and arrange over the salad.',
  'Dust generously with freshly ground black pepper and serve.',
]},

{id:165,name:'Cracked Wheat and Freekeh Salad with Preserved Lemon and Barberries',category:'Salads',difficulty:'hard',serves:4,time:'1 hr 15 min',calories:380,mainIngredient:'Freekeh',
ingredients:[
  {name:'Natural yoghurt',amount:400,unit:'ml'},
  {name:'Salt',amount:1,unit:'pinch'},
  {name:'Butter',amount:60,unit:'g'},
  {name:'Celery stalks',amount:2,unit:'whole',prep:'finely chopped'},
  {name:'Golden shallots',amount:2,unit:'whole',prep:'finely chopped'},
  {name:'Garlic clove',amount:1,unit:'clove',prep:'finely chopped'},
  {name:'Cracked wheat',amount:80,unit:'g'},
  {name:'Freekeh',amount:80,unit:'g',prep:'soaked'},
  {name:'Water',amount:380,unit:'ml'},
  {name:'Water',amount:250,unit:'ml'},
  {name:'Barberries',amount:2,unit:'tbsp'},
  {name:'Caraway water or ground caraway seeds',amount:1,unit:'tbsp'},
  {name:'Chardonnay vinegar',amount:2.5,unit:'tsp'},
  {name:'Extra virgin olive oil',amount:1.5,unit:'tbsp'},
  {name:'Preserved lemon',amount:0.5,unit:'tsp',prep:'finely chopped'},
  {name:'Toasted almonds',amount:80,unit:'g',prep:'chopped'},
  {name:'Spring onions',amount:4,unit:'whole',prep:'finely sliced'},
  {name:'Fresh mint',amount:1,unit:'handful',prep:'shredded'},
  {name:'Fresh parsley',amount:1,unit:'handful',prep:'shredded'},
],
steps:[
  'Season yoghurt with a pinch of salt, line a small sieve with muslin or clean cloth, place yoghurt in the sieve over a bowl, cover and refrigerate for 6 hours or overnight to drain.',
  'Divide butter, celery, shallot and garlic equally between two medium lidded saucepans. Place over low heat and sweat the vegetables for a few minutes.',
  'Add the bulgur to one pan and drained freekeh to the other. Stir to ensure each grain is covered with butter, then add 190ml water to each pan, bring to the boil and cover with cartouche and lid.',
  'Cook gently on the stovetop for about 12 minutes, checking and tasting until the grains are tender. Spread out on a board or plate to cool quickly.',
  'Pour 250ml warm water over barberries and leave to soak for 10 minutes. Strain barberries, reserving 3 tablespoons of the soaking liquid.',
  'Add strained barberries to the soaking liquid with caraway water, chardonnay vinegar, olive oil and salt. Set aside.',
  'When grains are cold, mix together the cooked bulgur and freekeh. Combine with the barberry vinaigrette.',
  'Arrange the grain mixture on a serving plate. Top with labne, preserved lemon, toasted almonds, spring onions, mint and parsley.',
  'Drizzle with additional olive oil and serve.',
]},
{id:166,name:'Carrot Tarte Tatin',category:'Sides',difficulty:'medium',serves:4,time:'1 hr 15 min',calories:350,mainIngredient:'Carrot',
ingredients:[
  {name:'Carrots',amount:6,unit:'whole'},
  {name:'Honey',amount:2,unit:'tbsp'},
  {name:'Apple cider vinegar',amount:1,unit:'tbsp'},
  {name:'Orange juice',amount:1,unit:'tbsp'},
  {name:'Cold butter',amount:2,unit:'tbsp'},
  {name:'Orange zest',amount:1,unit:'tsp'},
  {name:'Fresh thyme',amount:4,unit:'sprigs'},
  {name:'Puff pastry',amount:1,unit:'sheet'},
  {name:'Cold water',amount:1,unit:'tsp'},
  {name:'Crumbled feta cheese',amount:100,unit:'g'},
  {name:'Olive oil',amount:2,unit:'tbsp'},
  {name:'Flaky sea salt',amount:1,unit:'to taste'},
],
steps:[
  'Preheat the oven to 150°C (convection) and peel the carrots, cutting them lengthways.',
  'Roast the carrots in the oven until tender but still with a slight bite in the centre.',
  'Increase the oven temperature to 175°C.',
  'In a 20cm pan, combine honey, apple cider vinegar, and orange juice. Cook over medium-high heat without stirring until it reduces into a syrup with excess liquid evaporated.',
  'Lower heat to medium-low, add cold butter, and stir as it melts into a smooth caramel. If it splits, add 1 teaspoon cold water and whisk back together.',
  'Stir in orange zest and fresh thyme, then arrange the roasted carrots in the caramel.',
  'Cover with a sheet of puff pastry, tucking the edges around the filling, and prick a few small holes in the pastry to release steam.',
  'Bake at 175°C until the pastry is puffed and deeply golden brown, then remove and let rest for 30 minutes.',
  'Flip the tart out of the pan onto a plate. If it sticks, warm the pan gently on low heat.',
  'Top with crumbled feta cheese, fresh thyme, a drizzle of olive oil, and a sprinkle of flaky sea salt. Serve.',
]},

{id:167,name:'Vegemite and Cheese Cabbage',category:'Sides',difficulty:'easy',serves:2,time:'45 min',calories:250,mainIngredient:'Cabbage',
ingredients:[
  {name:'Cabbage',amount:1,unit:'whole'},
  {name:'Butter',amount:60,unit:'g'},
  {name:'Vegemite',amount:0.5,unit:'tsp'},
  {name:'Chicken or vegetable stock',amount:90,unit:'ml'},
  {name:'Parmesan',amount:20,unit:'g'},
  {name:'Salt',amount:1,unit:'to taste'},
  {name:'Black pepper',amount:1,unit:'to taste'},
],
steps:[
  'Quarter the cabbage and trim away some of the core.',
  'Combine the softened butter and Vegemite and mix well.',
  'Place the cabbage in an air fryer cake pan.',
  'Smear the butter mixture over the cabbage, add the stock to the pan, and season with salt and pepper.',
  'Cover with foil and cook for 30 minutes at 200°C.',
  'Remove the foil, spoon the cooking juices over the cabbage, and cook at 200°C for a further 5 minutes.',
  'Baste again and cook for another 2 minutes, or until caramelised.',
  'Remove the cabbage from the air fryer, baste with the cooking juices, and sprinkle over the Parmesan.',
]},

{id:168,name:'Fettuccine with Sardines, Cabbage, Garlic, Chilli and Lemon',category:'Pasta & Rice',difficulty:'easy',serves:2,time:'20 min',calories:550,mainIngredient:'Sardines',
ingredients:[
  {name:'Fettuccine',amount:200,unit:'g'},
  {name:'Garlic cloves',amount:3,unit:'clove'},
  {name:'Red chilli',amount:1,unit:'whole'},
  {name:'White cabbage',amount:200,unit:'g',prep:'thinly sliced'},
  {name:'Dry white wine',amount:120,unit:'ml'},
  {name:'Sardines in extra virgin olive oil',amount:2,unit:'tin',prep:'chopped'},
  {name:'Lemon',amount:1,unit:'whole',prep:'zested and juiced'},
  {name:'Butter',amount:20,unit:'g'},
  {name:'Fresh parsley',amount:1,unit:'handful',prep:'chopped'},
],
steps:[
  'Cook the fettuccine in salted boiling water until al dente.',
  'Thinly slice the garlic and chilli.',
  'In a pan, sauté the garlic and chilli in the oil from one tin of sardines until fragrant.',
  'Add the sliced cabbage and cook for a few minutes until softened.',
  'Pour in the white wine and let it reduce slightly.',
  'Add the chopped sardines, lemon zest and juice, and butter. Stir to combine and heat through gently.',
  'Drain the pasta, reserving a little cooking water. Toss with the sardine mixture, adding a splash of cooking water if needed to coat.',
  'Serve topped with chopped parsley.',
]},

{id:169,name:'New York Style Pepperoni and Hot Honey Pizza',category:'Bread & Bakes',difficulty:'hard',serves:4,time:'48 hr',calories:700,mainIngredient:'Pizza Dough',
ingredients:[
  {name:'Bread flour',amount:700,unit:'g'},
  {name:'Wholemeal flour',amount:300,unit:'g'},
  {name:'Salt',amount:25,unit:'g'},
  {name:'Olive oil',amount:30,unit:'ml'},
  {name:'Sugar',amount:20,unit:'g'},
  {name:'Dry yeast',amount:5,unit:'g'},
  {name:'Water',amount:570,unit:'ml'},
  {name:'Tinned tomatoes',amount:2,unit:'tin'},
  {name:'Dried oregano',amount:2,unit:'g'},
  {name:'Low-moisture mozzarella',amount:400,unit:'g',prep:'grated'},
  {name:'Pepperoni',amount:400,unit:'g',prep:'sliced'},
  {name:'Hot honey',amount:4,unit:'tbsp'},
  {name:'Fresh basil',amount:1,unit:'bunch'},
  {name:'Parmesan',amount:1,unit:'to taste'},
],
steps:[
  'Combine bread flour, wholemeal flour, sugar, dry yeast, and water in a large bowl. Mix by hand, then add olive oil and salt. Knead briefly to distribute.',
  'Knead on a workbench for 8-10 minutes until smooth. Cover and refrigerate for 48 hours.',
  'Three hours before baking, remove from the fridge, divide into 400g portions, roll into tight balls, place on a greased tray, and prove at room temperature for 2-3 hours.',
  'Preheat the oven to 400°C at least an hour ahead to heat-soak the baking surface.',
  'Blend tinned tomatoes with a pinch of salt, sugar, and dried oregano until smooth.',
  'Stretch the dough to fit your peel or baking surface. Top with tomato sauce, mozzarella, and pepperoni.',
  'Bake for 5-6 minutes until the base is crispy and the cheese is golden.',
  'Finish with hot honey, torn basil leaves, and freshly grated Parmesan.',
]},

{id:170,name:'High-Protein Chocolate Date Mousse',category:'Desserts',difficulty:'easy',serves:4,time:'15 min',calories:280,mainIngredient:'Dates',
ingredients:[
  {name:'Dates',amount:150,unit:'g'},
  {name:'Chia seeds',amount:60,unit:'g'},
  {name:'Cocoa powder',amount:30,unit:'g'},
  {name:'Greek yoghurt',amount:400,unit:'g'},
  {name:'Milk',amount:150,unit:'ml'},
  {name:'Whey protein powder',amount:1,unit:'scoop'},
  {name:'Vanilla extract',amount:5,unit:'g'},
  {name:'Salt',amount:1,unit:'pinch'},
],
steps:[
  'Combine everything except the chia seeds into a blender and blend until smooth.',
  'Stir in the chia seeds.',
  'Refrigerate for at least 2 hours until set.',
]},

{id:179,name:'Smoked Banana-Skin Flan',category:'Desserts',difficulty:'hard',serves:6,time:'120 min',calories:280,mainIngredient:'Banana',
ingredients:[
  {name:'Eggs',amount:2,unit:'whole'},
  {name:'Egg yolks',amount:4,unit:'whole'},
  {name:'Caster sugar',amount:100,unit:'g'},
  {name:'Banana skins',amount:10,unit:'whole'},
  {name:'Pure cream',amount:1,unit:'litre'},
  {name:'Caster sugar (for caramel)',amount:150,unit:'g'},
  {name:'Water',amount:50,unit:'ml'},
],
steps:[
  'Smoke banana skins over a gentle fire until completely blackened and dehydrated (2-3 days ahead).',
  'Alternatively use a dehydrator or low oven.',
  'Warm cream to 60°C, stir in dried skins and refrigerate overnight to infuse.',
  'Pass cream through a fine sieve before using.',
  'Whisk eggs, yolks and sugar in stand mixer for 4 minutes until combined.',
  'Slowly whisk in 480ml strained banana cream.',
  'Refrigerate overnight to develop flavours.',
  'Make caramel: stir sugar with 50ml water over medium-high heat until dark caramel, about 10 minutes.',
  'Divide caramel among six dariole moulds and coat the sides.',
  'Heat oven to 150°C.',
  'Strain banana cream mixture into moulds.',
  'Set moulds in a water bath, cover with foil, bake until just set with a slight wobble, 35-45 minutes.',
  'Cool to room temperature, then refrigerate for at least 6 hours.',
  'Run a knife around the inside edges and flip out onto serving plates.',
  'Serve chilled.',
]},

{id:180,name:'Salted-Caramel Semifreddo',category:'Desserts',difficulty:'medium',serves:8,time:'30 min',calories:340,mainIngredient:'Cream',
ingredients:[
  {name:'Thickened cream',amount:700,unit:'ml'},
  {name:'Caster sugar (for caramel)',amount:200,unit:'g'},
  {name:'Unsalted butter, diced',amount:100,unit:'g'},
  {name:'Cream (for caramel)',amount:300,unit:'ml'},
  {name:'Sea salt',amount:1,unit:'to taste'},
  {name:'Egg yolks',amount:12,unit:'whole'},
  {name:'Caster sugar (for sabayon)',amount:100,unit:'g'},
  {name:'Water',amount:100,unit:'ml'},
],
steps:[
  'Make salted caramel: combine 200g sugar with 100ml water and cook to very dark caramel without stirring.',
  'Carefully add butter and stir until melted.',
  'Add 300ml cream and bring to a simmer, ensure sugar is dissolved.',
  'Add a good pinch of sea salt.',
  'Cool completely in the fridge.',
  'Make sabayon: whisk 12 egg yolks with 100g sugar over a pot of simmering water (double boiler) until mixture doubles in size and reaches 89°C.',
  'Cool completely in the fridge.',
  'Whip 700ml thickened cream to soft peaks.',
  'Cool all three components completely.',
  'Add sabayon to salted caramel and mix thoroughly.',
  'Gently fold in whipped cream until well combined.',
  'Transfer to a terrine mould lined with plastic wrap.',
  'Freeze for at least 6 hours.',
  'Scoop or slice to serve.',
]},

{id:181,name:'Vanilla Slice',category:'Desserts',difficulty:'hard',serves:8,time:'60 min',calories:380,mainIngredient:'Chocolate',
ingredients:[
  {name:'White chocolate, chopped',amount:345,unit:'g'},
  {name:'Butter, diced and softened',amount:345,unit:'g'},
  {name:'Block cream cheese, room temperature',amount:60,unit:'g'},
  {name:'Iota carrageenan powder',amount:3,unit:'g'},
  {name:'Agar powder',amount:3,unit:'g'},
  {name:'Pure cream',amount:650,unit:'ml'},
  {name:'Vanilla pods',amount:2,unit:'whole'},
  {name:'Gold-strength gelatine leaves',amount:2,unit:'whole'},
  {name:'Inverted puff pastry, defrosted',amount:600,unit:'g'},
  {name:'Egg yolks, beaten',amount:2,unit:'whole'},
  {name:'Water',amount:650,unit:'ml'},
  {name:'Flaky sea salt',amount:1,unit:'to taste'},
],
steps:[
  'For cream filling, place chocolate, butter and cream cheese in a heatproof bowl.',
  'Add iota and agar to 650ml water and blend with stick blender, bring to boil.',
  'Combine cream, vanilla pods and gelatine in a saucepan and bring to a strong simmer.',
  'Pour both mixtures into the chocolate mixture and blend until smooth.',
  'Pour into a container, seal and chill for at least 8 hours or overnight.',
  'On a lightly floured surface, roll pastry to just under 1cm thick.',
  'Cut into two equal rectangles and chill for 20 minutes.',
  'Transfer to baking tray lined with baking paper.',
  'Brush tops with egg yolk, chill until dry, brush again and chill another 20 minutes.',
  'Heat oven to 200°C, bake for 20 minutes until golden.',
  'Reduce heat to 150°C, bake another 15-20 minutes until deep golden caramel colour.',
  'Cool completely on a wire rack.',
  'Whisk chilled cream filling until thick cream consistency.',
  'Pipe a thin strip of cream down the centre of a plate, place pastry on top.',
  'Pipe a very thick layer of vanilla cream over the base pastry.',
  'Crown with the second pastry layer and press down gently for stability.',
  'Cut into slices and serve.',
]},

{id:182,name:'Bullet Tart',category:'Desserts',difficulty:'hard',serves:8,time:'90 min',calories:360,mainIngredient:'Chocolate',
ingredients:[
  {name:'Plain flour',amount:560,unit:'g'},
  {name:'Caster sugar',amount:40,unit:'g'},
  {name:'Malt powder',amount:18,unit:'g'},
  {name:'Unsalted butter, diced and cool',amount:180,unit:'g'},
  {name:'Cream cheese, room temperature',amount:45,unit:'g'},
  {name:'Black food colouring',amount:1,unit:'tsp'},
  {name:'Ice-cold water',amount:115,unit:'ml'},
  {name:'Egg white, beaten',amount:1,unit:'whole'},
  {name:'Soft liquorice',amount:500,unit:'g'},
  {name:'Dark chocolate (70%)',amount:1170,unit:'g'},
  {name:'Water (for ganache)',amount:600,unit:'ml'},
  {name:'Kefir or sour cream',amount:1,unit:'to serve'},
],
steps:[
  'For tart shell, pulse flour, sugar and malt powder in food processor.',
  'Add butter, cream cheese and food colouring, pulse until mixture resembles wet sand.',
  'Pulse in 100-115ml ice-cold water just until dough comes together.',
  'Shape into a ball, flatten into a disc, wrap and chill for 2 hours.',
  'Let pastry come to room temperature, roll to 2mm thick.',
  'Transfer to a 25cm loose-bottomed fluted tart tin, pressing gently into recesses.',
  'Trim edges leaving a slight overhang.',
  'Freeze to chill and relax for at least 1 hour.',
  'Heat oven to 175°C.',
  'Line with baking paper and weights, blind-bake for 15 minutes.',
  'Remove paper and weights, brush with egg white.',
  'Reduce to 150°C, bake another 12 minutes until crisp and golden.',
  'Cool completely before filling.',
  'For ganache, chop liquorice finely.',
  'Heat 600ml water to 80°C, add liquorice and cook until softened, about 15 minutes.',
  'Blend liquorice and water until smooth.',
  'Pour over chopped chocolate in a heatproof bowl and stir until melted.',
  'Cool to 37°C, transfer to stand mixer and beat on medium speed until glossy and room temperature.',
  'Fill tart shell with ganache level with the edge.',
  'Refrigerate for at least 2 hours to set.',
  'Slice while cold and firm, serve with kefir or sour cream.',
]},

{id:183,name:'Egg Yolk and Almond Tart',category:'Desserts',difficulty:'medium',serves:8,time:'75 min',calories:320,mainIngredient:'Almond',
ingredients:[
  {name:'Unsalted butter',amount:250,unit:'g'},
  {name:'Brown sugar',amount:220,unit:'g'},
  {name:'Sea salt',amount:4,unit:'g'},
  {name:'Eggs',amount:2,unit:'whole'},
  {name:'Extra egg yolk (for patching)',amount:1,unit:'whole'},
  {name:'Almond meal (for pastry)',amount:125,unit:'g'},
  {name:'Plain flour',amount:320,unit:'g'},
  {name:'Baking powder',amount:0.25,unit:'tsp'},
  {name:'Egg yolks (for filling)',amount:12,unit:'whole'},
  {name:'Almond meal (for filling)',amount:240,unit:'g'},
  {name:'Sea salt (for filling)',amount:5,unit:'g'},
  {name:'Caster sugar (for syrup)',amount:500,unit:'g'},
  {name:'Water (for syrup)',amount:250,unit:'ml'},
  {name:'Lemon caramel',amount:1,unit:'to serve'},
  {name:'Sour cream, whipped',amount:1,unit:'to serve'},
],
steps:[
  'For pastry, cream butter, brown sugar and 4g salt until pale and smooth.',
  'Add eggs one at a time, ensuring each is fully incorporated.',
  'Reduce speed to low and add almond meal, flour and baking powder.',
  'Mould into a ball with air released, wrap and chill for 1 hour.',
  'Let come to not-quite room temperature, roll between greased baking paper to 5mm thick.',
  'Transfer to a 22cm deep-sided pie tin, gently pressing into bottom and sides.',
  'Trim overhanging pastry, patch any cracks with extra egg yolk.',
  'Chill for half an hour before filling.',
  'For filling, dissolve 500g caster sugar in 250ml water over medium heat, cool to room temperature.',
  'Heat oven to 150°C.',
  'Blend 12 egg yolks on low speed until together.',
  'Blend in cooled sugar syrup until just combined.',
  'Add 240g almond meal and 5g salt, blend again until combined.',
  'Increase speed to high and blend for only 30 seconds to 1 minute total.',
  'Pour into tart base.',
  'Bake on middle rack until top is well caramelised and filling mostly set with modest wobble in centre, about 30 minutes.',
  'Cool to room temperature before de-tinning.',
  'Slice and serve with lemon caramel and whipped sour cream.',
]},

// ── DIPS & STARTERS ──────────────────────────────────────
{id:184,name:'Roast Tomato and Chickpea Dip with Homemade Naan-ish Bread',category:'Dips & Starters',difficulty:'medium',serves:4,time:'60 min',calories:350,mainIngredient:'Cherry Tomatoes',
ingredients:[
  {name:'Cherry tomatoes',amount:400,unit:'g'},
  {name:'Canned chickpeas, drained and rinsed',amount:400,unit:'g'},
  {name:'Extra-virgin olive oil',amount:60,unit:'ml'},
  {name:'Labne or cream cheese',amount:80,unit:'g'},
  {name:'Plain Greek yoghurt',amount:60,unit:'ml'},
  {name:'Strong bread flour',amount:400,unit:'g'},
  {name:'Instant dried yeast',amount:2,unit:'tsp'},
  {name:'Salt',amount:1,unit:'tsp'},
  {name:'Softened butter',amount:1,unit:'tbsp'},
  {name:'Plain yoghurt',amount:100,unit:'g'},
  {name:'Warm water',amount:0,unit:'as needed'},
],
steps:[
  'Preheat oven to 200 degrees C (fan-forced). Place cherry tomatoes and chickpeas on a large roasting tray, drizzle with olive oil and season.',
  'Roast until tomatoes are collapsed and chickpeas are golden and slightly crisp, 30 to 35 minutes.',
  'Allow to cool slightly, then blend or mash together with labne or cream cheese and yoghurt to a rough dip consistency. Season to taste.',
  'For the naan-ish bread, combine flour, yeast and salt. Add butter and yoghurt with enough warm water to bring together into a soft dough. Knead until smooth and elastic, 8 to 10 minutes.',
  'Cover and rest for 20 to 25 minutes.',
  'Divide dough into portions and roll each out thinly. Cook in a hot dry pan or under a grill for 2 to 3 minutes per side until charred in spots and cooked through.',
  'Serve the dip with warm naan-ish bread on the side.',
]},

// ── SALADS ──────────────────────────────────────────────
{id:185,name:'Husband and Wife Smashed Cucumber and Wood Ear Mushroom Salad',category:'Salads',difficulty:'easy',serves:4,time:'30 min',calories:120,mainIngredient:'Lebanese Cucumbers',
ingredients:[
  {name:'Lebanese cucumbers',amount:3,unit:'whole'},
  {name:'Caster sugar',amount:0.5,unit:'tsp'},
  {name:'Ajinomoto MSG',amount:0.5,unit:'tsp'},
  {name:'Wood ear mushrooms',amount:20,unit:'g'},
  {name:'Coriander',amount:0.5,unit:'cup'},
  {name:'White soy sauce',amount:60,unit:'ml'},
  {name:'Chilli oil',amount:1,unit:'tbsp'},
  {name:'Mirin',amount:1,unit:'tbsp'},
  {name:'Rice wine vinegar',amount:2,unit:'tsp'},
  {name:'Sesame oil',amount:2,unit:'tsp'},
  {name:'Ground Sichuan pepper',amount:0.5,unit:'tsp'},
],
steps:[
  'Place the cucumbers on a chopping board and whack each gently with a cleaver a few times until they splinter and open with jagged edges.',
  'Cut into bite-sized pieces and place in a bowl. Sprinkle with sugar, MSG and 1/2 tsp fine sea salt and stand, tossing occasionally, for 15 to 20 minutes, then drain and transfer cucumber to a bowl.',
  'For the dressing, whisk all ingredients in a jug to combine.',
  'Add mushrooms, coriander and dressing to cucumbers and toss to combine.',
  'Transfer to a serving bowl.',
]},

// ── SEAFOOD ──────────────────────────────────────────────

{id:187,name:'Stir-fried King Prawns with Chilli Black Bean Paste',category:'Seafood',difficulty:'hard',serves:4,time:'45 min',calories:280,mainIngredient:'King Prawns',
ingredients:[
  {name:'Extra-large king prawns, peeled and deveined',amount:12,unit:'whole'},
  {name:'Spanish onion, diced',amount:1,unit:'whole'},
  {name:'Spring onions, cut into batons',amount:10,unit:'whole'},
  {name:'Ginger, finely grated',amount:1.5,unit:'tbsp'},
  {name:'Light soy sauce',amount:1,unit:'tbsp'},
  {name:'Oyster sauce',amount:1,unit:'tbsp'},
  {name:'Long green chillies',amount:2,unit:'whole'},
  {name:'Salted fermented black beans',amount:100,unit:'g'},
  {name:'Garlic cloves',amount:3,unit:'whole'},
  {name:'Red chillies',amount:2,unit:'whole'},
  {name:'Neutral-flavoured oil',amount:2.5,unit:'tsp'},
  {name:'Potato starch',amount:1,unit:'tsp'},
  {name:'Sesame oil',amount:1,unit:'tbsp'},
  {name:'Ground white pepper',amount:0.5,unit:'tsp'},
  {name:'Caster sugar',amount:1,unit:'tsp'},
],
steps:[
  'For the black bean paste, preheat oven to 120 degrees C (fan-forced). Spread black beans on a baking tray lined with baking paper and roast to dry out, about 10 minutes. Set aside to cool slightly.',
  'Process chilli and garlic in a food processor to a rough paste, add black beans and pulse to combine. Heat oil in a frying pan over low heat and cook paste until fragrant and savoury. Cool and refrigerate in an airtight container for up to 1 month.',
  'For the marinade, combine sesame oil, white pepper and sugar in a non-reactive bowl. Add prawns and toss to coat, then set aside at room temperature for 20 minutes.',
  'Fill a large saucepan with neutral oil and place over medium-high heat until oil reaches 170 degrees C on a deep-frying thermometer. Deep-fry prawns until golden and cooked through, about 2 minutes. Drain on paper towel.',
  'Heat extra oil in a large wok over high heat until smoking. Add onion and spring onion and stir-fry until golden, 20 seconds to 1 minute.',
  'Add black bean paste and oyster sauce and cook for 1 to 2 minutes. Add prawns and toss until combined.',
  'Season with MSG, sugar and fine sea salt to taste. Transfer to a platter to serve.',
]},

{id:188,name:'Cantonese Wok-tossed Pipis with Garlic and Chilli',category:'Seafood',difficulty:'medium',serves:4,time:'20 min',calories:180,mainIngredient:'Pipis',
ingredients:[
  {name:'Pipis',amount:1000,unit:'g'},
  {name:'Neutral-flavoured oil',amount:2,unit:'tbsp'},
  {name:'Spring onions, cut into batons',amount:3,unit:'whole'},
  {name:'Ginger, cut into julienne',amount:15,unit:'g'},
  {name:'Garlic cloves, crushed',amount:5,unit:'whole'},
  {name:'Chilli garlic sauce',amount:2,unit:'tbsp'},
  {name:'Light soy sauce',amount:80,unit:'ml'},
  {name:'Coriander with stems',amount:0.5,unit:'cup'},
],
steps:[
  'Heat a wok over high heat, add 150 ml water and bring to the boil. Add pipis, cover and cook until they open, 3 to 4 minutes.',
  'Drain, reserving pipis and 60 ml of the cooking liquid. Wipe the wok dry with paper towel.',
  'Add oil and heat over high heat until smoking. Stir-fry spring onion, ginger and garlic until fragrant and light golden, 1 to 2 minutes.',
  'Add pipis and reserved cooking liquid and toss to combine.',
  'Add chilli garlic sauce, then soy sauce, and simmer for 1 to 2 minutes.',
  'Add coriander, toss to combine, then transfer to a bowl. Serve with steamed rice on the side.',
]},

// ── MEAT & POULTRY ──────────────────────────────────────────────
{id:189,name:'Hot and Numbing Fried Chicken Wings',category:'Meat & Poultry',difficulty:'hard',serves:4,time:'60 min',calories:520,mainIngredient:'Chicken Wings',
ingredients:[
  {name:'Chicken nibbles, halved',amount:1000,unit:'g'},
  {name:'Potato starch, for dusting',amount:200,unit:'g'},
  {name:'Garlic cloves, crushed',amount:2,unit:'whole'},
  {name:'Dried long red chillies',amount:2,unit:'whole'},
  {name:'Chopped dried chilli',amount:1,unit:'tbsp'},
  {name:'Crispy chilli oil',amount:1,unit:'tbsp'},
  {name:'Sichuan peppercorns',amount:2,unit:'tsp'},
  {name:'Toasted sesame seeds',amount:2,unit:'tsp'},
  {name:'Spring onion, thinly sliced',amount:1,unit:'whole'},
  {name:'Light soy sauce',amount:100,unit:'ml'},
  {name:'Caster sugar',amount:15,unit:'g'},
  {name:'Coriander seeds',amount:1,unit:'tbsp'},
  {name:'Ground Sichuan pepper',amount:1,unit:'tbsp'},
  {name:'White peppercorns',amount:0.75,unit:'tsp'},
],
steps:[
  'For the marinade, whisk soy sauce, sugar, potato starch and 10 g fine sea salt in a non-reactive bowl to combine. Add chicken, turn to coat, then cover and refrigerate overnight to marinate.',
  'For the spiced salt, dry-roast coriander seeds and whole Sichuan peppercorns in a small frying pan over medium heat until fragrant, 1 to 2 minutes. Transfer to a spice grinder with the remaining spiced salt ingredients and 1 tbsp fine sea salt, and grind to a fine powder.',
  'Half-fill a large saucepan with neutral oil and place over medium heat until oil reaches 170 degrees C on a deep-frying thermometer. Place potato starch in a bowl, add wings and turn to coat, shaking off any excess.',
  'Deep-fry chicken in batches, turning occasionally, until golden and cooked through, 6 to 8 minutes. Drain on paper towel, transfer to a bowl and season generously with spiced salt.',
  'Heat the extra 2 tbsp oil in a large wok over medium heat. Stir-fry garlic, dried chillies, chilli oil and Sichuan peppercorns until fragrant, 2 to 3 minutes.',
  'Add chicken, sesame seeds and spring onion and toss to combine. Remove from heat and transfer to a platter to serve.',
]},

// ── VEGETARIAN ──────────────────────────────────────────────
{id:190,name:'Palak Paneer Fillo Pie',category:'Vegetarian',difficulty:'hard',serves:6,time:'90 min',calories:420,mainIngredient:'Paneer',
ingredients:[
  {name:'Ghee',amount:80,unit:'g'},
  {name:'Spanish onion, finely chopped',amount:1,unit:'large'},
  {name:'Garlic cloves, crushed',amount:3,unit:'whole'},
  {name:'Long green chillies, thinly sliced',amount:2,unit:'whole'},
  {name:'Ginger, finely grated',amount:1,unit:'tsp'},
  {name:'Cumin seeds',amount:2,unit:'tsp'},
  {name:'Fenugreek leaves (dried methi)',amount:1,unit:'tsp'},
  {name:'Ground turmeric',amount:0.5,unit:'tsp'},
  {name:'Garam masala',amount:1.5,unit:'tsp'},
  {name:'Ground chilli',amount:1,unit:'tsp'},
  {name:'Spinach',amount:690,unit:'g'},
  {name:'Paneer, crumbled',amount:400,unit:'g'},
  {name:'Coriander, finely chopped',amount:1,unit:'bunch'},
  {name:'Lemon',amount:0.5,unit:'whole'},
  {name:'Egg',amount:1,unit:'whole'},
  {name:'Plain yoghurt',amount:60,unit:'g'},
  {name:'Filo pastry sheets',amount:16,unit:'whole'},
  {name:'Unsalted butter',amount:150,unit:'g'},
  {name:'Curry leaves',amount:1,unit:'handful'},
  {name:'Light palm sugar',amount:1,unit:'tsp'},
  {name:'Extra-virgin olive oil',amount:2,unit:'tbsp'},
  {name:'Baby fennel, thinly sliced',amount:3,unit:'whole'},
  {name:'Spanish onion (small), thinly sliced',amount:1,unit:'whole'},
  {name:'Soft herbs (coriander and mint)',amount:1,unit:'cup'},
],
steps:[
  'Preheat oven to 180 degrees C (fan-forced). Grease a 30 cm round baking tray or pie tin with butter.',
  'For the curry leaf butter, melt butter over low heat with garlic and curry leaves, cooking until foaming and fragrant, 5 to 6 minutes. Remove from heat and stand.',
  'Melt ghee in a frying pan over medium heat. Add onion, garlic, chilli and ginger and cook until softened, about 10 minutes. Add cumin seeds, fenugreek, turmeric, garam masala and ground chilli and cook until fragrant, then set aside to cool.',
  'Meanwhile, pulse spinach in batches in a food processor until finely chopped. Place in a colander, add 1 1/2 tsp salt flakes, toss well and stand to draw out excess moisture for 10 minutes. Squeeze out excess moisture and transfer to a bowl.',
  'Add paneer, cooled onion mixture, finely chopped coriander, lemon zest and juice and mix to combine. Season to taste, then stir through egg and yoghurt.',
  'Warm curry butter gently. Place one sheet of filo on a work surface with the long side facing you and brush with curry butter. Top with another sheet and brush again. Spoon filling along one edge to form a log, then roll up tightly tucking in the ends to form a cylinder.',
  'Arrange in the prepared tin, coiling and building from the centre outward. Repeat with the remaining filling and filo.',
  'Brush the top with eggwash and curry butter. Bake for 35 to 45 minutes until golden and cooked through, then rest before slicing.',
  'For the fennel salad, combine olive oil and lemon juice, then toss with fennel, onion and herbs and season to taste. Serve alongside the pie.',
]},
{id:191,name:'Thai Green Curry of Pink Ling, Prawns and Eggplant',category:'Seafood',difficulty:'medium',serves:4,time:'80 min',calories:550,mainIngredient:'Ling',ingredients:[
  {name:'Grapeseed oil',amount:60,unit:'ml'},
  {name:'Coconut cream',amount:400,unit:'ml'},
  {name:'Coconut milk',amount:250,unit:'ml'},
  {name:'Chicken bone broth',amount:300,unit:'ml'},
  {name:'Makrut lime leaves, scrunched',amount:4,unit:'whole'},
  {name:'Apple eggplants, quartered',amount:200,unit:'g'},
  {name:'Green beans, trimmed and halved',amount:200,unit:'g'},
  {name:'Pink ling fillet, cut into 5 cm pieces',amount:600,unit:'g'},
  {name:'Tiger prawns, peeled and deveined',amount:12,unit:'whole'},
  {name:'Lime juice',amount:60,unit:'ml'},
  {name:'Fish sauce',amount:2,unit:'tbsp'},
  {name:'Light palm sugar',amount:1,unit:'tbsp'},
  {name:'Coriander seeds',amount:2,unit:'tsp'},
  {name:'Cumin seeds',amount:1,unit:'tsp'},
  {name:'White peppercorns',amount:0.5,unit:'tsp'},
  {name:'Long green chillies',amount:6,unit:'whole'},
  {name:'Green birdseye chillies',amount:2,unit:'whole'},
  {name:'Spring onions',amount:100,unit:'g'},
  {name:'Garlic cloves',amount:5,unit:'whole'},
  {name:'Coriander roots',amount:4,unit:'whole'},
  {name:'Lemongrass stalk, thinly sliced',amount:1,unit:'whole'},
  {name:'Galangal, peeled and chopped',amount:10,unit:'g'},
  {name:'Turmeric, peeled and chopped',amount:10,unit:'g'},
  {name:'Thai shrimp paste',amount:1,unit:'tsp'},
  {name:'Makrut lime zest',amount:1,unit:'whole'},
  {name:'Grapeseed oil for paste',amount:125,unit:'ml'},
  {name:'Rice wine vinegar',amount:125,unit:'ml'},
  {name:'Caster sugar',amount:55,unit:'g'},
  {name:'Star anise',amount:2,unit:'whole'},
  {name:'Red shallots, thinly sliced',amount:3,unit:'whole'},
],steps:[
  'For the green curry paste, dry-roast the coriander and cumin seeds in a small frying pan until fragrant, about 30 seconds. Transfer to a bowl to cool, then grind to a fine powder with the white peppercorns. Blend with the remaining paste ingredients and 1 tsp fine salt to a smooth paste and set aside.',
  'For the pickled shallots, stir the vinegar, sugar, star anise, half a tsp fine salt and 180 ml water in a small saucepan over medium-high heat until the sugar dissolves. Remove from heat, add the shallots and leave to cool and pickle. Drain before using.',
  'Heat 2 tbsp oil in a large saucepan over medium heat. Add the curry paste and the head of coconut cream skimmed from the top of the can, reserving the remaining coconut cream, and stir until fragrant and the oil separates, 12 to 15 minutes. Add the coconut milk, bone broth and lime leaves, and simmer over low heat for 10 minutes.',
  'Add the eggplant and beans to the curry, bring to a simmer over medium heat and cook covered for 5 minutes. Add the fish and prawns and simmer covered, stirring occasionally, until just cooked, 3 to 5 minutes. Remove from heat. Stir in the lime juice, fish sauce, palm sugar and remaining coconut cream. Discard the lime leaves.',
  'Divide the rice and curry among bowls and serve topped with pickled shallots and Thai basil.',
]}
];
