// ── SEAFOOD ──────────────────────────────────────────────
const RECIPES2 = [

{id:43,name:'Fish Pot Pie',category:'Seafood',difficulty:'medium',serves:2,time:'45 min',calories:580,mainIngredient:'Fish',
ingredients:[
  {name:'Olive oil',amount:30,unit:'ml'},
  {name:'Red onion',prep:'chopped',amount:30,unit:'g'},
  {name:'Cavolo nero',prep:'chopped',amount:0.5,unit:'bunch'},
  {name:'Baby capers',amount:30,unit:'g'},
  {name:'Cornichons',prep:'chopped',amount:30,unit:'g'},
  {name:'Dill',prep:'chopped',amount:15,unit:'g'},
  {name:'Parsley',prep:'chopped',amount:5,unit:'g'},
  {name:'Lemon zest',amount:1,unit:'lemon'},
  {name:'Crème fraîche or cream',amount:245,unit:'g'},
  {name:'Ling fillet',prep:'diced',amount:300,unit:'g'},
  {name:'Ocean trout, diced',amount:300,unit:'g'},
  {name:'Peas',amount:140,unit:'g'},
  {name:'Puff pastry sheet',amount:1,unit:'sheet'},
  {name:'Egg yolk',amount:1,unit:'whole'},
],
steps:[
  'Sauté onion and cavolo nero in oil with salt until dry. Cool completely.',
  'Mix with capers, cornichons, herbs, lemon zest, crème fraîche, fish and peas.',
  'Spoon into a pie dish. Cover with puff pastry, brush with egg yolk and cut a steam hole.',
  'Bake at 210°C for 25 minutes until pastry is golden.',
]},

{id:44,name:'Crispy-Skin Blue-Eye with Burnt Butter & Yoghurt',category:'Seafood',difficulty:'medium',serves:2,time:'25 min',calories:390,mainIngredient:'Fish',
ingredients:[
  {name:'Blue-eye trevalla fillets, skin on',amount:320,unit:'g'},
  {name:'Greek yoghurt',amount:260,unit:'g'},
  {name:'Garlic clove',prep:'grated',amount:1,unit:'clove'},
  {name:'Lemon juice',amount:15,unit:'ml'},
  {name:'Baby spinach',amount:200,unit:'g'},
  {name:'Olive oil',amount:30,unit:'ml'},
  {name:'Butter',amount:60,unit:'g'},
  {name:'Pine nuts',amount:40,unit:'g'},
  {name:'Smoked paprika',amount:2,unit:'g'},
  {name:'Lemon',prep:'halved',amount:1,unit:'whole'},
],
steps:[
  'Mix yoghurt with garlic, lemon juice, salt and pepper. Set aside.',
  'Pat fish skin dry. Heat oil in a pan, fry skin-side down over high heat for 3–4 minutes until crisp. Flip briefly. Rest.',
  'Wilt spinach in the same pan with a splash of water. Drain well.',
  'Brown butter with pine nuts, smoked paprika and a squeeze of lemon until nutty.',
  'Plate yoghurt, then spinach, then fish. Drizzle burnt butter and pine nuts over everything.',
]},

{id:45,name:'Gochujang Fish & Brussels Sprouts Tray Bake',category:'Seafood',difficulty:'medium',serves:2,time:'30 min',calories:420,mainIngredient:'Fish',
ingredients:[
  {name:'Blue-eye trevalla or ling fillet',amount:650,unit:'g'},
  {name:'Brussels sprouts',prep:'halved',amount:500,unit:'g'},
  {name:'Onion, cut into wedges',amount:1,unit:'whole'},
  {name:'Broccolini',amount:1,unit:'bunch'},
  {name:'Olive oil',amount:30,unit:'ml'},
  {name:'Gochujang dressing',amount:250,unit:'ml'},
  {name:'Radishes',prep:'sliced',amount:4,unit:'whole'},
  {name:'Spring onions',prep:'sliced',amount:3,unit:'whole'},
  {name:'Edamame beans',amount:75,unit:'g'},
  {name:'Rice vinegar',amount:15,unit:'ml'},
  {name:'Sesame oil',amount:15,unit:'ml'},
  {name:'Kimchi (optional)',amount:100,unit:'g'},
  {name:'Steamed rice',amount:1,unit:'to serve'},
],
steps:[
  'Toss brussels sprouts and onion with oil, salt and most of the gochujang dressing. Roast 7 minutes at 230°C.',
  'Add fish skin-side down and broccolini to the tray. Roast a further 8 minutes until fish is just cooked.',
  'Mix radish, spring onion and edamame with rice vinegar and sesame oil.',
  'Scatter the fresh salad over the tray bake. Serve with kimchi, steamed rice and extra dressing.',
]},

{id:46,name:'Green Shakshuka with Quinoa and Fish',category:'Seafood',difficulty:'medium',serves:4,time:'40 min',calories:460,mainIngredient:'Fish',
ingredients:[
  {name:'Olive oil',amount:80,unit:'ml'},
  {name:'Leek or brown onion, finely chopped',amount:1,unit:'small'},
  {name:'Garlic cloves',prep:'sliced',amount:2,unit:'cloves'},
  {name:'Ras el hanout',amount:22,unit:'g'},
  {name:'Broccoli',prep:'finely chopped',amount:1,unit:'small head'},
  {name:'Kale or cavolo nero, thinly sliced',amount:0.5,unit:'bunch'},
  {name:'Zucchinis',prep:'grated',amount:2,unit:'whole'},
  {name:'Mixed quinoa, rinsed',amount:200,unit:'g'},
  {name:'Vegetable stock',amount:625,unit:'ml'},
  {name:'Firm white fish fillet (ling, trevalla)',amount:600,unit:'g'},
  {name:'Dairy-free pesto',amount:80,unit:'ml'},
  {name:'Frozen peas',amount:140,unit:'g'},
  {name:'Coriander',prep:'chopped',amount:1,unit:'handful'},
  {name:'Greek yoghurt or whipped tahini',amount:140,unit:'g'},
  {name:'Lemon wedges',amount:2,unit:'whole'},
],
steps:[
  'Heat oil in a wide pan. Cook leek, garlic and salt for 3 minutes. Add ras el hanout and broccoli, cook 1 minute.',
  'Stir in kale, zucchini and pepper, cook 2 minutes until wilted.',
  'Stir through quinoa, add stock and season. Bring to boil, cover and simmer 10 minutes.',
  'Rub fish with a little olive oil and half the pesto. Nestle into vegetables, scatter peas on top. Cover and cook 10 minutes.',
  'Rest 5 minutes. Drizzle with remaining pesto, scatter coriander. Serve with yoghurt and lemon wedges.',
]},

{id:47,name:'Grilled Mackerel with Salsa Verde',category:'Seafood',difficulty:'medium',serves:4,time:'20 min',calories:310,mainIngredient:'Mackerel',
ingredients:[
  {name:'Mackerel fillets',amount:4,unit:'whole'},
  {name:'Olive oil',amount:30,unit:'ml'},
  {name:'Parsley leaves',amount:1,unit:'cup'},
  {name:'Basil leaves',amount:0.5,unit:'cup'},
  {name:'Garlic clove',amount:1,unit:'clove'},
  {name:'Capers',amount:15,unit:'g'},
  {name:'Anchovy fillets',amount:3,unit:'whole'},
  {name:'Red wine vinegar',amount:30,unit:'ml'},
  {name:'Olive oil (salsa)',amount:100,unit:'ml'},
],
steps:[
  'Blend parsley, basil, garlic, capers, anchovies, vinegar and olive oil to a rough salsa verde. Adjust with extra oil if needed.',
  'Brush mackerel fillets with olive oil and season.',
  'Grill skin-side down for 3–4 minutes until skin is crisp. Flip and cook briefly.',
  'Serve with salsa verde spooned generously over.',
]},

{id:48,name:'Grilled Prawns with Garlic & Chilli',category:'Seafood',difficulty:'easy',serves:4,time:'15 min',calories:180,mainIngredient:'Prawns',
ingredients:[
  {name:'Raw prawns',prep:'peeled and deveined',amount:500,unit:'g'},
  {name:'Olive oil',amount:30,unit:'ml'},
  {name:'Garlic cloves',prep:'finely chopped',amount:3,unit:'cloves'},
  {name:'Red chilli',prep:'finely chopped',amount:1,unit:'whole'},
  {name:'Lemon juice',amount:30,unit:'ml'},
  {name:'Parsley',prep:'chopped',amount:1,unit:'handful'},
],
steps:[
  'Toss prawns with olive oil, garlic, chilli, salt and pepper.',
  'Heat barbecue or grill pan to high. Cook prawns 2–3 minutes per side until pink and just cooked.',
  'Squeeze lemon juice over, scatter parsley and serve immediately.',
]},

{id:49,name:'Grilled Chimichurri Prawns',category:'Seafood',difficulty:'easy',serves:2,time:'20 min + 5 hr marinade',calories:320,mainIngredient:'Prawns',
ingredients:[
  {name:'Parsley',prep:'chopped',amount:1,unit:'cup'},
  {name:'Coriander',prep:'chopped',amount:1,unit:'cup'},
  {name:'Oregano',prep:'chopped',amount:0.5,unit:'cup'},
  {name:'Garlic clove',prep:'chopped',amount:1,unit:'clove'},
  {name:'Olive oil',amount:200,unit:'ml'},
  {name:'Red wine vinegar',amount:22,unit:'ml'},
  {name:'Balsamic vinegar',amount:15,unit:'ml'},
  {name:'Dried chilli flakes',amount:1,unit:'pinch'},
  {name:'Lemon zest',amount:1,unit:'lemon'},
  {name:'Large prawns, shells on',amount:6,unit:'whole'},
],
steps:[
  'Mix herbs, garlic, oil, both vinegars, chilli and lemon zest. Season well.',
  'Coat prawns with half the chimichurri. Marinate 5 hours in the fridge.',
  'Grill prawns over medium heat, turning often, for 5 minutes until cooked through.',
  'Serve with remaining chimichurri and lemon wedges.',
]},

{id:50,name:'One-Tray Roast Fish with Brothy White Beans',category:'Seafood',difficulty:'medium',serves:4,time:'25 min',calories:380,mainIngredient:'Fish',
ingredients:[
  {name:'Olive oil',amount:80,unit:'ml'},
  {name:'Leek',prep:'chopped',amount:0.5,unit:'small'},
  {name:'Garlic cloves',prep:'sliced',amount:4,unit:'cloves'},
  {name:'Rosemary sprigs',amount:2,unit:'sprigs'},
  {name:'Anchovy fillets (optional)',amount:4,unit:'whole'},
  {name:'Capers',prep:'rinsed',amount:45,unit:'g'},
  {name:'Lemon, juiced and zested',amount:1,unit:'whole'},
  {name:'Kale leaves, thinly sliced',amount:0.25,unit:'bunch'},
  {name:'Broccolini, cut short',amount:1,unit:'bunch'},
  {name:'Vegetable stock',amount:500,unit:'ml'},
  {name:'Cannellini beans',prep:'rinsed',amount:800,unit:'g'},
  {name:'Parsley',prep:'chopped',amount:1,unit:'handful'},
  {name:'Firm white fish fillet (trevalla)',amount:600,unit:'g'},
],
steps:[
  'Heat oven to 200°C. Heat 60 ml oil in a large ovenproof pan. Add leek, garlic, rosemary, anchovies and salt. Cook 3 minutes.',
  'Add lemon zest, kale and broccolini, cook briefly to wilt. Pour in stock and beans, bring to boil, stir through parsley and lemon juice.',
  'Season fish, drizzle with remaining oil. Place on top of the bean mixture.',
  'Transfer to oven and roast 6 minutes until fish is just cooked. Serve with lemon wedges.',
]},

{id:51,name:'Poached Salmon with Dill Sauce',category:'Seafood',difficulty:'medium',serves:4,time:'25 min',calories:350,mainIngredient:'Salmon',
ingredients:[
  {name:'Salmon fillets',amount:4,unit:'whole'},
  {name:'Bay leaf',amount:1,unit:'whole'},
  {name:'Peppercorns',amount:6,unit:'whole'},
  {name:'Lemon',prep:'sliced',amount:1,unit:'whole'},
  {name:'Water',amount:500,unit:'ml'},
  {name:'White wine',amount:500,unit:'ml'},
  {name:'Sour cream',amount:200,unit:'g'},
  {name:'Lemon juice',amount:15,unit:'ml'},
  {name:'Fresh dill',prep:'chopped',amount:1,unit:'handful'},
],
steps:[
  'Place water, wine, bay leaf, peppercorns and lemon slices in a wide pan. Bring to a simmer.',
  'Add salmon fillets and poach gently for 8–10 minutes until just cooked through.',
  'Remove salmon carefully with a slotted spoon.',
  'Mix sour cream, lemon juice, dill, salt and pepper for the sauce. Serve with salmon.',
]},

{id:52,name:'Sardines in Tomato Sauce',category:'Seafood',difficulty:'easy',serves:4,time:'30 min',calories:220,mainIngredient:'Sardines',
ingredients:[
  {name:'Whole sardines',prep:'cleaned',amount:8,unit:'whole'},
  {name:'Olive oil',amount:30,unit:'ml'},
  {name:'Onion',prep:'finely chopped',amount:1,unit:'whole'},
  {name:'Garlic cloves',prep:'sliced',amount:3,unit:'cloves'},
  {name:'Tinned chopped tomatoes',amount:400,unit:'g'},
  {name:'Tomato paste',amount:15,unit:'g'},
  {name:'Dried oregano',amount:2,unit:'g'},
  {name:'Chilli flakes (optional)',amount:2,unit:'g'},
],
steps:[
  'Heat olive oil in a pan. Sauté onion and garlic until soft, about 6 minutes.',
  'Stir in tomatoes, tomato paste, oregano and chilli. Simmer 10 minutes.',
  'Add sardines in a single layer, season, cover and cook 8–10 minutes until cooked through.',
  'Serve hot with lemon wedges and bread.',
]},

{id:53,name:'Scallop, Chorizo & Beans',category:'Seafood',difficulty:'medium',serves:2,time:'20 min',calories:420,mainIngredient:'Scallops',
ingredients:[
  {name:'Scallops',prep:'patted dry',amount:400,unit:'g'},
  {name:'Spanish chorizo',prep:'finely diced',amount:1,unit:'small'},
  {name:'Cannellini beans',prep:'rinsed',amount:400,unit:'g'},
  {name:'Garlic cloves',prep:'finely chopped',amount:2,unit:'cloves'},
  {name:'Fennel seeds',prep:'crushed',amount:5,unit:'g'},
  {name:'Dried chilli flakes',amount:1,unit:'pinch'},
  {name:'Olive oil',amount:30,unit:'ml'},
  {name:'Unsalted butter',amount:30,unit:'g'},
  {name:'Lemon zest and juice',amount:1,unit:'lemon'},
],
steps:[
  'Heat 1 tbsp oil and half the butter in a small pan. Add garlic, fennel and chilli, then beans with a splash of water. Mash slightly until creamy. Season with lemon juice. Keep warm.',
  'Heat remaining oil in a frying pan. Fry chorizo until crisp. Remove.',
  'Season scallops. Add remaining butter to the pan and sear scallops 45–60 seconds per side until golden.',
  'Serve scallops on bean purée, scattered with chorizo, pan juices and lemon zest.',
]},

{id:54,name:'Seafood Paella',category:'Seafood',difficulty:'medium',serves:4,time:'40 min',calories:520,mainIngredient:'Seafood',
ingredients:[
  {name:'Olive oil',amount:30,unit:'ml'},
  {name:'Onion',prep:'chopped',amount:1,unit:'whole'},
  {name:'Red capsicum',prep:'chopped',amount:1,unit:'whole'},
  {name:'Garlic cloves',prep:'chopped',amount:2,unit:'cloves'},
  {name:'Paella rice',amount:400,unit:'g'},
  {name:'Smoked paprika',amount:5,unit:'g'},
  {name:'Saffron threads',amount:1,unit:'pinch'},
  {name:'Fish stock',amount:1000,unit:'ml'},
  {name:'Prawns',prep:'peeled',amount:200,unit:'g'},
  {name:'Mussels',prep:'cleaned',amount:200,unit:'g'},
  {name:'Squid',prep:'sliced',amount:200,unit:'g'},
  {name:'Parsley',prep:'chopped',amount:1,unit:'handful'},
],
steps:[
  'Heat oil in a paella pan. Fry onion, capsicum and garlic until soft.',
  'Stir in rice, paprika and saffron. Pour in stock and simmer 15 minutes without stirring.',
  'Add prawns, mussels and squid. Cook 8–10 minutes until rice is tender and seafood cooked.',
  'Scatter parsley and serve with lemon wedges.',
]},

{id:55,name:'Smoky Butter Beans with Fish and Rice',category:'Seafood',difficulty:'medium',serves:4,time:'35 min',calories:450,mainIngredient:'Fish',
ingredients:[
  {name:'Olive oil',amount:60,unit:'ml'},
  {name:'Brown onion',prep:'finely chopped',amount:1,unit:'small'},
  {name:'Red capsicum',prep:'finely chopped',amount:1,unit:'small'},
  {name:'Garlic cloves',prep:'sliced',amount:2,unit:'cloves'},
  {name:'Chipotle in adobo or chilli salsa',amount:15,unit:'g'},
  {name:'Sweet smoked paprika',amount:10,unit:'g'},
  {name:'Ground cumin',amount:15,unit:'g'},
  {name:'Basmati rice',amount:200,unit:'g'},
  {name:'Crushed tomatoes',amount:400,unit:'g'},
  {name:'Vegetable or chicken stock',amount:800,unit:'ml'},
  {name:'Ling fillet, skinless boneless',amount:500,unit:'g'},
  {name:'Butter beans',prep:'rinsed',amount:400,unit:'g'},
  {name:'Parsley and mint',prep:'chopped',amount:1,unit:'handful'},
  {name:'Lemon juice',amount:30,unit:'ml'},
  {name:'Za\'atar (optional)',amount:15,unit:'g'},
  {name:'Greek yoghurt',amount:130,unit:'g'},
],
steps:[
  'Heat oil in a casserole. Add onion, capsicum, garlic, salt and pepper. Cook 4 minutes.',
  'Add chipotle, paprika and cumin, stir 1 minute. Add rice, tomatoes and stock. Bring to boil.',
  'Reduce heat and cook 6 minutes until rice is partially cooked.',
  'Nestle fish into rice. Spoon sauce over. Cover and cook 6 minutes. Rest 5 minutes off heat.',
  'Toss butter beans with herbs, extra oil and lemon juice. Spoon around fish. Sprinkle za\'atar and serve with yoghurt.',
]},

{id:56,name:'Turmeric Fish, Coconut & Chickpea Curry',category:'Seafood',difficulty:'medium',serves:2,time:'35 min',calories:480,mainIngredient:'Fish',
ingredients:[
  {name:'Onion',prep:'chopped',amount:1,unit:'whole'},
  {name:'Garlic cloves',prep:'chopped',amount:2,unit:'cloves'},
  {name:'Tomato',prep:'chopped',amount:1,unit:'whole'},
  {name:'Vegetable stock',amount:400,unit:'ml'},
  {name:'Coconut milk',amount:310,unit:'ml'},
  {name:'Chickpeas',prep:'rinsed',amount:400,unit:'g'},
  {name:'Firm white fish (ling, hake), cubed',amount:500,unit:'g'},
  {name:'Spinach',prep:'chopped',amount:1,unit:'bunch'},
  {name:'Coriander',prep:'chopped',amount:1,unit:'handful'},
  {name:'Lime juice',amount:30,unit:'ml'},
  {name:'Ground turmeric',amount:50,unit:'g'},
  {name:'Fresh ginger',prep:'sliced',amount:30,unit:'g'},
  {name:'Ground cinnamon',amount:5,unit:'g'},
  {name:'Neutral oil',amount:60,unit:'ml'},
],
steps:[
  'Blend turmeric paste: oil, turmeric, ginger, cinnamon and pepper with 80 ml water. Cook in pan 5–7 minutes until thick.',
  'Fry onion and garlic with salt until softened. Add tomato, cook 3 minutes. Stir in turmeric paste.',
  'Add stock, simmer 4 minutes. Pour in coconut milk and chickpeas, bring to boil.',
  'Add fish, poach 5 minutes until just cooked. Stir through spinach.',
  'Finish with coriander and lime juice. Serve with rice or quinoa.',
]},

{id:57,name:'Whole Baked Snapper with Lemon & Herbs',category:'Seafood',difficulty:'medium',serves:2,time:'35 min',calories:280,mainIngredient:'Snapper',
ingredients:[
  {name:'Whole snapper',prep:'cleaned and scaled',amount:1200,unit:'g'},
  {name:'Olive oil',amount:30,unit:'ml'},
  {name:'Garlic cloves',prep:'sliced',amount:2,unit:'cloves'},
  {name:'Lemon',prep:'sliced',amount:1,unit:'whole'},
  {name:'Fresh parsley, dill or coriander',amount:1,unit:'handful'},
],
steps:[
  'Heat oven to 200°C. Score the fish lightly on each side, drizzle with olive oil and season well.',
  'Stuff the cavity with garlic, lemon slices and fresh herbs.',
  'Place on a lined baking tray and roast 25 minutes until flesh flakes easily.',
  'Serve with pan juices.',
]},

{id:58,name:'Whole Roast Snapper with Red Miso Butter',category:'Seafood',difficulty:'medium',serves:2,time:'25 min',calories:310,mainIngredient:'Snapper',
ingredients:[
  {name:'Whole snapper',prep:'cleaned',amount:600,unit:'g'},
  {name:'Olive oil',amount:15,unit:'ml'},
  {name:'Red miso butter',amount:150,unit:'g'},
  {name:'Fresh chives, snipped',amount:1,unit:'bunch'},
  {name:'Baby sorrel leaves (optional)',amount:1,unit:'handful'},
  {name:'Lemon wedges',amount:1,unit:'to serve'},
],
steps:[
  'Heat oven to 210°C. Pat fish dry and score 3 slits per side.',
  'Rub with olive oil, salt and pepper. Roast 10 minutes.',
  'Melt miso butter and spoon generously over fish. Roast 7 minutes more.',
  'Rest 3 minutes, then plate with remaining butter, chives, sorrel and lemon wedges.',
]},

{id:59,name:'Whole Roast Lebanese Fish',category:'Seafood',difficulty:'medium',serves:2,time:'30 min + 1 hr marinade',calories:340,mainIngredient:'Fish',
ingredients:[
  {name:'Whole leatherjackets',prep:'cleaned',amount:2,unit:'whole'},
  {name:'Pine nuts',prep:'toasted',amount:50,unit:'g'},
  {name:'Parsley leaves',amount:1,unit:'handful'},
  {name:'Red onion',prep:'sliced',amount:0.5,unit:'small'},
  {name:'Olive oil',amount:60,unit:'ml'},
  {name:'Lemon juice',amount:45,unit:'ml'},
  {name:'Honey',amount:30,unit:'ml'},
  {name:'Za\'atar',amount:30,unit:'g'},
  {name:'Smoked paprika',amount:5,unit:'g'},
  {name:'Sumac',amount:10,unit:'g'},
  {name:'Cinnamon',amount:5,unit:'g'},
  {name:'Garlic cloves',prep:'chopped',amount:4,unit:'cloves'},
],
steps:[
  'Score fish on both sides and season.',
  'Mix marinade from oil, lemon juice, honey, za\'atar, paprika, sumac, cinnamon and garlic. Coat fish inside and out. Chill 1 hour.',
  'Roast at 220°C for 15–20 minutes until cooked through. Rest 3 minutes.',
  'Scatter with toasted pine nuts, parsley and sliced onion. Serve with flatbread or rice.',
]},

// ── MEAT & POULTRY ────────────────────────────────────────
{id:60,name:'Buttermilk-Brined Roast Chicken',category:'Meat & Poultry',difficulty:'medium',serves:4,time:'1 hr 15 min + overnight',calories:520,mainIngredient:'Chicken',
ingredients:[
  {name:'Whole chicken',amount:1600,unit:'g'},
  {name:'Buttermilk',amount:1000,unit:'ml'},
  {name:'Salt',amount:45,unit:'g'},
  {name:'Garlic cloves',prep:'crushed',amount:3,unit:'cloves'},
  {name:'Lemon zest',amount:1,unit:'lemon'},
  {name:'Fresh thyme sprigs',amount:4,unit:'sprigs'},
  {name:'Olive oil',amount:30,unit:'ml'},
],
steps:[
  'Mix buttermilk, salt, garlic, lemon zest and thyme. Add chicken, cover and refrigerate overnight.',
  'Heat oven to 200°C. Remove chicken from brine and pat dry. Rub with olive oil and season.',
  'Roast for 1 hour until juices run clear when thigh is pierced.',
  'Rest 15 minutes before carving.',
]},

{id:61,name:'Grilled Chicken with Sumac & Garlic Yoghurt',category:'Meat & Poultry',difficulty:'easy',serves:4,time:'30 min',calories:380,mainIngredient:'Chicken',
ingredients:[
  {name:'Chicken thighs',prep:'bone-in skin-on',amount:4,unit:'whole'},
  {name:'Olive oil',amount:30,unit:'ml'},
  {name:'Ground sumac',amount:5,unit:'g'},
  {name:'Ground cumin',amount:5,unit:'g'},
  {name:'Garlic cloves',prep:'crushed',amount:2,unit:'cloves'},
  {name:'Greek yoghurt',amount:200,unit:'g'},
  {name:'Garlic clove (for yoghurt), crushed',amount:1,unit:'clove'},
  {name:'Lemon juice',amount:15,unit:'ml'},
],
steps:[
  'Rub chicken with olive oil, sumac, cumin, garlic, salt and pepper. Marinate 30 minutes if possible.',
  'Heat grill or barbecue. Cook chicken skin-side down until crisp, then turn. Cook about 20 minutes total until cooked through.',
  'Mix yoghurt, garlic and lemon juice together. Season.',
  'Serve chicken with garlic yoghurt.',
]},

{id:62,name:'Beef Stew with Red Wine',category:'Meat & Poultry',difficulty:'medium',serves:4,time:'3 hr',calories:580,mainIngredient:'Beef',
ingredients:[
  {name:'Chuck steak, diced',amount:1000,unit:'g'},
  {name:'Plain flour',amount:45,unit:'g'},
  {name:'Olive oil',amount:30,unit:'ml'},
  {name:'Onion',prep:'chopped',amount:1,unit:'whole'},
  {name:'Carrots',prep:'chopped',amount:2,unit:'whole'},
  {name:'Celery sticks',prep:'chopped',amount:2,unit:'stalks'},
  {name:'Garlic cloves',prep:'chopped',amount:3,unit:'cloves'},
  {name:'Tomato paste',amount:30,unit:'g'},
  {name:'Red wine',amount:500,unit:'ml'},
  {name:'Beef stock',amount:500,unit:'ml'},
  {name:'Bay leaves',amount:2,unit:'whole'},
  {name:'Fresh rosemary sprig',amount:1,unit:'sprig'},
],
steps:[
  'Toss beef in flour and season well. Brown in batches in olive oil. Remove and set aside.',
  'In the same pot, cook onion, carrots, celery and garlic until softened. Stir in tomato paste.',
  'Pour in wine and simmer 5 minutes. Add beef back with stock, bay leaves and rosemary.',
  'Cover and simmer gently for 2½ hours until beef is very tender. Season and serve.',
]},

{id:63,name:'Beef Stir-Fry with Ginger & Broccoli',category:'Meat & Poultry',difficulty:'easy',serves:4,time:'25 min',calories:380,mainIngredient:'Beef',
ingredients:[
  {name:'Beef rump',prep:'thinly sliced',amount:400,unit:'g'},
  {name:'Soy sauce',amount:30,unit:'ml'},
  {name:'Oyster sauce',amount:15,unit:'ml'},
  {name:'Sesame oil',amount:5,unit:'ml'},
  {name:'Garlic cloves',prep:'chopped',amount:2,unit:'cloves'},
  {name:'Fresh ginger',prep:'grated',amount:15,unit:'g'},
  {name:'Broccoli',prep:'cut into florets',amount:1,unit:'whole head'},
  {name:'Vegetable oil',amount:30,unit:'ml'},
  {name:'Steamed rice',amount:1,unit:'to serve'},
],
steps:[
  'Marinate beef in soy, oyster sauce and sesame oil for 15 minutes.',
  'Heat a wok over high heat with vegetable oil. Stir-fry garlic and ginger for 30 seconds.',
  'Add beef and cook until browned, 2–3 minutes.',
  'Add broccoli and a splash of water. Cook 2–3 minutes until just tender-crisp. Serve with rice.',
]},

{id:64,name:'Crispy Pork Belly with Five Spice',category:'Meat & Poultry',difficulty:'medium',serves:4,time:'2 hr',calories:620,mainIngredient:'Pork',
ingredients:[
  {name:'Pork belly',prep:'skin scored',amount:1500,unit:'g'},
  {name:'Chinese five spice',amount:15,unit:'g'},
  {name:'Sea salt',amount:15,unit:'g'},
  {name:'Olive oil',amount:30,unit:'ml'},
],
steps:[
  'Heat oven to 220°C. Pat pork skin completely dry. Rub all over with oil, five spice and salt.',
  'Place on a rack in a roasting tray. Roast 30 minutes until skin blisters and crackles.',
  'Reduce oven to 170°C and roast a further 1½ hours until meat is very tender.',
  'Rest 15 minutes before slicing.',
]},

{id:65,name:'Herby Lamb & Beans',category:'Meat & Poultry',difficulty:'medium',serves:4,time:'50 min',calories:480,mainIngredient:'Lamb',
ingredients:[
  {name:'Lamb mince',amount:500,unit:'g'},
  {name:'Fennel seeds',amount:5,unit:'g'},
  {name:'Ground cumin',amount:2,unit:'g'},
  {name:'Dried oregano',amount:2,unit:'g'},
  {name:'Garlic clove',prep:'crushed',amount:1,unit:'clove'},
  {name:'Olive oil',amount:30,unit:'ml'},
  {name:'Onion',prep:'diced',amount:1,unit:'whole'},
  {name:'Cumin seeds',amount:5,unit:'g'},
  {name:'Cannellini beans',prep:'rinsed',amount:800,unit:'g'},
  {name:'Chicken stock',amount:240,unit:'ml'},
  {name:'Fennel bulb',prep:'sliced',amount:1,unit:'small'},
  {name:'Parsley leaves',amount:1,unit:'cup'},
  {name:'Mint leaves',amount:0.5,unit:'cup'},
  {name:'Anchovy fillets',amount:2,unit:'whole'},
  {name:'Capers',amount:15,unit:'g'},
  {name:'Lemon zest and juice',amount:1,unit:'lemon'},
],
steps:[
  'Make salsa verde: finely chop herbs, anchovies, a shallot and capers. Mix with lemon zest, juice and 60 ml olive oil.',
  'Mix lamb mince with fennel seeds, cumin, oregano, garlic, salt and pepper. Roll into balls.',
  'Brown meatballs in a skillet in oil. Set aside.',
  'Sauté onion, garlic and cumin seeds. Add beans, stock and sliced fennel. Simmer 10 minutes.',
  'Return meatballs to pan and cook 10 minutes. Serve topped with salsa verde and a fennel salad.',
]},

{id:66,name:'Slow-Roast Lamb Shoulder with Anchovy, Garlic & Rosemary',category:'Meat & Poultry',difficulty:'medium',serves:4,time:'4 hr',calories:560,mainIngredient:'Lamb',
ingredients:[
  {name:'Lamb shoulder, bone-in',amount:1750,unit:'g'},
  {name:'Anchovy fillets',amount:6,unit:'whole'},
  {name:'Garlic cloves',amount:4,unit:'cloves'},
  {name:'Fresh rosemary sprigs',amount:2,unit:'sprigs'},
  {name:'Olive oil',amount:45,unit:'ml'},
  {name:'White wine',amount:250,unit:'ml'},
],
steps:[
  'Heat oven to 160°C. Make small incisions across the lamb and stuff with anchovy pieces, garlic slivers and rosemary.',
  'Rub all over with olive oil, season well. Place in roasting dish with white wine.',
  'Cover tightly with foil and roast 3½–4 hours until meat falls from the bone.',
  'Rest 20 minutes before carving. Serve with pan juices.',
]},

{id:67,name:'Umami Lamb Cutlets with Miso Butter & Cabbage',category:'Meat & Poultry',difficulty:'medium',serves:4,time:'25 min',calories:420,mainIngredient:'Lamb',
ingredients:[
  {name:'Savoy cabbage',prep:'cut into wedges',amount:1,unit:'whole'},
  {name:'Sesame oil',amount:30,unit:'ml'},
  {name:'Lamb cutlets, trimmed',amount:12,unit:'whole'},
  {name:'White miso paste',amount:30,unit:'g'},
  {name:'Unsalted butter',prep:'softened',amount:100,unit:'g'},
  {name:'Furikake',amount:15,unit:'g'},
],
steps:[
  'Heat grill pan or barbecue on high. Brush cabbage wedges with sesame oil and cook 6 minutes until charred.',
  'Brush lamb cutlets with remaining sesame oil. Grill 3 minutes each side for medium-rare.',
  'Melt butter in a small pan and stir in miso paste until combined.',
  'Serve lamb with charred cabbage, drizzle miso butter over everything and sprinkle with furikake.',
]},

// ── VEGETARIAN ───────────────────────────────────────────
{id:68,name:'Butternut Pumpkin Ravioli with Sage Butter',category:'Vegetarian',difficulty:'hard',serves:4,time:'90 min',calories:480,mainIngredient:'Pumpkin',
ingredients:[
  {name:'Plain flour',amount:300,unit:'g'},
  {name:'Eggs',amount:3,unit:'whole'},
  {name:'Butternut pumpkin, roasted and mashed',amount:500,unit:'g'},
  {name:'Ricotta',amount:200,unit:'g'},
  {name:'Parmesan',prep:'grated',amount:50,unit:'g'},
  {name:'Ground nutmeg',amount:2,unit:'g'},
  {name:'Butter',amount:100,unit:'g'},
  {name:'Fresh sage leaves',amount:8,unit:'leaves'},
],
steps:[
  'Make pasta dough: mix flour and eggs, knead 10 minutes until smooth. Wrap and rest 30 minutes.',
  'Mix roasted pumpkin, ricotta, parmesan, nutmeg, salt and pepper for filling.',
  'Roll pasta dough very thin. Cut into rounds. Place a spoonful of filling on half, seal with another round.',
  'Boil ravioli in salted water 3–4 minutes until tender. Drain.',
  'Melt butter in a pan until golden, add sage leaves until crisp. Toss ravioli in sage butter and serve.',
]},

{id:69,name:'Cauliflower Steaks with Tahini & Pomegranate',category:'Vegetarian',difficulty:'medium',serves:4,time:'35 min',calories:280,mainIngredient:'Cauliflower',
ingredients:[
  {name:'Large cauliflower, cut into 4 thick steaks',amount:1,unit:'whole'},
  {name:'Olive oil',amount:45,unit:'ml'},
  {name:'Ground cumin',amount:5,unit:'g'},
  {name:'Ground coriander',amount:5,unit:'g'},
  {name:'Smoked paprika',amount:2,unit:'g'},
  {name:'Tahini',amount:30,unit:'g'},
  {name:'Lemon juice',amount:30,unit:'ml'},
  {name:'Garlic clove',prep:'crushed',amount:1,unit:'clove'},
  {name:'Pomegranate seeds',amount:60,unit:'g'},
  {name:'Parsley',prep:'chopped',amount:1,unit:'handful'},
],
steps:[
  'Heat oven to 200°C. Place cauliflower steaks on a tray, drizzle with oil, sprinkle spices and season.',
  'Roast 25–30 minutes until golden and tender.',
  'Mix tahini, lemon juice, garlic and 30 ml water into a sauce.',
  'Drizzle sauce over roasted cauliflower. Scatter pomegranate seeds and parsley.',
]},

{id:70,name:'Ratatouille',category:'Vegetarian',difficulty:'medium',serves:4,time:'40 min',calories:220,mainIngredient:'Eggplant',
ingredients:[
  {name:'Eggplant',prep:'diced',amount:1,unit:'whole'},
  {name:'Zucchinis',prep:'diced',amount:2,unit:'whole'},
  {name:'Red capsicum',prep:'diced',amount:1,unit:'whole'},
  {name:'Yellow capsicum',prep:'diced',amount:1,unit:'whole'},
  {name:'Onion',prep:'chopped',amount:1,unit:'whole'},
  {name:'Garlic cloves',prep:'chopped',amount:3,unit:'cloves'},
  {name:'Tinned chopped tomatoes',amount:400,unit:'g'},
  {name:'Olive oil',amount:45,unit:'ml'},
  {name:'Dried oregano',amount:5,unit:'g'},
  {name:'Fresh basil leaves',amount:1,unit:'handful'},
],
steps:[
  'Heat olive oil in a large pan. Fry onion and garlic until soft.',
  'Add eggplant, zucchini and both capsicums. Cook 10 minutes, stirring.',
  'Stir in tomatoes, oregano, salt and pepper. Simmer 20–25 minutes until very tender.',
  'Scatter basil leaves and serve.',
]},

{id:71,name:'Simple Chickpea Curry',category:'Vegetarian',difficulty:'medium',serves:4,time:'30 min',calories:360,mainIngredient:'Chickpeas',
ingredients:[
  {name:'Vegetable oil',amount:30,unit:'ml'},
  {name:'Onion',prep:'finely chopped',amount:1,unit:'whole'},
  {name:'Garlic cloves',prep:'minced',amount:3,unit:'cloves'},
  {name:'Fresh ginger',prep:'grated',amount:15,unit:'g'},
  {name:'Ground cumin',amount:10,unit:'g'},
  {name:'Ground coriander',amount:10,unit:'g'},
  {name:'Ground turmeric',amount:5,unit:'g'},
  {name:'Garam masala',amount:5,unit:'g'},
  {name:'Chickpeas, drained',amount:400,unit:'g'},
  {name:'Tinned chopped tomatoes',amount:400,unit:'g'},
  {name:'Vegetable stock',amount:250,unit:'ml'},
  {name:'Coconut milk',amount:100,unit:'ml'},
  {name:'Fresh coriander, to serve',amount:1,unit:'handful'},
],
steps:[
  'Heat oil in a pot. Fry onion, garlic and ginger until very soft, about 8 minutes.',
  'Stir in all spices and cook 1 minute until fragrant.',
  'Add chickpeas, tomatoes, stock and coconut milk. Simmer 20 minutes until thickened.',
  'Season and serve with rice and fresh coriander.',
]},

{id:72,name:'Stuffed Capsicums with Rice & Herbs',category:'Vegetarian',difficulty:'medium',serves:4,time:'55 min',calories:380,mainIngredient:'Capsicum',
ingredients:[
  {name:'Large red capsicums',amount:4,unit:'whole'},
  {name:'Basmati rice',amount:200,unit:'g'},
  {name:'Olive oil',amount:30,unit:'ml'},
  {name:'Onion',prep:'finely chopped',amount:1,unit:'whole'},
  {name:'Garlic cloves',prep:'chopped',amount:2,unit:'cloves'},
  {name:'Tomatoes',prep:'chopped',amount:2,unit:'whole'},
  {name:'Parsley',prep:'chopped',amount:1,unit:'handful'},
  {name:'Dill',prep:'chopped',amount:1,unit:'handful'},
],
steps:[
  'Heat oven to 180°C. Slice tops off capsicums and remove seeds.',
  'Cook rice until just tender, drain.',
  'Sauté onion and garlic in oil until soft. Add tomatoes and cook briefly. Stir through rice, herbs, salt and pepper.',
  'Stuff capsicums, replace tops. Place in a baking dish, drizzle with oil.',
  'Bake 35–40 minutes until capsicums are tender.',
]},

{id:73,name:'Stuffed Mushrooms with Herbs & Cheese',category:'Vegetarian',difficulty:'easy',serves:3,time:'30 min',calories:280,mainIngredient:'Mushrooms',
ingredients:[
  {name:'Large field mushrooms, stalks removed',amount:6,unit:'whole'},
  {name:'Olive oil',amount:30,unit:'ml'},
  {name:'Onion',prep:'finely chopped',amount:1,unit:'whole'},
  {name:'Garlic cloves',prep:'chopped',amount:2,unit:'cloves'},
  {name:'Breadcrumbs',amount:60,unit:'g'},
  {name:'Grated cheddar or parmesan',amount:100,unit:'g'},
  {name:'Parsley',prep:'chopped',amount:1,unit:'handful'},
  {name:'Fresh thyme leaves',amount:1,unit:'handful'},
],
steps:[
  'Heat oven to 180°C. Place mushroom caps on a lined baking tray.',
  'Sauté onion and garlic in oil until soft. Stir in breadcrumbs, cheese, herbs, salt and pepper.',
  'Spoon filling into each mushroom cap.',
  'Bake 20 minutes until golden and bubbling.',
]},

// ── PASTA & RICE ──────────────────────────────────────────
{id:74,name:'Clam Pasta with Garum, Bottarga & Verjuice',category:'Pasta & Rice',difficulty:'medium',serves:4,time:'25 min',calories:520,mainIngredient:'Clams',
ingredients:[
  {name:'Small clams',prep:'rinsed',amount:500,unit:'g'},
  {name:'Spaghetti',amount:400,unit:'g'},
  {name:'Olive oil',amount:45,unit:'ml'},
  {name:'Garlic cloves',prep:'thinly sliced',amount:3,unit:'cloves'},
  {name:'Red chilli',prep:'finely sliced',amount:1,unit:'whole'},
  {name:'Verjuice',amount:60,unit:'ml'},
  {name:'Garum',amount:30,unit:'ml'},
  {name:'Bottarga, finely grated',amount:25,unit:'g'},
  {name:'Parsley',prep:'chopped',amount:1,unit:'handful'},
],
steps:[
  'Cook spaghetti in salted boiling water until al dente. Reserve 1 cup cooking water, drain.',
  'Heat olive oil, add garlic and chilli, cook until fragrant.',
  'Increase heat, add clams and verjuice. Cover 2–3 minutes until clams open. Discard any that remain closed.',
  'Add garum, pasta and a splash of cooking water. Toss to coat.',
  'Stir through bottarga and parsley. Serve with lemon wedges and extra bottarga.',
]},

{id:75,name:'Spaghetti alle Vongole',category:'Pasta & Rice',difficulty:'medium',serves:4,time:'25 min',calories:480,mainIngredient:'Clams',
ingredients:[
  {name:'Spaghetti',amount:400,unit:'g'},
  {name:'Vongole (clams)',prep:'rinsed',amount:1000,unit:'g'},
  {name:'Olive oil',amount:45,unit:'ml'},
  {name:'Garlic cloves',prep:'thinly sliced',amount:3,unit:'cloves'},
  {name:'Red chilli',prep:'finely sliced',amount:1,unit:'small'},
  {name:'White wine',amount:150,unit:'ml'},
  {name:'Parsley',prep:'chopped',amount:1,unit:'handful'},
],
steps:[
  'Cook spaghetti until al dente, reserving some cooking water.',
  'Heat oil in a wide pan. Fry garlic and chilli until fragrant.',
  'Add clams and white wine. Cover and cook 2–3 minutes until clams open. Discard any unopened ones.',
  'Toss pasta with clams, parsley and a splash of cooking water. Season well.',
]},

{id:76,name:'Tuna Pasta with Chilli, Capers & Lemon',category:'Pasta & Rice',difficulty:'easy',serves:4,time:'25 min',calories:480,mainIngredient:'Tuna',
ingredients:[
  {name:'Spaghetti',amount:400,unit:'g'},
  {name:'Olive oil',amount:30,unit:'ml'},
  {name:'Day-old sourdough, blitzed to crumbs',amount:2,unit:'slices'},
  {name:'Small onion',prep:'finely chopped',amount:1,unit:'whole'},
  {name:'Garlic cloves',prep:'finely sliced',amount:3,unit:'cloves'},
  {name:'Long red chilli',prep:'finely chopped',amount:1,unit:'small'},
  {name:'Salted capers, rinsed',amount:60,unit:'g'},
  {name:'Tuna in olive oil',prep:'drained',amount:160,unit:'g'},
  {name:'Lemon zest and juice',amount:1,unit:'lemon'},
  {name:'Flat-leaf parsley',prep:'chopped',amount:1,unit:'handful'},
],
steps:[
  'Cook spaghetti until al dente. Drain, reserving a splash of cooking water.',
  'Fry breadcrumbs in oil until golden. Season and set aside.',
  'In same pan, cook onion until soft. Add garlic, chilli and capers, cook 1 minute.',
  'Flake in tuna, add pasta, a splash of cooking water, lemon zest and juice. Toss.',
  'Stir in parsley, season and top with golden breadcrumbs.',
]},

{id:77,name:'Pasta alla Norma',category:'Pasta & Rice',difficulty:'medium',serves:4,time:'40 min',calories:460,mainIngredient:'Eggplant',
ingredients:[
  {name:'Rigatoni or spaghetti',amount:400,unit:'g'},
  {name:'Large eggplants, diced',amount:2,unit:'whole'},
  {name:'Olive oil for frying',amount:80,unit:'ml'},
  {name:'Onion',prep:'chopped',amount:1,unit:'whole'},
  {name:'Garlic cloves',prep:'chopped',amount:2,unit:'cloves'},
  {name:'Tinned chopped tomatoes',amount:400,unit:'g'},
  {name:'Tomato paste',amount:15,unit:'g'},
  {name:'Fresh basil leaves',amount:1,unit:'handful'},
  {name:'Ricotta salata',prep:'grated',amount:100,unit:'g'},
],
steps:[
  'Fry eggplant in batches in olive oil until golden. Set aside.',
  'In the same pan, sauté onion and garlic. Add tomatoes and paste, simmer 15 minutes. Season.',
  'Cook pasta until al dente. Drain.',
  'Toss pasta with sauce and fried eggplant.',
  'Serve topped with fresh basil and grated ricotta salata.',
]},

{id:78,name:'Mushroom Risotto',category:'Pasta & Rice',difficulty:'medium',serves:4,time:'35 min',calories:520,mainIngredient:'Mushrooms',
ingredients:[
  {name:'Olive oil',amount:30,unit:'ml'},
  {name:'Onion',prep:'finely chopped',amount:1,unit:'whole'},
  {name:'Garlic cloves',prep:'chopped',amount:2,unit:'cloves'},
  {name:'Arborio rice',amount:300,unit:'g'},
  {name:'White wine',amount:150,unit:'ml'},
  {name:'Hot chicken or vegetable stock',amount:1000,unit:'ml'},
  {name:'Mixed mushrooms',prep:'sliced',amount:300,unit:'g'},
  {name:'Butter',amount:50,unit:'g'},
  {name:'Parmesan',prep:'grated',amount:60,unit:'g'},
  {name:'Parsley',prep:'chopped',amount:1,unit:'handful'},
],
steps:[
  'Heat oil in a large pan. Sauté onion and garlic until soft.',
  'Add rice, stir to coat, then pour in wine. Cook until absorbed.',
  'Add hot stock a ladle at a time, stirring continuously until each is absorbed, about 18 minutes total.',
  'In a separate pan, sauté mushrooms in butter until golden. Stir into risotto with parmesan.',
  'Season, scatter parsley and serve immediately.',
]},

]; // end recipes2
